### ISSUE TITLE
Is it possible to recover a lost preset dictionary?

### ISSUE THREAD

**Issue by redditanalytics** [madler/zlib#100]
Mark,

Thanks so much for maintaining this excellent piece of software.  My question is a generic one.  I use zlib delate and inflate with a preset dictionary to help increase compression for short strings.  I was curious if it would be possible to recover a lost preset dictionary in some fashion?  If a dictionary is lost, are there steps to recover it -- especially if one knows the expected decompressed output?

Thanks again Mark for all your work!

**Comment by madler** [comment]
If you have the expected decompressed output, then you would be able to reconstruct only those parts of the preset dictionary that are used by the compressed data.
