### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Chaitanya887** [madler/zlib#1003]
- Addition of book collection tab to the Android mobile app so that we can access any personal book collection. At the present moment, we can only access favorites and downloaded books under My Book section through the app.
 - In the online reader, if we select a word can we get the meaning of the word then and there, this feature will ensure to increase the vocabulary of the audience and make sure they don't have to go to any other app to get the meaning of the word.

**Comment by madler** [comment]
This is not that.
