### ISSUE TITLE
Looking for documentation on zipOpenNewFileInZip4 specially the versionMadeBy paramter

### ISSUE THREAD

**Issue by Neena1414** [madler/zlib#1006]
What and how should the values be given to versionMadeBy field  for zipOpenNewFileInZip4  utility function. Is there  any documentation

**Comment by madler** [comment]
Yes. Look in the [PKWare appnote](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT). Section 4.4.2 details what the field means and has a table of operating systems. Section 4.4.3 has a list of versions for use in the other byte.

**Comment by Neena1414** [comment]
Thank You for this. Would you have reference of a sample client call to know a working example. The minizip test program does not use zipOpenNewFileInZip4

**Comment by madler** [comment]
I do not.
