### ISSUE TITLE
I get inconsistent results between C and python when uncompressing certain raw deflate streams

### ISSUE THREAD

**Issue by sgmihai** [madler/zlib#1008]
Trying to write a nntp client library in Nim, and to implement comperssion I need support for raw deflate.
For some reason decompression doesn't work on any of the deflate compressed data i get as messages from the server.
I tried the same data with zlib from python, and it works there. Also tried raw C to make sure it's not a nim library wrapper issue.
https://play.nim-lang.org/#pasty=OKkTiTma
https://www.online-python.com/O5FjtZKr4c

I've already wasted a few hours on this issue and lacking more advanced debugging skills, I ask you if you have any idea what is going on here. I found out that incrementing the first byte in the example above by 1, makes it decompress in nim/c.
Other such problematic byte values examples:
https://pastebin.com/raw/NUaWie6K https://pastebin.com/raw/b07c8kst
These also work without a problem in python

**Comment by madler** [comment]
Please pose your question on stackoverflow.com. As presented, this is not a zlib issue. Thanks.
