### ISSUE TITLE
Is it possible to backport new functionality of gzbuffer() to boost file writing performance from zlib-1.2.5 to zlib-1.2.3?

### ISSUE THREAD

**Issue by ingvagabund** [madler/zlib#101]
Hi,

Is it possible to backport new functionality of gzbuffer() to boost file writing performance from zlib-1.2.5 to zlib-1.2.3? Updating to zlib-1.2.5 breaks libxml2 because of a known bug [1] of libxml2 relying on undocumented internals. libxml2 can not be updated.

I can not find any notes on this new functionality in changelog so can not say if it is 1.2.5.1 or 1.2.5.2 or other.

[1] http://osdir.com/ml/svn-commits-list/2010-01/msg05723.html

Thanks
Jan

**Comment by madler** [comment]
> On May 20, 2015, at 1:40 AM, ingvagabund <notifications@github.com> wrote:
> 
> Hi,
> 
> Is it possible to backport new functionality of gzbuffer() to boost file writing performance from zlib-1.2.5 to zlib-1.2.3? Updating to zlib-1.2.5 breaks libxml2 because of a known bug [1] of libxml2 relying on undocumented internals. libxml2 can not be updated.

No, since the bug in libxml2 was revealed by those same changes to the gz functions.  So if you succeeded in changing out the gz* code in 1.2.3 to be the same as in 1.2.5, then you would see the same libxml2 bug.

Mark

**Comment by ingvagabund** [comment]
Thank you for the answer.
