### ISSUE TITLE
Coverity complaint about overflow in crc32_z

### ISSUE THREAD

**Issue by nigoroll** [madler/zlib#1010]
We import zlib into [Varnish-Cache](https://github.com/varnishcache/varnish-cache) and as such also run it through [coverity](https://scan.coverity.com/projects/varnish), which started to complain (on 2024-06-24, possibly related to the import being upgraded to 1.3.0 ?) about an overflow (I would rather think it was an underflow) here:

https://github.com/madler/zlib/blob/d476828316d05d54c6fd6a068b121b30c147b5cd/crc32.c#L779

Coverity reasons that before the statement `blks` could be zero, which would obviously result in SIZE_MAX iterations of the loop. I do not understand the code well enough to be certain that `blks = len / (N * W);` can not possibly result in `blks` being assigned zero, so maybe the code could be restructured or an assertion added?

Ref Coverity CID 1605324

FYI @dridi @bsdphk

**Comment by madler** [comment]
Perhaps Coverity needs to be smarter. Or at least more certain about things before it complains about them. This is in a block that starts with:

```
    if (len >= N * W + W - 1) {
```

Then as you note:

```
        blks = len / (N * W);
```

Previous `#ifdef`'s assure that if `N` and `W` are defined, they are positive. (In particular in 1..6 and 4 or 8 respectively.)

So `blks` is at least 1.
