### ISSUE TITLE
Multi-threading support

### ISSUE THREAD

**Issue by hjarnek** [madler/zlib#1013]
Hi,

Any plans to add support for multi-threaded compression in zlib, similar to pigz? That speed improvement would be very welcome when implementing gzipped file handling in your own programs.

**Comment by madler** [comment]
Yes, I plan to. Though it may be a separate package in C++ that uses zlib, since threads are more portable and better supported in C++.

**Comment by hjarnek** [comment]
Alright, nice to hear! Thanks for the super-quick response. Looking forward to multi-threaded support.
