### ISSUE TITLE
Deflate/inflate roundtrip fails when `MAX_WBITS=8` and `MAX_MEM_LEVEL=4`

### ISSUE THREAD

**Issue by twpayne** [madler/zlib#1020]
## Short problem description

With zlib 1.3.1 and zlib at the latest `develop` branch (commit d476828316d05d54c6fd6a068b121b30c147b5cd), `MAX_WBITS` set to 8, and `MAX_MEM_LEVEL` set to 4, `deflate` creates streams that `inflate`, with the same configuration, fails to decompress. Instead, `inflate` returns the error `Z_DATA_ERROR`.

## Steps to reproduce

1. Build zlib with `-DMAX_WBITS=8 -DMAX_MEM_LEVEL=4`.
2. Compile and run the following program, which is a minimal program that reproduces the problem.

```c
#undef NDEBUG // Undefine NDEBUG so we can use assert() with side effects.
#include <assert.h>
#include <stdio.h>
#include <string.h>

#include "zlib.h"

int main() {
    char *input = "Hello, world!";
    uInt input_len = strlen(input);
    
    printf("input is %s\n", input);

    // Deflate.
    Bytef compressed[32] = {0};
    uInt compressed_len = 0;
    {
        z_stream strm = {0};
        assert(deflateInit(&strm, Z_DEFAULT_COMPRESSION) == Z_OK);
        strm.next_in = input;
        strm.avail_in = input_len;
        strm.next_out = compressed;
        strm.avail_out = sizeof compressed;
        assert(deflate(&strm, Z_FINISH) == Z_STREAM_END);
        compressed_len = sizeof compressed - strm.avail_out;
        assert(deflateEnd(&strm) == Z_OK);
    }
    
    printf("compressed data is %d bytes\n", compressed_len);
    printf("stream is {");
    for (int i = 0; i < compressed_len; i++) {
        if (i != 0) {
            printf(", ");
        }
        printf("0x%02x", compressed[i]);
    }
    printf("}\n");
    
    // Inflate.
    Bytef output[32] = {0};
    uInt output_len = 0;
    {
        z_stream strm = {0};
        assert(inflateInit(&strm) == Z_OK);
        strm.next_in = compressed;
        strm.avail_in = compressed_len;
        strm.next_out = output;
        strm.avail_out = sizeof output;
        int ret = inflate(&strm, Z_FINISH);
        if (ret != Z_STREAM_END) {
            printf("inflate returned %d\n", ret);
        }
        assert(ret == Z_STREAM_END);
        output_len = sizeof output - strm.avail_out;
        assert(inflateEnd(&strm) == Z_OK);
    }
    
    printf("output is %*s\n", output_len, output);
    
    return 0;
}
```

This program is available as a gist: https://gist.github.com/twpayne/77c724d80f3c907a579382c1c8533942

### Expected output

The program should deflate and inflate the string `Hello, world` without error.

### Actual output

`inflate` returns `Z_STREAM_ERROR`:

```console
$ gcc -o reflate test/reflate.c libz.a && ./reflate
input is Hello, world!
compressed data is 21 bytes
stream is {0x18, 0x95, 0xf3, 0x48, 0xcd, 0xc9, 0xc9, 0xd7, 0x51, 0x28, 0xcf, 0x2f, 0xca, 0x49, 0x51, 0x04, 0x00, 0x20, 0x5e, 0x04, 0x8a}
inflate returned -3
reflate: test/reflate.c:53: main: Assertion `ret == Z_STREAM_END' failed.
```

## Further information

* The problem does not occur when `MAX_WBITS=9` (one larger) and `MAX_MEM_LEVEL=4` (same value), i.e. increasing `MAX_WBITS` to 9 means the deflate/inflate round trip succeeds.
* The stream generated by `deflate` is a valid stream, and is successfully inflated by a decompressor with larger parameters.
* The reason for using such small values is to run zlib on a microcontroller with only a few kilobytes of RAM. The real life data to be compressed is very repetitive, so even with these small parameters, zlib compresses the data very well.

**Comment by madler** [comment]
This is known. From zlib.h:

>      For the current implementation of deflate(), a windowBits value of 8 (a
>    window size of 256 bytes) is not supported.  As a result, a request for 8
>    will result in 9 (a 512-byte window).  In that case, providing 8 to
>    inflateInit2() will result in an error when the zlib header with 9 is
>    checked against the initialization of inflate().

`MAX_WBITS=8` results in forcing `windowBits` to be 8 for both deflate and inflate. As noted, that will fail.

I will add a check at compile time to reject `MAX_WBITS` values outside of 9..15, for those that do not read the documentation.

By the way, you should not put operations with necessary side effects inside an `assert()`, since there is an option to remove all of the asserts in production executables. You should instead:

```c
        int ret = deflateInit(&strm, Z_DEFAULT_COMPRESSION);
        assert(ret == Z_OK);
```

**Comment by madler** [comment]
https://github.com/madler/zlib/commit/ef24c4c7502169f016dcd2a26923dbaf3216748c

**Comment by twpayne** [comment]
> This is known.

Thank you very much for the swift response and sorry that I missed the documentation on this. I was looking at the [documentation in `zconf.h.in`](https://github.com/madler/zlib/blob/ef24c4c7502169f016dcd2a26923dbaf3216748c/zconf.h.in#L274-L294), and missed the comment in `zlib.h`. Adding a compile-time check is the perfect solution for catching all misuse, thank you.



> By the way, you should not put operations with necessary side effects inside an `assert()`, since there is an option to remove all of the asserts in production executables.

I agree. The reproduction case above was written to be as short as possible and includes the line:

```c
#undef NDEBUG // Undefine NDEBUG so we can use assert() with side effects.
```

Thanks again for the fast response and fix!
