### ISSUE TITLE
Building Glib for armv8 Processor

### ISSUE THREAD

**Issue by aagmangour** [madler/zlib#109]
I want to build Glib for ARMv8 (AARCH64) processor. I am getting the following error.Anyone having any idea about how to proceed .please help

Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../gobject/gtype.h:1531:7: note: in expansion of macro 'g_once_init_enter'
   if (g_once_init_enter (&g_define_type_id__volatile))  \
       ^
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../gobject/gtype.h:1465:61: note: in expansion of macro '_G_DEFINE_INTERFACE_EXTENDED_BEGIN'
 #define G_DEFINE_INTERFACE_WITH_CODE(TN, t_n, T_P, _C_)     _G_DEFINE_INTERFACE_EXTENDED_BEGIN(TN, t_n, T_P) {_C_;} _G_DEFINE_INTERFACE_EXTENDED_END()
                                                             ^
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../gobject/gtype.h:1446:47: note: in expansion of macro 'G_DEFINE_INTERFACE_WITH_CODE'
 #define G_DEFINE_INTERFACE(TN, t_n, T_P)      G_DEFINE_INTERFACE_WITH_CODE(TN, t_n, T_P, ;)
                                               ^
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../gio/gproxy.c:45:1: note: in expansion of macro 'G_DEFINE_INTERFACE'
 G_DEFINE_INTERFACE (GProxy, g_proxy, G_TYPE_OBJECT)
 ^
In file included from /Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../android/glibconfig.h:9:0,
                 from /Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../android/config.h:500,
                 from /Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../gio/gproxy.c:23:
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../glib/gmacros.h:162:53: error: size of array '_GStaticAssertCompileTimeAssertion_1' is negative
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                                     ^
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../glib/gmacros.h:159:47: note: in definition of macro 'G_PASTE_ARGS'
 #define G_PASTE_ARGS(identifier1,identifier2) identifier1 ## identifier2
                                               ^
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../glib/gmacros.h:162:44: note: in expansion of macro 'G_PASTE'
 #define G_STATIC_ASSERT(expr) typedef char G_PASTE (_GStaticAssertCompileTimeAssertion_, __COUNTER__)[(expr) ? 1 : -1] G_GNUC_UNUSED
                                            ^
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../glib/gthread.h:257:5: note: in expansion of macro 'G_STATIC_ASSERT'
     G_STATIC_ASSERT (sizeof *(location) == sizeof (gpointer));       \
     ^
/Users/aagman/Desktop/glib/glib-2.35.8-for-android/glib-2.35.8/jni/../gobject/gtype.h:1547:7: note: in expansion of macro 'g_once_init_leave'
       g_once_init_leave (&g_define_type_id__volatile, g_define_type_id); \

**Comment by madler** [comment]
You need to observe the subtle difference between the letter Z and the letter G.
