### ISSUE TITLE
deflate.c:887:54: runtime error: left shift of negative value -1

### ISSUE THREAD

**Issue by crrodriguez** [madler/zlib#122]
883     /* Make sure there is something to do and avoid duplicate consecutive
 884      * flushes. For repeated and useless calls with Z_FINISH, we keep
 885      * returning Z_STREAM_END instead of Z_BUF_ERROR.
 886      */
 887     } else if (strm->avail_in == 0 && RANK(flush) <= RANK(old_flush) &&
 888                flush != Z_FINISH) {
 889         ERR_RETURN(strm, Z_BUF_ERROR);
 890     }

old_flush may be -1.. RANK(-1) produces undefined behaviour.

How to reproduce : 

Build with gcc 5.2 and fsanitize=undefined
run make check.

hello world
zlib version 1.2.8 = 0x1280, compile flags = 0xa9
uncompress(): hello, hello!
gzread(): hello, hello!
gzgets() after gzseek:  hello!
deflate.c:887:54: runtime error: left shift of negative value -1
inflate(): hello, hello!
large_inflate(): OK
after inflateSync(): hello, hello!
inflate with dictionary: hello, hello!
                *** zlib test OK ***
hello world
zlib version 1.2.8 = 0x1280, compile flags = 0xa9
uncompress(): hello, hello!
gzread(): hello, hello!
gzgets() after gzseek:  hello!
deflate.c:887:54: runtime error: left shift of negative value -1
inflate(): hello, hello!
large_inflate(): OK
after inflateSync(): hello, hello!
inflate with dictionary: hello, hello!
                *** zlib shared test OK ***
hello world
zlib version 1.2.8 = 0x1280, compile flags = 0xa9
uncompress(): hello, hello!
gzread(): hello, hello!
gzgets() after gzseek:  hello!
deflate.c:887:54: runtime error: left shift of negative value -1
inflate(): hello, hello!
large_inflate(): OK
after inflateSync(): hello, hello!
inflate with dictionary: hello, hello!
                *** zlib 64-bit test OK ***

**Comment by mtl1979** [comment]
Fixed in 8a979f6c7986574e37316148cd8ca440c3bc08a3.
