### ISSUE TITLE
iowin32.c, invalid MySetFilePointerEx() in version 1.2.8

### ISSUE THREAD

**Issue by jvanlabeke** [madler/zlib#128]
Code has been factored from previous versions in a MySetFilePointerEx() method which use a dwMoveMethod argument. The code always use the hard value FILE_CURRENT instead of the argument. 

Version 1.2.8:
`static BOOL MySetFilePointerEx(HANDLE hFile, LARGE_INTEGER pos, LARGE_INTEGER *newPos,  DWORD dwMoveMethod)
{
# ifdef IOWIN32_USING_WINRT_API

```
return SetFilePointerEx(hFile, pos, newPos, dwMoveMethod);
```
# else

```
LONG lHigh = pos.HighPart;
DWORD dwNewPos = SetFilePointer(hFile, pos.LowPart, &lHigh, `**FILE_CURRENT**`);`
```

should be:
`static BOOL MySetFilePointerEx(HANDLE hFile, LARGE_INTEGER pos, LARGE_INTEGER *newPos,  DWORD dwMoveMethod)
    {
# ifdef IOWIN32_USING_WINRT_API

```
 return SetFilePointerEx(hFile, pos, newPos, dwMoveMethod);
```
# else

```
LONG lHigh = pos.HighPart;
DWORD dwNewPos = SetFilePointer(hFile, pos.LowPart, &lHigh, `**dwMoveMethod**`);`
```

There is a similar issue in the win32_seek64_file_func() method when calling MySetFilePointerEx()

version 1.2.8:
`if (hFile)
    {
        LARGE_INTEGER pos;
        pos.QuadPart = offset;
        if (!MySetFilePointerEx(hFile, pos, NULL,`**FILE_CURRENT**`))`

should be:

`if (hFile)
    {
        LARGE_INTEGER pos;
        pos.QuadPart = offset;
        if (!MySetFilePointerEx(hFile, pos, NULL,`**dwMoveMethod**`))`

Regards
Julien

**Comment by mtl1979** [comment]
Fixed already in 89e335abb49cd5c7d29d94e8f506d3f8ed71315a.
