### ISSUE TITLE
CMake skip building examples/tests/running tests and installing files? (As submodule)

### ISSUE THREAD

**Issue by MrSapps** [madler/zlib#147]
When using this repo as a submodule I'd like to just build the static lib/dll/so. Is there a way to disable:

-Building example binaries
-Adding/running test (the example binaries)
-Installing files

I noticed there seems to be a skip var for each install section?

if(NOT SKIP_INSTALL_HEADERS AND NOT SKIP_INSTALL_ALL )
    install(FILES ${ZLIB_PUBLIC_HDRS} DESTINATION "${INSTALL_INC_DIR}")
endif()

**Comment by timofonic** [comment]
@paulsapps Did you take a look at this fork? https://github.com/Dead2/zlib-ng/

**Comment by danielalves** [comment]
I created a PR that partially solves this issue: https://github.com/madler/zlib/pull/824
