### ISSUE TITLE
BUG: fixed tables don't match the generated output

### ISSUE THREAD

**Issue by vinniefalco** [madler/zlib#154]
It seems that the fixed table constants in inffixed.h don't match the output produced by `fixedtables()` when `BUILDFIXED` is defined.

The differences occur in array indexes 99, 227, 335, and 483 of the `lencode` table. When `BUILDFIXED` is defined, these elements have `code::op` equal to 72, 78, 72, and 78 respectively. But in the fixed table constants, `op` is 64.

Does this matter?

**Comment by tbeu** [comment]
Hm, cannot reproduce. If I build zlib v1.2.8 with `MAKEFIXED` defined the output of `makefixed()` is identical to file inffixed.h.

**Comment by vinniefalco** [comment]
Right, because the code that prints the C declarations fixes the output here:
https://github.com/madler/zlib/blob/master/inflate.c#L345
Note how 64 is substituted for `state.lencode[low].op`.

But I'm not talking about `MAKEFIXED` I'm talking about `BUILDFIXED`. Specifically this function here:
https://github.com/madler/zlib/blob/master/inflate.c#L261

Why does the output of the function `fixedtables` disagree with the data declarations when `BUILDFIXED` is defined?

**Comment by vinniefalco** [comment]
Anyone?

**Comment by madler** [comment]
Not a bug. 72 and 78 behave just like 64 when using the table for decoding, which is to mark an invalid code.
