### ISSUE TITLE
Small issues spotted by static analyzers

### ISSUE THREAD

**Issue by irwir** [madler/zlib#158]
1) According to standards there is no need to check pointer for null before calling _free()_.
That means, lines 97 and 99 in _zlib\gzread.c_ could be removed.
Also in _zlib\contrib\minizip\unzip.c_ and _zlib\contrib\minizip\zip.c_ macro TRYFREE() might be simplified or replaced with direct free() calls.

2) Inconsistency with _szComment_ pointer usage in  function
_extern int ZEXPORT unzGetGlobalComment (unzFile file, char \* szComment, uLong uSizeBuf)_, file _zlib\contrib\minizip\unzip.c_.
The pointer is dereferenced in line 2068, but checked for null at line 2073.
If check for null is necessary then probably it might be moved up to line 2055 like this:
`if (file==NULL || szComment==NULL)`

**Comment by irwir** [comment]
3) The assignment
`err = ZIP_ERRNO;`
in file _zip.c_, line 1538 does nothing because the value would be uncondicionally overwritten in line 1543.

**Comment by andrewvaughanj** [comment]
@irwir: while this doesn't pertain to fixing these issues directly, how did you find these problems? What "static analysers" (I notice that is a plural!) did you use?

**Comment by madler** [comment]
When you're as old as I am, you know that `free()` wasn't always that way. In any case, I removed the checks in gzread.c. Updated to contributions in contrib need to be made by the respective contributors.

**Comment by irwir** [comment]
It could be seen that minizip code was updated recently.
Had the original contributor got active again or maybe this issue could be reopened for implementation?
