### ISSUE TITLE
Compress or decompress data specified by a pointer.

### ISSUE THREAD

**Issue by AraHaan** [madler/zlib#165]
I would like for there to be a version of comression and decompression where the data that is being pointed would be compressed or decompressed without modifying the original file so that way I can only write the compressed data in a mass body file of all files that I need to process with zlib only to append a special xml header with some other data on top. Also another reason why on this is because I would have to calculate Crc32's for the XML as well.

But the unfortunate thing is that it would have to process the data the pointer is pointing to and point to that data's compressed / decompressed data. But it is better than overwriting the original files.

Yeah Granted the ones that requires a opened file may or may not write to the file that was opened. Who knows. But yeah having a little memory compression/decompression only that is pointed to would be helpful for me. Also it would be nice t have a example on how to use the CRC32 functions as well. I find the example of a simple one on the zlib website to not include CRC32.

**Comment by madler** [comment]
I can't figure out what you're requesting here.

There is a usage example of crc32() in its documentation in zlib.h.

**Comment by AraHaan** [comment]
Well 1 thing I was looking for is memory compression / decompression of a file stream without modifying the file itself. Which would be of use for me on top of the crc32 stuff which I am going to take a look at thanks.

**Comment by madler** [comment]
zlib doesn't modify any files. The whole point of zlib is to provide in-memory compression and decompression.
