### ISSUE TITLE
Visual studio static code analysis on latest release

### ISSUE THREAD

**Issue by boxerab** [madler/zlib#185]
Thanks for maintaining this library!

Here are some warnings from visual studio 2015:   

    \gzlib.c(214): warning C6031: Return value ignored: 'snprintf'.
    \gzlib.c(296): warning C6031: Return value ignored: 'snprintf'.
    \gzlib.c(611): warning C6031: Return value ignored: 'snprintf'.
    \gzread.c(100): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.      Results might not be an expected value.
     \gzread.c(513): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.
     \gzread.c(529): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.
     \gzwrite.c(24): warning C6297: Arithmetic overflow:  32-bit value is shifted, then cast to 64-bit value.  Results might not be an expected value.
     trees.c(534): warning C6385: Reading invalid data from 's->bl_count':  the readable size is '32' bytes, but '-2' bytes may be read.
     \trees.c(550): warning C6385: Reading invalid data from 's->bl_count':  the readable size is '32' bytes, but 'bits' bytes may be read.

**Comment by madler** [comment]
Thanks. The warnings are all non-problems. The last two are especially silly, since the compiler is trying to infer things about how the code will execute when it has no clue whatsoever about what's going on. (Hence the use of the word "may".)

**Comment by boxerab** [comment]
Glad to hear.

**Comment by xorz57** [comment]
I came across this issue while trying to solve a similar one. Thanks for your information @madler.
