### ISSUE TITLE
access to start and stop markers in a stream of compressed files

### ISSUE THREAD

**Issue by ingvarha** [madler/zlib#189]
Two years ago today, I posted this issue to the zlib-devel list. To celebrate this, I'll add a github issue to track any further progress.

Varnish, a fast web cache, uses a library libvgz, which is zlib with a small patch. This patch gives access to start and stop markers in a stream of compressed files. Varnish uses this to sort out edge side includes when putting together http pages from backend servers for http clients. The patch was originally written by Paul-Henning Kamp. He has written some more high level info about the usage of zlib in varnish here: https://varnish-cache.org/docs/trunk/phk/gzip.html

As the downstream maintainer of varnish in Fedora, I would like to see these features added to zlib if possible, to avoid bundling a zlib fork with varnish.

John Reiser added, on the zlib-devel list, in a followup post:

> A call to  deflate(strm, SYNC_FLUSH);  will align the stream to a byte boundary.
> This works even for (0 == strm->avail_in), so such a call may be inserted after any
> other call to deflate(), without modifying or interfering with any existing logic.
> The space cost for aligning the stream is the cost for an empty [zero-length]
> stored block: three bits, plus filler bits to the next byte boundary, plus
> four bytes (00 00 ff ff); see the comments which follow the declaration of
> deflate() in zlib.h.
> 
> Thus it seems to me that the varnish patch is equivalent to an optimization
> to save about 5 bytes of space per marker in the output stream.
> Is this savings valuable enough to make the patch worthwhile? 

I stripped down the changes to a minimal patch attached here. It applies cleanly and runs the test suite on Linux.

Please consider including it in zlib

Best regards,
Ingvar Hagelund

[varnish_zlib.patch.txt](https://github.com/madler/zlib/files/680760/varnish_zlib.patch.txt)

**Comment by bsdphk** [comment]
I second Ingvars request.

**Comment by madler** [comment]
I don't see anything here that can't be done with the `Z_BLOCK` flush option of `deflate()` and `deflatePending()`.

**Comment by madler** [comment]
You can get the same information during decompression, again using `Z_BLOCK`.

**Comment by bsdphk** [comment]
I'll look into that again.  Last I tried it didn't work for me.

**Comment by madler** [comment]
Here is a simple example:

```
// Read a zlib stream from stdin and write the bit positions of each deflate
// block on standard out in decimal, one per line.

#include <stdio.h>
#include <errno.h>
#include "zlib.h"

int main(void) {
    int ret;
    off_t pos;
    z_stream strm;
    unsigned char in[8192];
    unsigned char out[32768];

    strm.zalloc = Z_NULL;
    strm.zfree = Z_NULL;
    strm.opaque = Z_NULL;
    strm.next_in = Z_NULL;
    strm.avail_in = 0;
    ret = inflateInit(&strm);   // use inflateInit2() for gzip or raw
    if (ret != Z_OK)
        return ENOMEM;
    pos = 0;
    do {
        if (strm.avail_in == 0) {
            strm.avail_in = fread(in, 1, sizeof(in), stdin);
            strm.next_in = in;
            pos += strm.avail_in;
        }
        strm.avail_out = sizeof(out);
        strm.next_out = out;
        ret = inflate(&strm, Z_BLOCK);
        if ((strm.data_type & 0xc0) == 0x80)
            printf("%lld\n",
                   ((pos - strm.avail_in) << 3) - (strm.data_type & 7));
    } while (ret == Z_OK);
    inflateEnd(&strm);
    if (ret != Z_STREAM_END)
        return ret == Z_MEM_ERROR ? ENOMEM : EINVAL;
    return 0;
}
```

**Comment by madler** [comment]
I added a `deflateUsed()` function, which gives the number of bits used in the last byte of the just-completed deflate stream. See https://github.com/madler/zlib/commit/e011d8c164402cbb1baf92533dfb4f933ec08fee . The other two things you're looking for, the location of the start of the deflate stream and the location of the first bit of the penultimate deflate block are easily obtained. Here is an example:

```c
// gzip compress stdin to stdout. Show the bit locations of the start of the
// first deflate block, the start of the last deflate block, and the last
// deflate stream bit.

#include <stdio.h>
#include <assert.h>
#include "zlib.h"

// Compress from strm to out with flush. Update the number of bytes written,
// *writ. Return the deflate() return value, or Z_ERRNO if the write failed.
int comp(FILE *out, unsigned long long *writ, z_stream *strm, int flush) {
    unsigned char buf[16384];
    strm->avail_out = sizeof(buf);
    strm->next_out = buf;
    int ret = deflate(strm, flush);
    *writ += fwrite(buf, 1, sizeof(buf) - strm->avail_out, out);
    return ferror(out) ? Z_ERRNO : ret;
}

int main(void) {
    // Initialize gzip deflate.
    z_stream strm = {0};
    int ret = deflateInit2(&strm, -1, 8, 15 + 16, 8, 0);
    assert(ret == Z_OK);

    // Write the gzip header and note its size.
    unsigned long long writ = 0;
    do {
        ret = comp(stdout, &writ, &strm, Z_NO_FLUSH);
    } while (ret == Z_OK);
    assert(ret == Z_BUF_ERROR);
    fprintf(stderr, "first deflate block @ %llu(0)\n", writ);

    // Read and deflate all of input data with Z_NO_FLUSH. This will consume
    // all of the input, and write all but the ultimate deflate block and the
    // last 0-7 bits of penultimate deflate block.
    unsigned char buf[16384];
    do {
        if (strm.avail_in == 0) {
            strm.avail_in = fread(buf, 1, sizeof(buf), stdin);
            assert(!ferror(stdin));
            strm.next_in = buf;
        }
        ret = comp(stdout, &writ, &strm, Z_NO_FLUSH);
    } while (ret == Z_OK);
    assert(ret == Z_BUF_ERROR);
    assert(strm.avail_in == 0);

    // Write the ultimate block. Set left to the number of bits remaining to
    // write from the penultimate block (in 0..7). Show the byte and bit offset
    // of the first bit of the ultimate block.
    int left;
    deflatePending(&strm, Z_NULL, &left);
    fprintf(stderr, "last deflate block @ %llu(%d)\n", writ, left);
    do {
        ret = comp(stdout, &writ, &strm, Z_FINISH);
    } while (ret == Z_OK);
    assert(ret == Z_STREAM_END);

    // Note the location of the last bit in the deflate stream. The length of a
    // gzip trailer is always eight.
    deflateUsed(&strm, &left);
    fprintf(stderr, "last deflate bit @ %llu(%d)\n", writ - 9, left - 1);

    // Clean up.
    deflateEnd(&strm);
    return 0;
}
```

**Comment by dridi** [comment]
Thank you very much for this new `deflateUsed()` function. It looks a lot like what I coincidentally attempted last week, except that I relied on how our current fork works so it would only work for the last block instead of any block emitted.

The function itself is incomplete, I needed to take the level into account for completeness:

```
wrong diff, see below
```

This otherwise does not work when we actually need to flush in the middle of a gzip stream. The reason why we can't solely rely on `Z_NO_FLUSH` is that we sometimes need to collect byte-aligned offsets in the middle of a stream to work with compressed fragments of the original payload. Such a fragment may be at the end of the payload, and we may not know when that payload ends while we are processing it.

**Comment by dridi** [comment]
I was working in a regular zlib and the one in our fork and took the wrong diff.

The one that works for me is:

```diff
--- i/trees.c
+++ w/trees.c
@@ -185,6 +185,8 @@ local void bi_windup(deflate_state *s) {
         put_byte(s, (Byte)s->bi_buf);
     }
     s->bi_used = ((s->bi_valid - 1) & 7) + 1;
+    if (s->level <= 0)
+        s->bi_used += 5;
     s->bi_buf = 0;
     s->bi_valid = 0;
 #ifdef ZLIB_DEBUG
```

I'm not submitting a patch because I wasn't sure how to update the documentation for `deflateUsed()`.

**Comment by dridi** [comment]
https://github.com/madler/zlib/pull/989

**Comment by dridi** [comment]
FYI the comment mentioning `Z_NO_FLUSH` in your code snippet made me wrongly assume that a flush just before a `Z_FINISH` would prevent me from collecting the last bit position.

It turned out to be a red herring, `deflateUsed()` is perfectly usable even with other flags, as long as the input is exhausted before passing the `Z_FINISH` flag. The last problem I was facing was related to the compression level, and I eventually realized that the problem was level zero, the lack of compression.

I updated #989 accordingly.

**Comment by madler** [comment]
What I understand from https://github.com/varnishcache/varnish-cache/wiki/VIP35:-Retire-libvgz is that you need to know:

- start bit (beginning of the first deflate block)
- last bit (beginning of the last deflate block)
- stop bit (end of the last deflate block)

I have provided code that does exactly that. Is there some other requirement?

> as long as the input is exhausted before passing the Z_FINISH flag

You can get the position of the first bit of the ultimate deflate block as long as the input _and the output_ is exhausted. You need to provide all of the input you're going to for this gzip member using `deflate()` with `Z_NO_FLUSH`, and you need to pull output from `deflate()` with `Z_NO_FLUSH` until it has no more to give you. At that point, and only at that point, it has written all of the pentultimate deflate block, except for 0 to 7 bits, where `deflatePending()` gives you that bit count. With the number of compressed bytes produced and that bit count from `deflatePending()`, you now know the starting bit position of the next deflate block, which is the ultimate deflate block with its first bit equal to 1.

None of that has anything to do with `deflateUsed()`, so I don't understand your comment about it being usable in that case. You can get the position of the bit discussed above without it.

Now when `deflate()` is called with `Z_FINISH`, with _no more input_, it will deliver the ultimate deflate block. You would call `deflate()` with `Z_FINISH` (and no more input) as many times as needed to collect the remaining output.

`deflateUsed()` will tell you the number of bits used in the last byte at the _end_ of the ultimate deflate block, after you are done calling `deflate()` with `Z_FINISH`.

**Comment by dridi** [comment]
> I have provided code that does exactly that. Is there some other requirement?

There is a 5bit discrepancy for the stop bit when compression is disabled, see #989.
 
> You can get the position of the first bit of the ultimate deflate block as long as the input _and the output_ is exhausted. You need to provide all of the input you're going to for this gzip member using `deflate()` with `Z_NO_FLUSH`, and you need to pull output from `deflate()` with `Z_NO_FLUSH` until it has no more to give you. At that point, and only at that point, it has written all of the pentultimate deflate block, except for 0 to 7 bits, where `deflatePending()` gives you that bit count. With the number of compressed bytes produced and that bit count from `deflatePending()`, you now know the starting bit position of the next deflate block, which is the ultimate deflate block with its first bit equal to 1.

This is the part where your comment got me confused. I thought I was getting the wrong result in a case where everything else was already flushed before the call with the `Z_FINISH` flag. But I'm operating the way you just described, regardless of what happened before, I'm intercepting deflate calls with `Z_FINISH` and make sure to exhaust both input and output with `Z_NO_FLUSH` transparently.

The case where this was not working happened to have both already flushed the penultimate block and a zero compression level. I wrongly assumed that having already flushed was the reason.

> None of that has anything to do with `deflateUsed()`, so I don't understand your comment about it being usable in that case. You can get the position of the bit discussed above without it.

I'm seeing now that I was referring to the last bit in my previous comment when I meant the stop bit, adding to the confusion.
 
> Now when `deflate()` is called with `Z_FINISH`, with _no more input_, it will deliver the ultimate deflate block. You would call `deflate()` with `Z_FINISH` (and no more input) as many times as needed to collect the remaining output.
> 
> `deflateUsed()` will tell you the number of bits used in the last byte at the _end_ of the ultimate deflate block, after you are done calling `deflate()` with `Z_FINISH`.

And I was able to make it work with the tip of the develop branch.

However, when there is no compression, the stop bit is off by 5, for what I understand is space for an additional forced stored block. In #989 I bridge this gap between directly in `deflateUsed()`.

Apologies for the confusion, I hope I clarified the current situation.

**Comment by madler** [comment]
Understood. Fixed by https://github.com/madler/zlib/commit/884e0c0809e4cc5e88d6545d1c49de7946c1b1ca .

**Comment by dridi** [comment]
I'm still seeing one off-by-5 case with this patch.

**Comment by dridi** [comment]
After a quick check, there seems to be a code path leading to `bi_used` being overwritten in `bi_windup()`.

Applying https://github.com/madler/zlib/pull/989 on top of https://github.com/madler/zlib/commit/884e0c0809e4cc5e88d6545d1c49de7946c1b1ca solves the problem.

**Comment by dridi** [comment]
Never mind, it's a case where `deflate_store()` is never called, so `bi_windup()` needs to account for those extra 5 bits. I see now that `bi_used` is always guaranteed to be 1..8 so the documentation for `deflateUsed()` does not need to change in #989.

**Comment by madler** [comment]
> I'm still seeing one off-by-5 case with this patch.

Can you provide a test case? If `deflate_store()` was not called, then your +5 doesn't run.

**Comment by dridi** [comment]
I added the following test to `example.c`, taking the literal calls made by our test framework in the offending test case. It can probably be simplified using much less input, but I took the path of least resistance to reproduce it in your test suite.

```c
/* ===========================================================================
 * Test Z_NO_COMPRESSION deflate() not calling deflate_store()
 */
static void test_missing_deflate_store(Byte *compr, uLong comprLen,
                       Byte *uncompr, uLong uncomprLen) {
    z_stream c_stream; /* compression stream */
    int err, i;

    c_stream.zalloc = zalloc;
    c_stream.zfree = zfree;
    c_stream.opaque = (voidpf)0;

    err = deflateInit2(&c_stream, Z_NO_COMPRESSION, Z_DEFLATED, 16+15, 8,
        Z_DEFAULT_STRATEGY);
    CHECK_ERR(err, "deflateInit2");

    const struct {
        int avail_out;  /* negative value: expected avail_out */
        int flush;      /* -1: no more deflate() calls */
        int expect;
        const char *in; /* NULL: do not set next_in and avail_in */
    } calls[] = {
        {  4082, Z_NO_FLUSH, Z_OK,         "" },
        { -4072, Z_NO_FLUSH, Z_BUF_ERROR,  NULL },
        { -4072, Z_NO_FLUSH, Z_OK,
            "!~#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_"
            "~#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`"
            "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`a"
            "$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`ab"
            "%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abc"
            "&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcd"
            "'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcde"
            "()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdef"
            ")*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefg"
            "*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefgh"
            "+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghi"
            ",-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghij"
            "-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijk"
            "./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijkl"
            "/0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklm"
            "0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmn"
            "123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmno"
            "23456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnop"
            "3456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopq"
            "456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqr"
            "56789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrs"
            "6789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrst"
            "789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstu"
            "89:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuv"
            "9:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvw"
            ":;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwx"
            ";<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxy"
            "<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz"
            "=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{"
            ">?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|"
            "?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}"
            "@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!"
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~"
            "BCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#"
            "CDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$"
            "DEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%"
            "EFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&"
            "FGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'"
            "GHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'("
            "HIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()"
            "IJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*"
            "JKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+"
            "KLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,"
            "LMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-"
            "MNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-."
            "NOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./"
            "OPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0"
            "PQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./01"
            "QRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./012"
            "RSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123"
            "STUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./01234"
            "TUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./012345"
            "UVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456"
            "VWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./01234567"
            "WXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./012345678"
            "XYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789"
            "YZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:"
            "Z[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;"
            "[\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;<"
            "\]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;<="
            "]^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;<=>"
            "^_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;<=>?"
            "_`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;<=>?@"
            "`abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;<=>?@A"
            "abcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123456789:;<=>?@AB"
            "bcdefghijklmnopqrstuvwxyz{|}!~#$%&'()*+,-./0123"
        },
        { -4072, Z_NO_FLUSH, Z_BUF_ERROR,  NULL },
        { -4072, Z_FINISH,   Z_OK,         NULL },
        {  4096, Z_FINISH,   Z_STREAM_END, NULL },
        {    -1, -1,         -1,           NULL },
    };

    for (i = 0; calls[i].flush >= 0; i++) {
        if (calls[i].avail_out < 0) {
            if (c_stream.avail_out != -calls[i].avail_out) {
                fprintf(stderr, "calls[%i] expected avail_out=%i, got %i\n",
                    i, -calls[i].avail_out, c_stream.avail_out);
                exit(1);
            }
        } else {
            c_stream.next_out = compr;
            c_stream.avail_out = calls[i].avail_out;
        }
        if (calls[i].in != NULL) {
            c_stream.next_in = (Bytef *)calls[i].in;
            c_stream.avail_in = strlen(calls[i].in);
        }
        err = deflate(&c_stream, calls[i].flush);
        if (err != calls[i].expect) {
            fprintf(stderr, "calls[%i] deflate: expected %i, got %i\n",
                i, calls[i].expect, err);
            exit(1);
        }
    }

    err = deflateUsed(&c_stream, &i);
    CHECK_ERR(err, "deflateUsed");

    err = deflateEnd(&c_stream);
    CHECK_ERR(err, "deflateEnd");

    if (i != 8) {
        fprintf(stderr, "deflateUsed: expected 8 bits, got %i\n", i);
        exit(1);
    }
}
```

And when I run it I get the following result:

```
$ make test
hello world
zlib version 1.3.1.1-motley = 0x1311, compile flags = 0xa9
uncompress(): hello, hello!
gzread(): hello, hello!
gzgets() after gzseek:  hello!
inflate(): hello, hello!
large_inflate(): OK
after inflateSync(): hello, hello!
inflate with dictionary: hello, hello!
deflateUsed: expected 8 bits, got 3
		*** zlib test FAILED ***
make: *** [Makefile:85: teststatic] Error 1
```

**Comment by madler** [comment]
Thanks. This should take care of that: https://github.com/madler/zlib/commit/3adaa095a7a6c3f2cc00f73311f9bc8688c21aa7 .

**Comment by dridi** [comment]
Confirmed, this takes care of the remaining failure. Thank you again for the time spent solving our use case.
