### ISSUE TITLE
rpm-4.11.3 fails to install packages built with zlib-1.2.9 installed

### ISSUE THREAD

**Issue by chris2553** [madler/zlib#191]
I've built and installed zlib-1.2.9 on my system (home rolled but based on Linux From Scratch). I've found that rpms created with this system cannot be installed. Nor can their contents be viewed with Midnight Commander (mc).
The error produced by rpm is:
[chris:~/rpm]$ sudo rpm -i x86_64/whois-5.2.14-1.x86_64.rpm 
error: unpacking of archive failed on file /usr/bin/whois;586aad21: cpio: read failed - No such file or directory
error: whois-5.2.14-1.x86_64: install failed
When trying to view an rpm with mc a dialogue box pops up containing the message "Premature end of cpio archive".

If I revert to zlib-1.2.8 and rebuild the rpms, everything is OK, although rpms built when zlib-1.2.9 was installed still cannot be installed.

This table summarises what I have found:

BUILD       INSTALL    RESULT
1.2.8            1.2.8         GOOD
1.2.8            1.2.9         GOOD
1.2.9            1.2.8         FAIL
1.2.9            1.2.9         FAIL

I've bisected the problem and that ended with:
[chris:~/build/zlib]$ git bisect bad
4f1df003ed39280c2e4f62581888a62def3e34fe is the first bad commit
commit 4f1df003ed39280c2e4f62581888a62def3e34fe
Author: Mark Adler <madler@alumni.caltech.edu>
Date:   Tue Apr 5 03:09:59 2016 -0700

    Loop on write() calls in gzwrite.c in case of non-blocking I/O.

:100644 100644 efff93af013c756fd22808e171ce412d18606a36 f07731a423e5d19444c563bd1340ed83be271c41 M      gzwrite.c

Unfortunately, this commit does not revert because of subsequent commits, so I haven't tried that.

**Comment by madler** [comment]
Can you make a corrupt rpm available?

**Comment by chris2553** [comment]
On 02/01/17 21:18, Mark Adler wrote:
> Can you make a corrupt rpm available?
> 

Sure. I've attached one.

**Comment by chris2553** [comment]
Mmm, seems the attachment didn't make it as an attachment to my emailed reply. Nor, it seems, can I attach it to this post, even in a zip archive, which is supposed to be a supported file type. Sorry, I'm a newbie to Github. How do I supply you with this corrupt rpm, please?

**Comment by chris2553** [comment]
On 02/01/17 21:18, Mark Adler wrote:
> Can you make a corrupt rpm available?
> 

The corrupt rpm you asked for.

**Comment by madler** [comment]
Please email it to madler@alumni.caltech.edu . Thanks.

**Comment by madler** [comment]
Fixed in 1.2.10. Thank you for the report.
