### ISSUE TITLE
test suite

### ISSUE THREAD

**Issue by arekm** [madler/zlib#192]
Not sure which build method (cmake or old ./configure && make) is the official way now but seems that each of these method runs different test suite at "make test".

That's the first problem.

Second problem is that running old way - "./configure; make; make test" doesn't exit with non-zero status if any test fails. exit status is always 0 regardless of actual test result.

Fedora, PLD and possibly other distros use 'make test' to run test suite. With exit status being always 0 that test is useless.

**Comment by madler** [comment]
I maintain configure and make, so that is the official way. I test with configure and make, and don't use cmake. The cmake configurations are provided, so those are not as consistent.

I will look at fixing the exit status problem.

**Comment by madler** [comment]
I am finding that `make test` returns a non-zero error code if there is an error.
