### ISSUE TITLE
1.2.10 deflateParams issue

### ISSUE THREAD

**Issue by pmqs** [madler/zlib#198]
Code  [here](https://gist.github.com/pmqs/52c1e397a2510bcfe28b037e62a5046a) a hacked version of examples/zpipe.c
The inflate code has not been changed. The deflate code has been changed to do the following
 

- read block of data
- deflate with Z_NO_FLUSH
- deflate with Z_BLOCK
- deflateParams - level to Z_NO_COMPRESSION

- read block of data
- deflate with Z_NO_FLUSH
- deflate with Z_FINISH

First with zlib 1.2.8

```
$ zpipe < /etc/dictionaries-common/words >/tmp/xxx
 
This is [1.2.8][1.2.8]
DEFLATE out 2, return 0
FLUSH Z_BLOCK 1254, return 0
deflateParams Level to Z_NO_COMPRESSION, got 0
DEFLATE out 0, return 0
FLUSH Z_FINISH 4096, return 0
FLUSH Z_FINISH 9, return 1
RET 1
```

uncompressing with zpipe works without issue.

Now compress with zlib 1.2.10 

```
$ zpipe < /etc/dictionaries-common/words >/tmp/xxx
This is [1.2.10][1.2.10]
DEFLATE out 2, return 0
FLUSH Z_BLOCK 1254, return 0
deflateParams Level to Z_NO_COMPRESSION, got 0
DEFLATE out 0, return 0
FLUSH Z_FINISH 4096, return 0
FLUSH Z_FINISH 4, return 1
RET 1
```

Uncompressing with 1.2.10 I'm seeing Z_DATA_ERROR

```
$ zpipe -d </tmp/xxx >/dev/null
This is [1.2.10][1.2.10]
zpipe: invalid or incomplete deflate data
```

**Comment by madler** [comment]
Fixed https://github.com/madler/zlib/commit/4c7c90768308587884fab6159d93a4695a5ab1f0 .
