### ISSUE TITLE
unzOpen2_64 (unzip.h) function is not able to open the most trivial zip file

### ISSUE THREAD

**Issue by gyokketto** [madler/zlib#199]
Hi,

The function returns null for an empty zip file. I think it should return a valid unzFile pointer and the unzGetGlobalInfo64 should return an unz_global_info64 instance where number_entry is zero.

The zip file (22B): `[0x50,0x4B,0x05,0x06,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00]`
```
zlib_filefunc64_def ffunc;
fill_win32_filefunc64A(&ffunc);
unzFile uf = unzOpen2_64("<path to the zip file>", &ffunc);
```

zlib-1.2.10, Win10, vc14

Thank you.

**Comment by Neustradamus** [comment]
@gvollant: Can you look?

**Comment by madler** [comment]
Applied fix.
