### ISSUE TITLE
Read access violation in inffas32.asm on Win32 build

### ISSUE THREAD

**Issue by ketjow4** [madler/zlib#200]
There is a read access violation in mentioned file. It's on line 669. 

My setup:
-Visual Studio 2015 Community
-Zlib 1.2.11 sources.

I downloaded sources compiled library with projects in contrib/vstudio/vc14. Then I linked it to my own project. When i try to run zpipe.c example in x86(win32) there is read access violation. On x64 it works completely fine, both debug and release. This happen on only decompresion. I managed to compress some file with this library that I build. On run I just redirect that compressed file to stdin. My project is c++ if it can change something.

**Comment by madler** [comment]
You are using someone's DLL that was compiled with assembler code that is not supported. The assembler code is known to have bugs. You should recompile a zlib DLL without assembler code.

**Comment by madler** [comment]
Line 669 of what?

**Comment by ketjow4** [comment]
Line 669 of inffas32.asm. This file is in this repository to be precise in \contrib\masmx86. I downloaded exactly zlib-1.2.11 so the newest version(from this very github) and compiled it by myself with visual studio solutions. I tried to compress some file and it work just great. It's only decompresion in x86 that is not working. 

You earlier said that asm can have bugs but there is no configuration in Visual Studio to build it without ASM in debug. 

You can download my project from:
https://github.com/ketjow4/AKD_Project

It should build without error in VS 2015. All dll are there, one thing you may want to change is comment/uncomment decompresion in main and redirect stdout or stdin.
To replicate the error build x86 debug or release and try to decompress.

**Comment by madler** [comment]
Thanks. Yes, it should not be built with the asm code. I wasn't aware that the Visual Studio configuration was somehow forcing that. Are you referring to what's in contrib/vstudio? If so, I'll try to get that fixed.

What do you mean by "official code"?

**Comment by ketjow4** [comment]
Yes I am referring to contrib/vstudio. What's more there is configuration called ReleaseWithoutASM in this solutions in contrib/vstudio  but it also doesn't work if it can help you somehow. I only tested it on VC14 solution.

Maybe it would be good to metion somewhere that these asm code isn't working or maybe even remove it from repository. From what I can see it wasn't updated since 1.2.5 version of Zlib

Through  "official code" I mean that it is downloaded from this github repository and is not changed by me or anyone else. 

Looking forward for any kind of fix.

**Comment by madler** [comment]
There are warnings you should see when compiling using #pragma message:

```
deflate.c:#  pragma message("Assembler code may have bugs -- use at your own risk")
inffast.c:#  pragma message("Assembler code may have bugs -- use at your own risk")

```

**Comment by madler** [comment]
Technically, nothing in contrib is official code. Those are third-party contributions to zlib.

**Comment by ketjow4** [comment]
Oh I see. I must have missed these warnings. So I will try to build it without asm code.

**Comment by madler** [comment]
I'd like to know if the warnings were displayed and you just didn't notice them, or if they weren't displayed. I think that the pragma message should work in Microsoft C, but I don't have it to test.

**Comment by ketjow4** [comment]
I just didn't notice them. They are displayed on build in Visual Studio output window but these window is usual small so they were written and I missed them. 

Good think is that x64 is working pretty well from what I can see. Could you tell me how to compile this without asm code? If no I think I can do by myself and I will try to write solution here.

**Comment by madler** [comment]
Sorry, no, I don't know anything about Visual Studio projects.

**Comment by theclashingfritz** [comment]
Both things that trigger this are in the projects pre-processor definitions. Remove both ASMV and ASMINF from it and the problem is solved.
