### ISSUE TITLE
automated version check

### ISSUE THREAD

**Issue by HTPCGuides** [madler/zlib#204]
We include this awesome library when building nginx from scratch, we are having to manually update the zlib version in the script and was hoping there was a way to get the current version via the command line to include in the bash script.

**Comment by madler** [comment]
http://zlib.net/current/zlib.tar.gz is the current version.

**Comment by akerl** [comment]
For anybody looking to snag the info on the latest version, I've been pulling it from github tags matching the regex `^v(.*)+`. In my case, it's so I know when to rebuild things against the new zlib, so just being able to point at the current release at build time wasn't enough.
