### ISSUE TITLE
Adding support for position independent code when compiling in static

### ISSUE THREAD

**Issue by sandvige** [madler/zlib#21]
Adding zlib as a static part of a shared library is not supported without editing the Makefile after executing ./configure (with --static), which could be a nice feature.

**Comment by dandesousa** [comment]
For gcc i've used this workaround that doesn't require editing the Makefile.

The work around for this is to set your base CFLAGS:
```
CFLAGS=-fPIC ./configure
```
You can add --static for just generating the static build. This request is pretty old but hopefully its still of use to someone.

**Comment by madler** [comment]
Solution provided by dandesousa.
