### ISSUE TITLE
adler32_combine is broken

### ISSUE THREAD

**Issue by alejolp** [madler/zlib#212]
We've been using ADLER32 to calculate the checksum of some custom data files and we're trying to speed up the process by doing the checksum in threads in parallel. It is my understanding that adler32_combine allows the combination of independent calculations of ADLER32 checksums for example to be used from independent threads, but a test program gives me a wrong result. After some digging I wrapped up the adler32_combine in my own call:

```
/*
$ ./a.out
adler32 buffer1: 4, 325013f
adler32 buffer2: 4, 2cb011e
adler32 buffer3: 8, aec025d
adler32_combine: ae8025c
adler32_combine fix: aec025d
*/

uLong adler32_combine_fix(uLong a1, uLong a2, z_off_t len2) {
    uLong acomb = adler32_combine(a1, a2, len2);
    return (((acomb & 0xffff) + 1) % 65521) | 
        (((((acomb >> 16) & 0xffff) + len2) % 65521) << 16);
}

int main(int argc, char** argv) {
    (void)argc;
    (void)argv;

    const char* buffer1 = DATA1;
    const char* buffer2 = DATA2;
    const char* buffer3 = DATA1 DATA2;

    unsigned int len1 = strlen(buffer1);
    unsigned int len2 = strlen(buffer2);
    unsigned int len3 = strlen(buffer3);

    uLong a1 = adler32(0L, (const Bytef *)buffer1, len1);
    uLong a2 = adler32(0L, (const Bytef *)buffer2, len2);
    uLong a3 = adler32(0L, (const Bytef *)buffer3, len3);
    uLong acomb = adler32_combine(a1, a2, len2);
    uLong acombfix = adler32_combine_fix(a1, a2, len2);

    printf("adler32 buffer1: %u, %lx\n", len1, a1);
    printf("adler32 buffer2: %u, %lx\n", len2, a2);
    printf("adler32 buffer3: %u, %lx\n", len3, a3);

    printf("adler32_combine: %lx\n", acomb);
    printf("adler32_combine fix: %lx\n", acombfix);

    return 0;
}
```

What do you think? Am I missing something? Thanks

**Comment by madler** [comment]
Yes, you are missing something. You are giving the `adler32()` routines the wrong initial value. The initial Adler-32 value is 1, not 0. Per the documentation in zlib.h, the initial value is what is returned by `adler32(0L, Z_NULL, 0)` which is 1.
