### ISSUE TITLE
inflate returns Z_DATA_ERROR

### ISSUE THREAD

**Issue by minhajakhterkhan199** [madler/zlib#213]
Dear,
I am trying to decompress data by calling the inflate function and after decompressing around few thousand bytes inflate through Z_DATA_ERROR  error. Input data is correct and verified by gzip on Ubuntu. 
Please find the function below and advise to resolve the issue.

int Decompress(unsigned char * pDest, unsigned long * ulDestLen, const unsigned char *  pSource, int iSourceLen)
{
    int ret = 0;
    unsigned int uiUncompressedBytes = 0; // Number of uncompressed bytes returned from inflate() function
    unsigned char * pPositionDestBuffer = pDest; // Current position in dest buffer
    unsigned char * pLastSource = &pSource[iSourceLen]; // Last position in source buffer
    z_stream strm;

    // We should now be at the beginning of the stream data
    /* allocate inflate state */
    strm.zalloc = Z_NULL;
    strm.zfree = Z_NULL;
    strm.opaque = Z_NULL;
    strm.avail_in = 0;
    strm.next_in = Z_NULL;
    //ret = inflateInit2(&strm, MAX_WBITS);         // 40       agay error
    ret = inflateInit2(&strm,16 +  MAX_WBITS);                  // 256 , 258, 64    yaha error
    if (ret != Z_OK)
    {
        tau_printf(" inflateInit2: %d \n\r",ret);
         Sleep(1);
        return -1;
    }

    // Uncompress the data
    strm.avail_in = iSourceLen;
    strm.next_in = pSource;

    do {
            strm.avail_out = *ulDestLen;
            strm.next_out = pPositionDestBuffer;
            ret = inflate(&strm, Z_NO_FLUSH);
            tau_printf(" ret: %d \n\r",ret);
             Sleep(1);
            assert(ret != Z_STREAM_ERROR);  /* state not clobbered */
            switch (ret)
            {
                case Z_NEED_DICT:
                    ret = Z_DATA_ERROR;     /* and fall through */
                case Z_DATA_ERROR:
                case Z_MEM_ERROR:
                    (void)inflateEnd(&strm);
                return -2;
            }
            uiUncompressedBytes = *ulDestLen - strm.avail_out;
            *ulDestLen -= uiUncompressedBytes; // ulDestSize holds number of free/empty bytes in buffer
            pPositionDestBuffer += uiUncompressedBytes;
    } while (strm.avail_out == 0);

    // Close the decompression stream
    inflateEnd(&strm);
    assert(ret == Z_STREAM_END);

    return 0;
} 
Waiting for your response. 
Best Regards,
Minhaj Akhter

**Comment by minhajakhterkhan199** [comment]
Dear,
Please respond on this issue.

Best Regards,
Minhaj Akhter

**Comment by madler** [comment]
What is meant by "issue" on github is an issue with the code that is hosted on github. It does not mean issues with your code, nor is it a place to get help debugging your code. If you have found a bug in zlib, then you can provide a minimal, complete, and verifiable example of the bug as an issue.

**Comment by minhajakhterkhan199** [comment]
Dear, 
I requested because I was using example from your website and it seems to me that with large stream zlib is throwing error. Its better if you help us to solve the issue. 

Best Regards,
Minhaj Akhter
