### ISSUE TITLE
deflateParams not working correctly in zlib 1.2.11

### ISSUE THREAD

**Issue by stanguturi** [madler/zlib#222]
I have been using zlib 1.2.8 and didn't find any issues. Only after updating my code to build with zlib 1.2.11, I have encountered the issue. deflateParams() when called to change the compression level, changes the avail_out which causes the next deflate() to call to fail.

Use case: In our code, we first try to compress a block of data using Z_BEST_COMPRESSION level. If the block of data can not be compressed in the given amount of 'output buffer', we try to call deflate() with 'Z_NO_COMPRESSION' with more output buffer. The second deflate call fails even when we have the necessary amount of 'output buffer'

Following is the list of sequence of APIs called:

1. deflateInit2(&zStream, Z_BEST_COMPRESSION, ....)

   (avail_in = 32768, avail_out = 32778)
2. deflateParams(&_zStream, Z_BEST_COMPRESSION, Z_DEFAULT_STRATEGY)

3. deflate(&_zStream, Z_FINISH)
   deflate returned Z_OK. This means, that more space is required.

4. deflateReset(&_zStream)

   (avail_in = 32768, avail_out = 32779)
   (Using Z_NO_COMPRESSION, avail_out should be sufficient)
5. deflateParams(&_zStream, Z_NO_COMPRESSION, Z_DEFAULT_STRATEGY)
   The above call is made to change the compression level.

   After 5, avail_out is changed to 1. This doesn't happen with zlib 1.2.8.
6. deflate(&_zStream, Z_FINISH)
   This deflate() returns Z_OK instead of Z_STREAM_END

For Zlib 1.2.8, 6th step returns Z_STREAM_END. But in Zlib 1.2.11, 6th step returns Z_OK which is
a regression.

On further debugging, I noticed that step 5 changes the avail_out attribute. It should not be changed. Is this a new behavior for zlib 1.2.11? Can someone please check this. Please do let me know if any other information is required from my side. Will be happy to provide.

Thanks
Sankar.

**Comment by praiskup** [comment]
Issue #190?

**Comment by madler** [comment]
`deflateParams()` changes the parameters _after_ the currently available input has been processed. So it is doing what it needs to do, which is compress the available input so that it can effect the change. It will operate as `deflate()` does, and change `avail_in` and `avail_out`.

From the zlib 1.2.8 documentation:

> If the compression level is changed, the input available so far is compressed with the old level (and may be flushed); the new level will take effect only at the next call of deflate().

If you want to effect the change immediately, you should not make any input available.
