### ISSUE TITLE
Crash in inflate()

### ISSUE THREAD

**Issue by Snuff-Daddy** [madler/zlib#223]
There is a crash in inflate() but only when ASMV and ASMINF are defined.  Zlib 1.2.11.  Visual Studio 2015 on Windows 7.  Using zlibstat.

```
L_do_loop:
; 437 "inffast.S"
	cmp  bl,15
	ja   L_get_length_code

	xor  eax,eax
	lodsw
	mov  cl,bl
	add  bl,16
	shl  eax,cl
	or  ebp,eax

L_get_length_code:
	mov  edx, [esp+0]
	mov  ecx, [esp+8]
	and  edx,ebp
	mov  eax, [ecx+edx*4]         <<<<< CRASH HERE ecx=0xCDCDCDCD (heap allocated but uninitialized)

L_dolen:
	mov  cl,ah
	sub  bl,ah
	shr  ebp,cl

```

**Comment by madler** [comment]
The assembler code, and everything else in contrib, are third-party contributions that are not part of zlib and are not supported.

**Comment by tbeu** [comment]
@madler Does this mean that all third-party contributions of the zlib repo will remain unmaintained forever as long as it is not patched by the original developer?

**Comment by wangdxnum1** [comment]
i have the same problem
