### ISSUE TITLE
zlib appears to have a heap issue

### ISSUE THREAD

**Issue by tztester** [madler/zlib#227]
Tried out the zlib distribution for Win64. Build the different versions of the libraries successfully on Win7 on VS2010.  Did some quick stress testing with the included app [testzlib] and ran it with Microsoft's AppVerifier (appverif.exe) and pointed AppVerifier to the testzlib binary.  With just the basic stress test, the testzlib fails in the deflate routine for certain files larger than a few hundred megabytes.   Looked at the stack and the bug appears to end up in the gvmat64.asm / longest_match() routine.  Running some tests, empirically it appeared to only happened with me for Release builds (Debug builds didn't fail).  So to get additional information, I modified the Release build to provided debug info so I could drill down to the problem.   Below are some background screenshots.   Any suggestions you may have to resolve this issue (whether it be a compiler setting, configuration issue, or a bug fix) will be greatly appreciated.

![2017-02-18_12-00-02](https://cloud.githubusercontent.com/assets/25867882/23095091/314619fa-f5d2-11e6-94a3-8950be280406.png)
![2017-02-18_11-54-23](https://cloud.githubusercontent.com/assets/25867882/23095094/3dddbc4a-f5d2-11e6-8600-81e2b0188e1f.png)
![2017-02-18_11-57-41](https://cloud.githubusercontent.com/assets/25867882/23095096/47c94e5e-f5d2-11e6-86d1-98235389d58f.png)
![2017-02-18_11-58-04](https://cloud.githubusercontent.com/assets/25867882/23095098/50df97aa-f5d2-11e6-80fe-63a7e2eec27e.png)

**Comment by madler** [comment]
The assembler code being used is in the contrib directory of zlib, which are third-party contributions, and is not supported. Also that code is known to be buggy and will likely be deleted in a forthcoming distribution. You should recompile without the assembler code.

**Comment by tztester** [comment]
Yep that did the trick.  Thx for the quick reply

Best regards,
Dave Tomczak
TZWorks, LLC
(office) +1-703-939-0411
(fax) +1-703-860-0581

Confidentiality Notice: The information transmitted is intended only for
the person or entity to which it is addressed and may contain proprietary,
business-confidential and/or privileged material. If you are not the
intended recipient of this message you are hereby notified that any use,
review, retransmission, dissemination, distribution, reproduction or any
action taken in reliance upon this message is prohibited. If you received
this in error, please contact the sender and delete the material from any
computer.
