### ISSUE TITLE
gzip specifications regarding OS code

### ISSUE THREAD

**Issue by hadrien-psydk** [madler/zlib#235]
Since zlib 1.2.11 the OS_CODE for Windows stored in the gzip header has a value of 10, as specified by PkZip APPNOTE.TXT file.

The value for Windows used to be 11, as specified by RFC 1952. This is a bit confusing. For example, when I compress a gzip archive with zlib 1.2.11 and open it with an archiver tool (like 7-zip), I get "TOPS-20" as the OS.

Is there any plan to update the RFC (or release a new official document) in order to update the operating system code mapping? That way any program that would implement gzip would use the new values instead of the old ones.

**Comment by madler** [comment]
I have no plan to submit a new RFC. (You can't really update an RFC. As I understand it, you can only put out a new one with a new number that states that it supersedes the old one.)

This is not a real issue as the OS code doesn't affect anything except for the programs listing the contents.

**Comment by alessandrodn** [comment]
Even though I may agree that the OS byte doesn't affect the program functionality, I wonder why zlib should comply with PKware definition and not respect the RFC 1952 standard?

**Comment by rzikm** [comment]
I was little confused when I discovered the discrepancy between implementation and the RFC. Is there something preventing zlib from changing the implementation to actually reflect the value from the RFC?
