### ISSUE TITLE
Redundant test in inflate_fast().

### ISSUE THREAD

**Issue by sh1boot** [madler/zlib#236]
In `inflate_fast()` the [`wnext == 0`](https://github.com/madler/zlib/blob/master/inffast.c#L200) case and the [`wnext >= op`](https://github.com/madler/zlib/blob/master/inffast.c#L229) are nearly identical, and they can be merged by setting

    wnext = (wnext == 0 && whave >= wsize) ? wsize : wnext;

at the beginning of the function.  This eliminates one test from the main loop (and the misleading comment along with it; if libpng operates row-at-a-time `wnext` will almost never be zero).

**Comment by madler** [comment]
`wnext == 0` is the most common case for the fast use of inflate with large output buffers. The code was written for speed in that case, and will be left as is.
