### ISSUE TITLE
deflateBound returns uLong but avail_out is uInt

### ISSUE THREAD

**Issue by DbxDev** [madler/zlib#244]
In case of a one shot compression the result of deflateBound is a uLong, but the value of avail_out
is a uInt, which makes the type returned by deflateBound at least inconsistent, and unsafe in extreme cases (risk of integer overflow).

**Comment by madler** [comment]
As a result, it is up to the application to call deflate multiple times to provide the requisite output space. This is inherent in the zlib interface, which will remain the same for compatibility.
