### ISSUE TITLE
Use-of-uninitialized-value in inflate()

### ISSUE THREAD

**Issue by npm1** [madler/zlib#245]
There are a couple of places in inflate() where UPDATE is called with state->check as its first parameter, without a guarantee that this value has been initialized (state comes from a ZALLOC in inflateInit). This causes use of uninitialized check value.

Suggested fix:
Add state->check=0; around here:
https://github.com/madler/zlib/blob/master/inflate.c#L230

**Comment by madler** [comment]
No, it's guaranteed if UPDATE is called. You'd need to follow the logic.

**Comment by npm1** [comment]
"Following the logic" in this method is hard, it's huge. I have a testcase for this, but I don't think I'm allowed to share it. It was obtained using Chromium fuzzers.  I'll share the state->mode sequence:

First inflate: HEAD -> BAD.
inflateSync: TYPE (the method returns Z_OK)
Second inflate: TYPEDO -> LEN_ -> LIT -> LEN->LIT->LEN->LIT->LEN->LEN->TYPE->CHECK and it uses the uninitialized value state->check there.

**Comment by madler** [comment]
You were correct -- it was possible for `inflateSync()` to leave inflate in an inconsistent state if header decoding was requested, but no header was ever processed. This commit fixes that:
 https://github.com/madler/zlib/commit/44e8ac810d7d50381429a15cdc6e48816beafd2b

**Comment by npm1** [comment]
Sorry for the late reply, I checked if the problem was solved with your patch but it was not. Now I got permission to share the testcase with you. It is for libtiff but the uninitialized values are in zlib. Please let me know how I could share it with you.

**Comment by npm1** [comment]
Ping. The commit mentioned does not fix the issue for our testcase. Is there any plan to fix this upstream or should Chromium patch its own version of zlib?

**Comment by madler** [comment]
You can send me an email. You can find my address on http://zlib.net/ .

**Comment by npm1** [comment]
It bounced :( "One of your attachments contained a virus. Your message was not sent."
I guess it thinks the libtiff testcase is somehow dangerous.

**Comment by madler** [comment]
Send me an email without an attachment, and I'll reply with a different email address for you to try.

**Comment by npm1** [comment]
I will be patching Chromium's copy of zlib because this is marked as a security bug and it has been open for too long.
