### ISSUE TITLE
Incorrect multi-line macro usage in the if-else clause

### ISSUE THREAD

**Issue by yurymik** [madler/zlib#247]
Macro `CLEAR_HASH` is [defined](https://github.com/madler/zlib/blob/master/deflate.c#L192) as follows:

```
#define CLEAR_HASH(s) \
    s->head[s->hash_size-1] = NIL; \
    zmemzero((Bytef *)s->head, (unsigned)(s->hash_size-1)*sizeof(*s->head));
```

and then [used](https://github.com/madler/zlib/blob/master/deflate.c#L603) in `deflateParams`:

```
          if (s->matches == 1)
                slide_hash(s);
          else
                CLEAR_HASH(s);
          s->matches = 0;
```

Call to `zmemzero` will be executed regardless of the `s->matches` value.

**Comment by yurymik** [comment]
Introduced by commit [9dc5a85](https://github.com/madler/zlib/commit/9dc5a8585f429109ef1948ab71b6b71bfa7181e2) "Speed up deflation for level 0 (storing)" from Nov 5, 2016.

**Comment by madler** [comment]
Fixed here https://github.com/madler/zlib/commit/38e8ce32afbaa82f67d992b9f3056f281fe69259
