### ISSUE TITLE
Zlib: deflateEnd() fails after deflateInit2()/deflateReset() when initialized for "Raw Deflate Compression"

### ISSUE THREAD

**Issue by 1234sv** [madler/zlib#250]
Description of the problem is:
 
deflateInit () for *raw deflate* moves internal state to BUSY_STATE (where as it is INIT_STATE for zlib). BUSY_STATE is considered to be == INIT_STATE for *raw deflate*.
So, when deflateEnd() is called, it has no way to identify whether stream is in the start or middle of core deflate operation()  thus reports an Z_DATA_ERROR.

How does it affect:
 
//This will work:
deflateInit2()
deflate(strmp,Z_FINISH);
deflateEnd()
 
//This will not work
deflateInit2()
while(cnt—)
{
 deflate(strmp,Z_FINISH);
  deflateReset()<--required to re-initiate deflate() on next input.
}
deflateEnd();

test_def_init_term.c - a simple test case to reproduce issue.

**Comment by 1234sv** [comment]
So, following solution been identified for it:
1. Use Z_FULL_FLUSH
Use Z_FULL_FLUSH instead of Z_FINISH whenever user indicate end of data. it allows deflateEnd() to terminate without error. However,  Z_FULL_FLUSH does not insert 'End of stream marker(per deflate standard rfc1950.txt)'. it is not a problem as long as application tracks the end of data and not rely on de-compressor to identify it. but if app rely on de-compressor to track the end of data then decompressor may never end.


2. Ignore Error
Since zlib deflateEnd() just check for state at end, we may ignore the error OR add a work-around to issue dummy deflate(strmp,Z_FINISH) to allow error-free call. This approach has been seen in use by linux kernel Crypto-comp interface based on "zlib" and "deflate" driver/algorithm.
Both driver in linux-kernel ignores the return code of zlib_deflateEnd().

\

**Comment by 1234sv** [comment]
Ping. any update on this,

**Comment by timofonic** [comment]
@1234sv Ask in the following project, it's a more active fork of zlib.

https://github.com/Dead2/zlib-ng

**Comment by 1234sv** [comment]
Seems you already created an issue for same in said repository. Do I need to do anything again there. ?

**Comment by timofonic** [comment]
@1234sv I created a big issue listing lots of issues here, I'm not sure if @Dead2 is going to read it.
I also sent an email to zlib developer, but BarracudaCentral antispam fltered it. I sent it again to zlib-devel

I recommend you to register to their mailing list and ask what's the current status of zlib project. zlib project may be small, but essential and widely used. It has many bugs and security issues that need to be resolved.

http://zlib.net/mailman/listinfo/zlib-devel_madler.net

Please spread this as much as possible and make people interested in zlib project to improve to send messages to the mailing list.

Kind regards.

**Comment by mtl1979** [comment]
The second example should not use Z_FINISH.

**Comment by 1234sv** [comment]
2nd example is valid use-scenario for stateless compression/decompression. say, i have 10 inputs which i want to compress independently. Then, there are two ways:
1. Either I call this whole sequence deflateInit() --> deflate() --> deflateEnd() for each input. (which is ideal sequence every one follow), OR
2. deflateInit() 
while( until all 10 processed) {
deflate()
deflateReset()
}
deflateEnd();

2nd loop works well for zlib, as states are managed correctly but for raw deflate

**Comment by mtl1979** [comment]
@1234sv The problem in second example and point 2 in above post is that Z_FINISH is supposed to be used right before deflateEnd(), it won't work anywhere else.

**Comment by madler** [comment]
Fixed.

**Comment by 1234sv** [comment]
hey Mark, you marked it as "fixed". Does it mean you acknowledge this as an issue and have corrected logic to take care of such calls?

**Comment by madler** [comment]
Yes.

**Comment by 1234sv** [comment]
Ok. Can I know which zlib release version we will get this fix?

**Comment by madler** [comment]
The next one.

**Comment by 1234sv** [comment]
Ok. Thanks very much for acknowledging this.

**Comment by RReverser** [comment]
@madler Judging by commit history, looks like there haven't been any releases since January 2017 (~2.5 years ago), so this fix haven't been included anywhere yet?

**Comment by madler** [comment]
The commit is on the develop branch.

**Comment by tbeu** [comment]
... and marked c376a417a724c21173f40765bd643388523b16f7.

**Comment by RReverser** [comment]
Yeah, what I meant was official release available in distros.

**Comment by madler** [comment]
Well, you did say "anywhere".

No, it is not in a new release yet. The official releases are on the master branch.
