### ISSUE TITLE
Valgrind finds issues when inflateSync is used

### ISSUE THREAD

**Issue by pmqs** [madler/zlib#252]
Modified version of examples/zpipe.c, called **malloc.c** [here ](https://gist.github.com/pmqs/add7f08d50747956b6e336f258b7ad48), does the following

1. creates a deflate stream with a full flush point
2. uses **inflateSync** to skip to the flush point
3. then inflates the rest of the stream

I ran as follows with zlib 1.2.11 on a 64-bit Linux  to get valgrind to test the call to **inflate**

    cat malloc.c  | ./malloc | valgrind --show-reachable=yes --track-origins=yes ./malloc -d >/dev/null

Valgrind finds a few issues with **inflate** after the call to **inflateSync** - see end of message. The uninitialized values referenced in all the valgrind errors are testing **inflate_state.flags** or **inflate_state.check** .

Initializing **inflate_state.flags** and **inflate_state.check** to zero in **__inflateInit2** makes all of the errors go away.

As you would expect I can also make all the valgrind errors go away by setting **z_stream.zalloc** to use **calloc** in my test code.

Interesting to note that **zcalloc** (in zutil.c), which is in the backtrace for the source of all the valgrind errors, will _conditionally_ use **calloc** itself, but only if an **unsigned int** is greater than 16 bits. The naming of that function suggests it should be doing a the equivalent of a **calloc** all the time. That doesn't seem to be the case for my test.

    voidpf ZLIB_INTERNAL zcalloc (opaque, items, size)
        voidpf opaque;
        unsigned items;
        unsigned size;
    {
        (void)opaque;
        return sizeof(uInt) > 2 ? (voidpf)malloc(items * size) :
                                  (voidpf)calloc(items, size);
    }

Would it be safer to just use **calloc** all the time?

Here are the valgrind errors

    ==20121== Memcheck, a memory error detector
    ==20121== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
    ==20121== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
    ==20121== Command: ./malloc -d
    ==20121== 
    ==20121== Conditional jump or move depends on uninitialised value(s)
    ==20121==    at 0x409437: inflate (inflate.c:1268)
    ==20121==    by 0x400D7A: inf (malloc.c:206)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121==  Uninitialised value was created by a heap allocation
    ==20121==    at 0x4C2DB8F: malloc (vg_replace_malloc.c:299)
    ==20121==    by 0x40E243: zcalloc (zutil.c:311)
    ==20121==    by 0x406D12: inflateInit2_ (inflate.c:223)
    ==20121==    by 0x406DC4: inflateInit_ (inflate.c:244)
    ==20121==    by 0x400C57: inf (malloc.c:151)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121== 
    ==20121== Conditional jump or move depends on uninitialised value(s)
    ==20121==    at 0x4090CC: inflate (inflate.c:1205)
    ==20121==    by 0x400D7A: inf (malloc.c:206)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121==  Uninitialised value was created by a heap allocation
    ==20121==    at 0x4C2DB8F: malloc (vg_replace_malloc.c:299)
    ==20121==    by 0x40E243: zcalloc (zutil.c:311)
    ==20121==    by 0x406D12: inflateInit2_ (inflate.c:223)
    ==20121==    by 0x406DC4: inflateInit_ (inflate.c:244)
    ==20121==    by 0x400C57: inf (malloc.c:151)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121== 
    ==20121== Conditional jump or move depends on uninitialised value(s)
    ==20121==    at 0x409159: inflate (inflate.c:1209)
    ==20121==    by 0x400D7A: inf (malloc.c:206)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121==  Uninitialised value was created by a heap allocation
    ==20121==    at 0x4C2DB8F: malloc (vg_replace_malloc.c:299)
    ==20121==    by 0x40E243: zcalloc (zutil.c:311)
    ==20121==    by 0x406D12: inflateInit2_ (inflate.c:223)
    ==20121==    by 0x406DC4: inflateInit_ (inflate.c:244)
    ==20121==    by 0x400C57: inf (malloc.c:151)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121== 
    ==20121== Conditional jump or move depends on uninitialised value(s)
    ==20121==    at 0x4091A5: inflate (inflate.c:1207)
    ==20121==    by 0x400D7A: inf (malloc.c:206)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121==  Uninitialised value was created by a heap allocation
    ==20121==    at 0x4C2DB8F: malloc (vg_replace_malloc.c:299)
    ==20121==    by 0x40E243: zcalloc (zutil.c:311)
    ==20121==    by 0x406D12: inflateInit2_ (inflate.c:223)
    ==20121==    by 0x406DC4: inflateInit_ (inflate.c:244)
    ==20121==    by 0x400C57: inf (malloc.c:151)
    ==20121==    by 0x40105D: main (malloc.c:275)
    ==20121== 
    zpipe: invalid or incomplete deflate data
    ==20121== 
    ==20121== HEAP SUMMARY:
    ==20121==     in use at exit: 0 bytes in 0 blocks
    ==20121==   total heap usage: 4 allocs, 4 frees, 48,120 bytes allocated
    ==20121== 
    ==20121== All heap blocks were freed -- no leaks are possible
    ==20121== 
    ==20121== For counts of detected and suppressed errors, rerun with: -v
    ==20121== ERROR SUMMARY: 10 errors from 4 contexts (suppressed: 0 from 0)

**Comment by madler** [comment]
Thank you for the report. This is fixed with this commit: https://github.com/madler/zlib/commit/44e8ac810d7d50381429a15cdc6e48816beafd2b .

And no, it would not be safer to just use calloc all the time. If calloc had been used, this bug would have never been found! Why would you think that zero just happens to be the correct value for the uninitialized variable to be set to?

**Comment by pmqs** [comment]
> Why would you think that zero just happens to be the correct value for the uninitialized variable to be set to?

Based on the incorrect assumption that zcalloc was intended to mirror calloc. :-)
