### ISSUE TITLE
Android NDK r15 and minizip

### ISSUE THREAD

**Issue by alexcohn** [madler/zlib#254]
With the new Android NDK (r15) and unified headers, minizip fails to compile for APP_API < 21. The fix seems to be simple and should not cause big problems: there is little chance that these old device will ever be challenged to open files larger than 4GB.

https://github.com/android-ndk/ndk/issues/364#issuecomment-296699881

> our fix was to modify [one line](https://github.com/madler/zlib/blob/master/contrib/minizip/ioapi.h#L24):
> 
>     -#if (!defined(_WIN32)) && (!defined(WIN32)) && (!defined(__APPLE__))
>     +#if (!defined(_WIN32)) && (!defined(WIN32)) && (!defined(__APPLE__)) && (!defined(ANDROID))
>
> (actually, we had `-DIOAPI_NO_64` even before).

**Comment by enh** [comment]
no, zlib shouldn't make any changes here... the actual r15 release already has this header bug fixed.

**Comment by alexcohn** [comment]
@enh I am not sure I want `__USE_FILE_OFFSET64` unconditionally defined on Android, even if the future fix in unified headers will silently ignore this for API<21.

**Comment by madler** [comment]
Issues in contrib should be reported to the respective author.
