### ISSUE TITLE
inconsistencies in ZLIB-1.2.11 builds using mingw-w64 and MSVC on Windows

### ISSUE THREAD

**Issue by sav-ix** [madler/zlib#258]
Hello, everyone,

Got few issues with ZLIB builds on Windows.

1. For builds using mingw-w64 with asm code usage got error:
```
sh-4.4$ make -f win32/Makefile.gcc LOC=-DASMV OBJA=match.o
[snip]
deflate.c:91:11: note: #pragma message: Assembler code may have bugs -- use at your own risk
 #  pragma message("Assembler code may have bugs -- use at your own risk")
           ^~~~~~~
[snip]
make: *** No rule to make target 'match.o', needed by 'libz.a'.  Stop.
```

And testsuite run finishes with errors:
```
sh-4.4$ make test testdll -f win32/Makefile.gcc
[snip]
ar rcs libz.a adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o
gcc  -o example.exe example.o libz.a
libz.a(deflate.o):deflate.c:(.text+0x745): undefined reference to `longest_match'
libz.a(deflate.o):deflate.c:(.text+0x1444): undefined reference to `longest_match'
libz.a(deflate.o):deflate.c:(.text+0x1ce1): undefined reference to `match_init'
libz.a(deflate.o):deflate.c:(.text+0x3fee): undefined reference to `match_init'
libz.a(deflate.o):deflate.c:(.text+0x43da): undefined reference to `match_init'
collect2.exe: error: ld returned 1 exit status
make: *** [win32/Makefile.gcc:101: example.exe] Error 1
```

Not reproduced for mingw-w64 builds without `LOC=-DASMV OBJA=match.o` keys and for MSVC builds with `LOC="-DASMV -DASMINF -I."...` keys.

2. Missing `install` and `uninstall` rules in file `win32/Makefile.msc`, which available in `win32/Makefile.gcc`.

3. Usage instructions in files `win32/Makefile.gcc` and `win32/Makefile.msc` are significantly different, though relate to the same platform.

Environment:
- Windows 10 x64,
- VS 2015 Update 3,
- Windows SDK 10.0.14393.33,
- mingw-w64 6.3.0,
- MSYS2 20161025,
- ZLIB-1.2.11.

Alexander

**Comment by rhuijben** [comment]
See also issue #41. I would recommend just disabling the unsupported assembly code and using the well tested C code.

**Comment by sav-ix** [comment]
That's understandable. But asm code usage for builds using mingw-w64 described in appropriate [`Makefile`](https://github.com/madler/zlib/blob/master/win32/Makefile.gcc). It meant that it should be built without errors.

**Comment by madler** [comment]
The assembler code will be removed.

**Comment by sav-ix** [comment]
I see, thank you.
What about issues (2) and (3)? Should the y reported as separate tickets, or they're none significant and won't be fixed?

**Comment by madler** [comment]
Please resubmit the other issues. Thanks.

**Comment by sav-ix** [comment]
Done, see: https://github.com/madler/zlib/issues/306 and https://github.com/madler/zlib/issues/307 .
