### ISSUE TITLE
Can't build shared library of current develop

### ISSUE THREAD

**Issue by rathsky** [madler/zlib#27]
./configure will print "ztest27459.c:1:2: error: #error error" and continue to only build the static library.

Removing that check in the script will have the compilation abort with

/usr/bin/ld: unable to find version dependency `ZLIB_1.2.7'

Building 1.2.7 finishes fine.

Arch Linux x64, gcc 4.7.2, glibc 2.16.0, binutils 2.23.1

**Comment by madler** [comment]
No response, so closing.
