### ISSUE TITLE
deflate.c (603) 'else' block seems to be missing braces

### ISSUE THREAD

**Issue by hadrien-psydk** [madler/zlib#272]
Hi,

[In deflate.c, line 603](../blob/master/deflate.c#L603), there is a call to the CLEAR_HASH macro in a 'else' block that does not have braces.

The definition of [CLEAR_HASH](../blob/master/deflate.c#L192) is made of two statements, so the second statement is executed outside the 'else'. Is that intended or am I missing something?

**Comment by madler** [comment]
Yep. Take a look at the commits on the develop branch.
