### ISSUE TITLE
Bug in inflate.c

### ISSUE THREAD

**Issue by umokk** [madler/zlib#274]
Zlib 1.2.11 supposedly has a bug in inflate.c.
How to reproduce:
1. Build zlib with asm enabled for x86 (Visual Studio 2017).
2. Build test\example.c.
3. Run.
You'll get access violation in contrib\masmx86\inffas32.asm, line 669: mov  eax, [ebx+eax*4]

x64 works fine.
1.2.8 worked fine for both x86 and x64.

**Comment by rhuijben** [comment]
See also issue #41. I would recommend never enabling the ASM optimizations until this issue is fixed.

**Comment by umokk** [comment]
And what about inffasx64.asm and gvmat64.asm (x64 asm files)? Are they ok or they're buggy too?

**Comment by madler** [comment]
The assembler code is in contrib and not part of the supported zlib. Since that code seems to be causing problems, it will be removed from the distribution.
