### ISSUE TITLE
deflate.c/deflateReset/deflateResetKeep does not reset deflate_state.high_water

### ISSUE THREAD

**Issue by xuemingshen** [madler/zlib#275]
The internal status deflate_state.high_water is not reset in deflateReset/deflateResetKeep/lm_init().
It triggers a regression from 1.2.8 to 1.2.11 [1] when the "strategy/levle is changed" and the "reset" is called, due to the condition check changed from "strm->total_in!=0" to "s->high_water" (for the flush last buffer" branch) in deflate.c/deflateParams().

from

    if ((strategy != s->strategy || func != configuration_table[level].func) &&
        strm->total_in != 0) {
        /* Flush the last buffer: */
        err = deflate(strm, Z_BLOCK);
        if (err == Z_BUF_ERROR && s->pending == 0)
            err = Z_OK;
    }

to

    if ((strategy != s->strategy || func != configuration_table[level].func) &&
        s->high_water) {
        /* Flush the last buffer: */
        int err = deflate(strm, Z_BLOCK);
        if (err == Z_STREAM_ERROR)
            return err;
        if (strm->avail_out == 0)
            return Z_BUF_ERROR;
    }

It seems reasonable to reset the "high_water" inside either deflateResetKeep() or lm_init().

[1] https://bugs.openjdk.java.net/browse/JDK-8184306

**Comment by madler** [comment]
This was fixed in https://github.com/madler/zlib/commit/f9694097dd69354b03cb8af959094c7f260db0a1 .
Can you verify?
