### ISSUE TITLE
Minimum size of inflate output buffer?

### ISSUE THREAD

**Issue by vinniefalco** [madler/zlib#280]
Lets say I am inflating a stream, and on the last call I provide the remainder of the stream contents minus the 4-byte "empty" deflate block (`0x00, 0x00, 0xff, 0xff `), and specify **Z_FLUSH**. There is plenty of output space.

So now I have no more input remaining except the empty deflate block, my question is what is the minimum size of the output area necessary to collect all the output that could be produced by feeding the empty deflate block in, on a call to `inflate`?

Thanks

**Comment by madler** [comment]
If I understand your question correctly, you are asking about the output space needed to hold the decompressed result of an empty deflate block. The answer is zero.

**Comment by vinniefalco** [comment]
Yes I think that's what I'm asking. I though there could be some yet-unwritten data in the inflate state, which causes the described latency, and that data is flushed when the inflator sees the empty deflate block? Or am I thinking about the compressor?

**Comment by madler** [comment]
If all that's left is the `00 00 ff ff`, then there is no pending uncompressed data, given the preceding "plenty of output space".
