### ISSUE TITLE
Function arguments names inconsistencies

### ISSUE THREAD

**Issue by irwir** [madler/zlib#287]
A minor thing, but having the same names would be preferable.

From _cppcheck_ output:
crc32.c, line 203
Function 'crc32_z' argument 1 names different: declaration 'adler' definition 'crc'.
gzwrite.c, line 354
Function 'gzputs' argument 2 names different: declaration 's' definition 'str'.
trees.c, lines 1159, 1160
Function 'bi_reverse' argument 1 names different: declaration 'value' definition 'code'.
Function 'bi_reverse' argument 2 names different: declaration 'length' definition 'len'.

**Comment by madler** [comment]
Addressed.
