### ISSUE TITLE
Bug in deflateParams()

### ISSUE THREAD

**Issue by chund** [madler/zlib#288]
This statement seems to be not correct. Not sure if it causes issues.

600             if (s->matches == 1) 
601                 slide_hash(s); 
602             else 
603                 CLEAR_HASH(s); 

Reason: CLEAR_HASH is a 2 line macro. Only the 1st line of the macro "s->head[s->hash_size-1] = NIL;" will be part of the else. The 2nd line of the macro "zmemzero((Bytef *)s->head, (unsigned)(s->hash_size-1)*sizeof(*s->head));" will be executed always.

**Comment by madler** [comment]
Already fixed in https://github.com/madler/zlib/commit/38e8ce32afbaa82f67d992b9f3056f281fe69259
