### ISSUE TITLE
Undefined behaviour in trees.c:1203

### ISSUE THREAD

**Issue by fgsch** [madler/zlib#290]
_tr_stored_block() is called twice in deflate.c with the second argument being NULL, first in deflate() and then in deflate_stored().

As per C standard, calling memcpy with a NULL argument is undefined even if the size is 0.

Found by ubsan.

**Comment by fgsch** [comment]
Introduced in 9dc5a85.

**Comment by madler** [comment]
Addressed.

**Comment by fgsch** [comment]
Where, sorry? I can't find any commits.

**Comment by tbeu** [comment]
723e928b84b0adac84cc11ec5c075a45e1a79903 went into develop branch (for now).
