### ISSUE TITLE
zlib asm test freeze on x86 msvc2015

### ISSUE THREAD

**Issue by silverqx** [madler/zlib#293]
Can't compile `zlib asm` version anymore. I did some tests and it started from `v1.2.9` version, reproducible on master branch too.

It happens only for x86 version and only when asm version is compiled. 64bit version works fine and x86 standard version too.

I Compiled as is described in `win32/Makefile.msc`.
`nmake -f win32/Makefile.msc LOC="-DASMV -DASMINF" OBJA="inffas32.obj match686.obj"`

And test runned with:
`nmake -f win32/Makefile.msc LOC="-DASMV -DASMINF" OBJA="inffas32.obj match686.obj" test`

I didn't tried with other msvc versions, only with msvc2015.

`v1.2.8` version works fine.

**Comment by madler** [comment]
The assembler code has been removed.

**Comment by silverqx** [comment]
Ok, thx for clarification
