### ISSUE TITLE
zlib dislike .NET garbage collector 

### ISSUE THREAD

**Issue by dimzon** [madler/zlib#294]
(deflate.c @ 361) checks ```s->strm != strm```
the problem is if ```strm``` is allocated into .NET managed heap. .NET garbage collector can run between zlib invokations. This mean real ```strm``` address can be changed during GC memory-defragmentation phase. So next call to Zlib will produce Z_STREAM_ERROR. This behavior doen't described into ```zlib.h```.
To workaround this check I need to use ```GCHandle.Alloc``` to lock ```strm``` into same memory address during whole compression cycle. This prevents the garbage collector from moving the object and hence undermines the efficiency of the garbage collector.

**Comment by madler** [comment]
Then that check is working! The z_stream structure cannot be moved. It contains pointers to memory that is part of the structure, so if it's moved, then the next use of the stream will fail badly with segfaults and the like.
