### ISSUE TITLE
memcpy-related UB, round two!

### ISSUE THREAD

**Issue by Sebbyastian** [madler/zlib#296]
Care needs to be taken to ensure [`memcpy` isn't used to copy overlapping objects](https://stackoverflow.com/questions/4415910/memcpy-vs-memmove/), as objectively `memcpy` is implemented in one of two ways:

- A loop from lowest to highest address, copying bytes
- A loop from highest to lowest address, copying bytes
- (any other order is possible, but realistically those are the two you're likely to see)

Depending upon implementation, erratic results may occur. See the linked StackOverflow question for more details.

[This](https://github.com/madler/zlib/blob/50893291621658f355bc5b4d450a8d06a563053d/examples/gzappend.c#L140) most certainly needs to be fixed.

[This](https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/gzwrite.c#L444) might also need to be fixed.

I suggest auditing all uses of `memcpy` for issues like this and #290 since it appears to be a hotspot...

**Comment by madler** [comment]
Addressed.
