### ISSUE TITLE
OS flag change in 1.2.11

### ISSUE THREAD

**Issue by perrygeo** [madler/zlib#320]
@madler: Question regarding the OS flag changeset here: https://github.com/madler/zlib/commit/ce12c5cd00628bf8f680c98123a369974d32df15

We have some python unit tests which asserted that the bytes returned were exactly equal to a test fixture. This approach has worked (by accident) for a while since we only tested on OSX and Linux. When I upgraded to OSX High Sierra, the tests started failing.

Here's what I've found out so far: OSX 10.13 (High Sierra) shipped with zlib 1.2.11 including the OS flag change. It works fine - doesn't impact our ability to decompress or round-trip data in any way. Just the 10th bit of the output differs from the old test fixtures, with the OS type changing from unix to apple. 

Fully expecting that the solution is "don't directly compare output by byte because they're OS specific" :-) And we're changing our tests accordingly. But with Linux+OSX being a hugely popular production+dev environment combo, I'm sure others will have made the assumption that byte output is equal on all linux/unix platforms and be a bit confused about their new results.

The spec doesn't list `19 - Apple` so it was difficult to track down why the 10th byte had suddenly flipped to `0x13`. Is there any that can be to make this more clear to OSX users? Would it be appropriate to update the [gzip spec](http://www.zlib.org/rfc-gzip.html) with the new OS list and a brief note?

**Comment by Neustradamus** [comment]
@madler: Can you look this issue?

**Comment by madler** [comment]
The OS codes come from the PKWare appnote:

```
        4.4.2.2 The current mappings are:

         0 - MS-DOS and OS/2 (FAT / VFAT / FAT32 file systems)
         1 - Amiga                     2 - OpenVMS
         3 - UNIX                      4 - VM/CMS
         5 - Atari ST                  6 - OS/2 H.P.F.S.
         7 - Macintosh                 8 - Z-System
         9 - CP/M                     10 - Windows NTFS
        11 - MVS (OS/390 - Z/OS)      12 - VSE
        13 - Acorn Risc               14 - VFAT
        15 - alternate MVS            16 - BeOS
        17 - Tandem                   18 - OS/400
        19 - OS X (Darwin)            20 thru 255 - unused
```
