### ISSUE TITLE
OS/390 ERROR CCN3343 ./gzwrite.c:451 Redeclaration of pt_gzprintf differs from previous declaration on line 1468 of “./zlib.h” 

### ISSUE THREAD

**Issue by sunnyap** [madler/zlib#326]
zlib-1.2.11 compilation on z/OS (OS/390)

# Issue 1:
```
cc -w -c -Wc,debug -Wc,dll,xplink -Wl,xplink ztest2794.c
FSUM3007 -w is not a valid option.
(exit code 1)
No shared library support; try without defining CC and CFLAGS
Building static library libptzlib.a version 1.2.11 with cc.
```
### Resolution
Resolved by dropping -w options in configure as its not a valid option in OS/390. Is there any way to retain -w and still compile on OS/390 as the same code is compiled on other Windows/*nix platforms?

# Issue 2:
```
Checking for gcc...
Checking for shared library support...
Building shared library libptzlib.so with cc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using s[n]printf().
Checking for snprintf() in stdio.h... Yes.
Checking for return value of snprintf()... Yes.
gmake[1]: Entering directory `/u/data002/zlib/zlib-1.2.11'
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  adler32.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  crc32.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  deflate.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  infback.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  inffast.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  inflate.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  inftrees.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  trees.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  zutil.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  compress.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  uncompr.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  gzclose.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  gzlib.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  gzread.c
cc -Wc,debug -Wc,dll,xplink -Wl,xplink -Wc,exportall    -c  gzwrite.c
ERROR CCN3343 ./gzwrite.c:451   Redeclaration of pt_gzprintf differs from previous declaration on line 1468 of "./zlib.h".
INFORMATIONAL CCN3378 ./gzwrite.c:451   Prototype for function pt_gzprintf cannot contain "..." when mixed with a nonprototype declaration.
CCN0793(I) Compilation failed for file ./gzwrite.c.  Object file not created.
FSUM3065 The COMPILE step ended with return code 12.
FSUM3017 Could not compile gzwrite.c. Correct the errors and try again.
gmake[1]: *** [gzwrite.o] Error 3
gmake[1]: Leaving directory `/u/data002/zlib/zlib-1.2.11'
gmake: *** [run_make] Error 2

ERROR CCN3343 ./gzwrite.c:451   Redeclaration of ptz_gzprintf differs from previous declaration on line 1468 of "./zlib.h".
@./gzwrite.c:451:   int ZEXPORTVA gzprintf(gzFile file, const char *format, ...)
@./zlib.h:1468:     ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char *format, ...));
@zconf.h.in:        define gzprintf              ptz_gzprintf
```
[CCN3343](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.3.0/com.ibm.zos.v2r3.cbcdg01/msg-CCN3343.htm)
[CCN3378 ](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.cbcdg01/msg-CCN3378.htm)
[configure.log](https://github.com/madler/zlib/files/1562479/configure.log)

### Resolution
How to resolve Issue 2?

**Comment by sunnyap** [comment]
Thanks to my colleague Carla's debugging effort, this issue was resolved in zconf.h.in by moving

```
#ifdef HAVE_STDARG_H    /* may be set to #if 1 by ./configure */
#  define Z_HAVE_STDARG_H
#endif
```
above
```
#ifndef OF /* function prototypes */
#  ifdef STDC
#    define OF(args)  args
#  else
#    define OF(args)  ()
#  endif
#endif

#ifndef Z_ARG /* function prototypes for stdarg */
#  if defined(STDC) || defined(Z_HAVE_STDARG_H)
#    define Z_ARG(args)  args
#  else
#    define Z_ARG(args)  ()
#  endif
#endif
```
The Z_HAVE_STDARG_H was not defined till Z_ARG code was being executed. Hence it was picking the wrong/stdio declaration. Moving Z_HAVE_STDARG_H ahead did the trick in resolving the issue.

Following z/OS cc/xlc compiler option **Wc, PPONLY -E**  was useful in nailing the issue.
Command 1:
`cc -Wc,PPONLY -E -Wc,debug -Wc,dll,xplink -Wl,xplink -D_LARGEFILE64_SOURCE=1 -o gzwrite.C gzwrite.c > gzwrite.out
`
Search "gzprintf" (2 hits in 1 file) gzwrite.out (2 hits)
    Line 1700: extern int  PSFT_gzprintf ();
    Line 2590: int  PSFT_gzprintf(PSFT_gzFile file,  char *format, ...)

Command 2:
Forcefully passing -DZ_HAVE_STDARG_H (although it cause - 
`WARNING CCN3236 ./zconf.h:444   Macro name Z_HAVE_STDARG_H has been redefined.`
`cc -Wc,PPONLY -E -Wc,debug -Wc,dll,xplink -Wl,xplink -D_LARGEFILE64_SOURCE=1 -DZ_HAVE_STDARG_H -o gzwrite.C gzwrite.c > gzwrite.out
`
Search "gzprintf" (2 hits in 1 file) in gzwrite.out (2 hits)
    Line 1700: extern int  PSFT_gzprintf (PSFT_gzFile file, char *format, ...);
    Line 2590: int  PSFT_gzprintf(PSFT_gzFile file,  char *format, ...)

Please review and check if we could push this fix. Thanks.

**Comment by Neustradamus** [comment]
@sunnyap: Z_ARG has been removed:
- https://github.com/madler/zlib/commit/3f635df97edbb85f55f8e991e5f00d94f4132a14

**Comment by madler** [comment]
The `gzprintf()` declarations can no longer differ.

I removed the `-w` option in configure when testing for shared libraries. Seems to work ok without it. https://github.com/madler/zlib/commit/88ec24670e9c484219392def5f2f4b5e3f839db3
