### ISSUE TITLE
potential bug in deflateParams

### ISSUE THREAD

**Issue by angeleno** [madler/zlib#332]
Hi Mark

Perhaps there is a potential bug here:

https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/deflate.c#L602-L603

committed thru:
https://github.com/madler/zlib/commit/9dc5a8585f429109ef1948ab71b6b71bfa7181e2

`CLEAR_HASH` is a multiple statement macro and unless you put curly-braces around it it is wrong.
BTW: it was caught when running clang-tidy.

If you agree, I will do a pull-request.

Best,
Sarang

**Comment by madler** [comment]
Already fixed in the Develop branch.
