### ISSUE TITLE
Uncompress & Unzip aborts

### ISSUE THREAD

**Issue by topwizprogramming** [madler/zlib#340]
I downloaded the most recent version 1.2.11 from www.zlib.net and compiled it with Visual Studio 2012 on Windows 10.
Compress & creating zip files works great. Uncompress and unzip abort. I tested by running minunz against a zip file created by minizip containing one file. I also tested using a zip file created with Windows built in zip file creation and had the same result.
I added calls to OutputDebugStringA and found that it is somewhere in the inflate function.
Here is a text grab from my command window:

>miniunz test.zip
MiniUnz 1.01b, demo of zLib + Unz package written by Gilles Vollant
more info at http://www.winimage.com/zLibDll/unzip.html
test.zip opened
 extracting: zlib.ico
>

The file zlib.ico is created but contains zero bytes.

The pre-compiled zlibwapi.dll is version 1.2.3 from 2005 so I am trying to get the latest version. I have been using zlibwapi.dll from PowerBuilder apps and seem to have a problem with really large data. One of the most recent versions has a fix for large data so I am hoping it will fix the problem in PowerBuilder.

**Comment by madler** [comment]
It is likely that however you are building it is including assembler code. Do not use the assembler code.

**Comment by topwizprogramming** [comment]
That was it. Using the ReleaseWithoutAsm configuration it works without issue. Thanks you for your prompt answer.
