### ISSUE TITLE
Static constants 

### ISSUE THREAD

**Issue by irwir** [madler/zlib#351]
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/compress.c#L31
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/uncompr.c#L35
In these two cases constants should have been `static`.

**Comment by madler** [comment]
What? Why? No memory for `max` will ever exist. It's no different than `#define max ((uInt)-1)`, except for type checking, which is a good thing.

**Comment by irwir** [comment]
Sorry, I was thinking in terms of C++, while in C `static` qualifier does someting very different.
This is a C library, therefore the issue should be closed, and the code left as is.
