### ISSUE TITLE
Calculation of NMAX in Adler32 checksum

### ISSUE THREAD

**Issue by hjred** [madler/zlib#356]
Hi there,

i have a question regarding the value of nmax in the Adler32 checksum. Why is it 5552?
If i use the basic formulas found on wikipedia for example:

     A = 1 + D1 + D2 + ... + Dn (mod 65521)
     B = A1 + A2 + ... + An = (1 + D1) + (1 + D1 + D2) + ... + (1 + D1 + D2 + ... + Dn) (mod 65521)

if i set every value to 255 (for D) and let me calculate max n so B is less than the maximum of uint32 say by wolframalpha
http://www.wolframalpha.com/input/?i=(1%2B1*255)%2B(1%2B2*255)%2B(1%2B3*255)%2B...%2B(1%2Bn*255)%3C%3D4294967295

the solution is (sqrt(8761733347849) - 257) / 510 for nmax, which is 5803 (rounded).

I got the same answer (5803) using a little program with 255 as input all the time and checking for the first overflow.

Thanks in advance

**Comment by madler** [comment]
5803 would only work the first time through. After the last set of modulo operations by 65521, A and B are not 1 and 0. They can each be anything in 0..65520. So you need to consider the case where A = 65520 and B = 65520. The rest is left as an exercise for the reader.

**Comment by hjred** [comment]
Ah, thanks very much :) i didn't thought about that
