### ISSUE TITLE
[question] keeping the z_stream live for whole application lifetime

### ISSUE THREAD

**Issue by CristoferMartins** [madler/zlib#371]
I got a application that runs for 24 hours long. I'm using one z_stream which is initialized at the application startup(call to deflateInit2) and it will call deflateEnd at the application shutdown. After the call to deflate(&stream, Z_FINISH) i'm calling deflateReset. My question is if there will be any problem with this setup like a memory leak or maybe a chance of crash since we gonna be using the same z_stream a lot.

**Comment by madler** [comment]
Nope, no problem. You can call `deflateReset()` as many times as you like, and it will continue to reuse the same memory allocation. So long as you call `deflateEnd()` when you are finally done, there will be no memory leak.
