### ISSUE TITLE
zlib not found by anaconda R

### ISSUE THREAD

**Issue by clouds-drift** [madler/zlib#373]
When install the R package "shortread", zlib was not found.
While "zlib" has been installed by "conda install -c anaconda zlib ".

Error log when install "shortread" by bioconductor:
configure:2700: checking for gzeof in -lz
configure:2735: gcc -o conftest -g -O2   conftest.c -lz   >&5
/export/data2/anaconda2/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.2.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
configure:2742: $? = 1
configure: failed program was:
| /* confdefs.h.  */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| /* end confdefs.h.  */
| 
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char gzeof ();
| int
| main ()
| {
| return gzeof ();
|   ;
|   return 0;
| }
configure:2763: result: no
configure:2773: error: zlib not found

**Comment by madler** [comment]
"zlib not found" means zlib was not found. Install it. (And no, we don't know how to install it on the system you didn't even identify. Google how to install it.)
