### ISSUE TITLE
FEXTRA field registry ?

### ISSUE THREAD

**Issue by bsdphk** [madler/zlib#396]
RFC1952 mentions an email address for registration of FEXTRA field identifiers, but that doesn't seem to work.

Does there exist an actual registry for FEXTRA fields, and if so, how does one go about making a registration ?

**Comment by minchai23** [comment]
Mark Adler answered this question on stach overflow
https://stackoverflow.com/questions/65188890/what-gzip-extra-field-subfields-exist
