### ISSUE TITLE
Condition always false

### ISSUE THREAD

**Issue by irwir** [madler/zlib#397]
https://github.com/madler/zlib/blob/7c0c75e990ca5395139c148f120042048b0ce091/inflate.c#L1436

Please check: the conditional block at the line 1414 ensures that `state->mode` has `SYNC` value, and that will remain unchanged at the line 1436.

**Comment by madler** [comment]
Thank you for the report. Fixed here: https://github.com/madler/zlib/commit/0d36ec47f310478549c0864f215ab5c0114c49ba .
