### ISSUE TITLE
Building static library in VIsual Studio 2017

### ISSUE THREAD

**Issue by irwir** [madler/zlib#404]
**develop** branch.

The solution from `vc14` was successfully upgraded, but static library could not be built for `x86` and `x64` platforms. The diagnostics depended on the selected configuration/platform:

> c1 : fatal error C1083: Cannot open source file: '..\..\masmx64\inffas8664.c': No such file or directory

or

>   crc32.c
> d:\e\tmp\d\tmp\zlib-develop\crc32.c(969): error C2708: 'crc32_combine64': actual parameters length in bytes differs from previous call or reference
>   d:\e\tmp\d\tmp\zlib-develop\crc32.c(952): note: see declaration of 'crc32_combine64'
> d:\e\tmp\d\tmp\zlib-develop\crc32.c(986): error C2708: 'crc32_combine_gen64': actual parameters length in bytes differs from previous call or reference
>   d:\e\tmp\d\tmp\zlib-develop\crc32.c(973): note: see declaration of 'crc32_combine_gen64'
> d:\e\tmp\d\tmp\zlib-develop\crc32.c(990): error C2373: 'crc32_combine_op': redefinition; different type modifiers
>   d:\e\tmp\d\tmp\zlib-develop\zlib.h(1767): note: see declaration of 'crc32_combine_op'

Solutions for eariler versions of  Visual Studio could have similar issues (`vc12` does), and `vc15` and `vc16` solutions might be added to the existing list.

**Comment by kaoh** [comment]
@irwir I have created a [pull request for VS 22](https://github.com/madler/zlib/pull/644). You can give it a try.

**Comment by Neustradamus** [comment]
@irwir: Have you tried?

**Comment by madler** [comment]
See https://github.com/madler/zlib/commit/d0704a820186481da35d08f4b655881e1d32089f
