### ISSUE TITLE
Implicit declaration in gzread.c causing bad ARM64 assembly generation

### ISSUE THREAD

**Issue by kenavolic** [madler/zlib#416]
### Environment

**Zlib version**: 1.2.8
**Compiler**: clang 6.0
**Target platform**: arm64

### Description:

Compilation leads to the following warning _"error: implicit declaration of function 'gets' is invalid in C99"_. This seems armless but clang will make a wrong assumption on _read_ signature for x64 builds:
```
 ssize_t read(int fd, void *buf, size_t count); // correct signature
 ssize_t read(int fd, void *buf, int count); // implicitly deduced by the compiler
```
The consequence is the generation of bad IR and thus flawed assembly by the compiler leading to undefined behavior (e.g bad `count` type -> wrong  assumptions by optimizer when `gz_avail `and `gz_load `are inlined in `gz_look` -> bad memory access). 

### Fixes:

Add explicit declaration by including `unistd.h` for POSIX system in `gzguts.h`

### Related Issues
* #62

**Comment by madler** [comment]
Did you use ./configure? It detects the presence of and includes unistd.h.

**Comment by kenavolic** [comment]
yes! We use:

```
CC="clang" CFLAGS="some flags" LDFLAGS="some flags" LD="clang" ./configure
make
```

**Comment by madler** [comment]
Please do a `make distclean` and your `./configure` command and attach the resulting configure.log file here. Thank you!

**Comment by kenavolic** [comment]
Argh... I am sorry, I think I made you lose time and time is precious... We do call ./configure on our linux configuration but not on our android one. I did it and it fixes the issue. Again, sorry...
