### ISSUE TITLE
Is this switch-case fallthrough intentional?

### ISSUE THREAD

**Issue by TorKlingberg** [madler/zlib#424]
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/infback.c#L480

Is that an intentional fall-through?

**Comment by madler** [comment]
Yes.

**Comment by tbeu** [comment]
Commenting it by `/* fall-through */` would make it more explicit and also silence static code analysis tools.

**Comment by madler** [comment]
If the world could come to some agreement on `/* fall-through */`, `// fall through`, `/* FALLTHRU */`, `__attribute__ ((fallthrough));`, `[[gnu::fallthrough]];`, `[[fallthrough]];`, etc., then maybe I would.

**Comment by tbeu** [comment]
Same verbosity as in your example is good enough: https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/examples/zpipe.c#L129
