### ISSUE TITLE
Building fails in Cygwin.

### ISSUE THREAD

**Issue by GremlinOnTheWingException** [madler/zlib#45]
$ ./configure
Checking for gcc...
Checking for shared library support...
No shared library support.
Building static library libz.a version 1.2.8 with gcc.
Checking for off64_t... No.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
Checking for attribute(visibility) support... No.

$ make -f win32/Makefile.gcc
gcc  -O3 -Wall -c -o adler32.o adler32.c
gcc  -O3 -Wall -c -o compress.o compress.c
gcc  -O3 -Wall -c -o crc32.o crc32.c
gcc  -O3 -Wall -c -o deflate.o deflate.c
gcc  -O3 -Wall -c -o gzclose.o gzclose.c
gcc  -O3 -Wall -c -o gzlib.o gzlib.c
gcc  -O3 -Wall -c -o gzread.o gzread.c
gcc  -O3 -Wall -c -o gzwrite.o gzwrite.c
gcc  -O3 -Wall -c -o infback.o infback.c
gcc  -O3 -Wall -c -o inffast.o inffast.c
gcc  -O3 -Wall -c -o inflate.o inflate.c
gcc  -O3 -Wall -c -o inftrees.o inftrees.c
gcc  -O3 -Wall -c -o trees.o trees.c
gcc  -O3 -Wall -c -o uncompr.o uncompr.c
gcc  -O3 -Wall -c -o zutil.o zutil.c
ar rcs libz.a adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o  gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o
windres --define GCC_WINDRES -o zlibrc.o win32/zlib1.rc
gcc -shared -Wl,--out-implib,libz.dll.a  \
-o zlib1.dll win32/zlib.def adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o  gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o  zlibrc.o
Cannot export gzopen_w: symbol not defined
collect2: ld returned 1 exit status
win32/Makefile.gcc:96: recipe for target `zlib1.dll' failed
make: *** [zlib1.dll] Error 1

 ‘gzopen_w’ in win32/zlib.def is useful for MinGW, but it is wrong for Cygwin.

**Comment by madler** [comment]
Pushed commit to compile `gzopen_w` when `__CYGWIN__` defined.

**Comment by dimpase** [comment]
the commit was b4ce6caf0992296230e4e25b22a63e418bdf4dcf

**Comment by adeseg** [comment]
$ make -f win32/Makefile.gcc
gcc  -O3 -Wall -DNO_VIZ -c -o adler32.o adler32.c
gcc  -O3 -Wall -DNO_VIZ -c -o compress.o compress.c
gcc  -O3 -Wall -DNO_VIZ -c -o crc32.o crc32.c
gcc  -O3 -Wall -DNO_VIZ -c -o deflate.o deflate.c
gcc  -O3 -Wall -DNO_VIZ -c -o gzclose.o gzclose.c
gcc  -O3 -Wall -DNO_VIZ -c -o gzlib.o gzlib.c
gcc  -O3 -Wall -DNO_VIZ -c -o gzread.o gzread.c
gcc  -O3 -Wall -DNO_VIZ -c -o gzwrite.o gzwrite.c
gcc  -O3 -Wall -DNO_VIZ -c -o infback.o infback.c
gcc  -O3 -Wall -DNO_VIZ -c -o inffast.o inffast.c
gcc  -O3 -Wall -DNO_VIZ -c -o inflate.o inflate.c
gcc  -O3 -Wall -DNO_VIZ -c -o inftrees.o inftrees.c
gcc  -O3 -Wall -DNO_VIZ -c -o trees.o trees.c
gcc  -O3 -Wall -DNO_VIZ -c -o uncompr.o uncompr.c
gcc  -O3 -Wall -DNO_VIZ -c -o zutil.o zutil.c
ar rcs libz.a adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o
gcc -shared -Wl,--out-implib,libzdll.a  \
-o zlib1.dll win32/zlib.def adler32.o compress.o crc32.o deflate.o gzclose.o gzlib.o gzread.o gzwrite.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o  zlibrc.o
/usr/lib/gcc/i686-pc-cygwin/7.4.0/../../../../i686-pc-cygwin/bin/ld: win32/zlib.def:4: syntax error
/usr/lib/gcc/i686-pc-cygwin/7.4.0/../../../../i686-pc-cygwin/bin/ld:win32/zlib.def: file format not recognized; treating as linker script
/usr/lib/gcc/i686-pc-cygwin/7.4.0/../../../../i686-pc-cygwin/bin/ld:win32/zlib.def:2: syntax error
collect2: error: ld returned 1 exit status
make: *** [win32/Makefile.gcc:91: zlib1.dll] Error 1
