### ISSUE TITLE
Ambiguous and non-free “Use by owners of Che Guevarra parafernalia is prohibited” licence term 

### ISSUE THREAD

**Issue by hikari-no-yume** [madler/zlib#450]
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/contrib/amd64/amd64-match.S#L1-9

```
/*
 * match.S -- optimized version of longest_match()
 * based on the similar work by Gilles Vollant, and Brian Raiter, written 1998
 *
 * This is free software; you can redistribute it and/or modify it
 * under the terms of the BSD License. Use by owners of Che Guevarra
 * parafernalia is prohibited, where possible, and highly discouraged
 * elsewhere.
 */
```

The licence terms in this file are problematic for several reasons:

1. They are ambiguous: is the file_actually_ covered by BSD, given there is this following prohibition statement? Does it or does it not create an exception to the BSD licence?
2. It is vague (“use” — what kind? “BSD License” — which version?).
3. If it is enforceable then it is a non-free licence term, that is, the file is not free software, and possibly not “open source”, because it cannot be used by anyone for any purpose.
4. It's either a joke or an ideological statement, and both might (in the eye of the beholder of course) reflect poorly on zlib.

Luckily, this file is optional. Unfortunately, it seems like it has made its way into larger software without the distributors or developers seemingly being fully aware of it.

I am aware of course [that](https://github.com/madler/zlib/blob/d6f0da2fa3bad566a43c7778259c55069416bd25/contrib/README.contrib)

> All files under this contrib directory are UNSUPPORTED. There were
provided by users of zlib and were not tested by the authors of zlib.
Use at your own risk. Please contact the authors of the contributions
for help about these, not the zlib authors. Thanks.

But the licence is nonetheless on a file included with zlib.

**Comment by hrieke** [comment]
Not a lawyer here, nor do I want to be one, but I'd say it's 'like the "Do No Evil" license or "Beerware" license, which I suspect lawyers hate for a variety of reasons.

In truth, zlib should have all the contrib code re-licensed under the zlib license (looking at you Delphi directory...).

**Comment by madler** [comment]
In this particular case, the assembler code will be removed from the next version of zlib for other reasons.

In the general case, I'm not going to police the licenses in the contrib directory. If that was deemed to be necessary, then I would likely remove everything from the contrib directory that's not mine, and call it something else.

**Comment by hikari-no-yume** [comment]
Thanks for taking the time to respond!

**Comment by hrieke** [comment]
Indeed, thank you Mark.
