### ISSUE TITLE
does avail_in == 0 guarantee that Z_SYNC_FLUSH block is completed in the output?

### ISSUE THREAD

**Issue by AleXoundOS** [madler/zlib#455]
It seems that despite avail_in is 0 I have to call deflate again in order for the EOB to be produced.

**Comment by madler** [comment]
No. `avail_in` being zero only assures that all of the input has been consumed. The only way to be sure that all of the output has been delivered is for `avail_out` to come back _non_-zero.

**Comment by AleXoundOS** [comment]
Thank you very much.

My fault, the following sentence was misleading for me.
> In particular avail_in is zero after the call if enough output space has been provided before the call.

**Comment by madler** [comment]
As a programmer, it is most important for you to understand basic logic. "avail_in is zero if enough output space has been provided" does _not_ imply "enough output space been provided if avail_in is zero".
