### ISSUE TITLE
contrib/minizip/mztools.c:40: missing sanity check on fopen return value ?

### ISSUE THREAD

**Issue by dcb314** [madler/zlib#461]
Source code is

  FILE* fpZip = fopen(file, "rb");
  FILE* fpOut = fopen(fileOut, "wb");
  FILE* fpOutCD = fopen(fileOutTmp, "wb");
  if (fpZip != NULL &&  fpOut != NULL) {

Maybe better:

  FILE* fpZip = fopen(file, "rb");
  FILE* fpOut = fopen(fileOut, "wb");
  FILE* fpOutCD = fopen(fileOutTmp, "wb");
  if (fpZip != NULL &&  fpOut != NULL && fpOutCD != NULL) {

**Comment by madler** [comment]
Comments on contrib/minizip should be directed to the author of the third-party contribution. See contrib/README.contrib .
