### ISSUE TITLE
Unable to Unzip file , created from an empty directory zipping

### ISSUE THREAD

**Issue by VivekZak-samsung** [madler/zlib#463]
Steps:
Created an empty directory -> Zipped using zip.h (zipOpen) -> unzOpen returns NULL for the same file (unzip.h)
Note: 
1. Zipped file size is non zero  
2. 7zip/winzip also cant unzip the file

@version1.2.11 #latest

**Comment by madler** [comment]
You are using a third-party contribution from the `contrib` directory, `contrib/minizip`, so you will need to contact the author of that contribution for support. (Gilles Vollant)

**Comment by gvollant** [comment]
for info, there is a fork of my work at https://github.com/nmoinvaz/minizip

**Comment by madler** [comment]
@gvollant Do you think I should replace the version you currently have in zlib with that fork?

**Comment by gvollant** [comment]
I'm not sure we can replace. We must check:
1) if new library is not far bigger
2) if it is both API AND binary (ABI) compatible

**Comment by gvollant** [comment]
I cannot reproduce the problem. I need more about about how EXACTLY reproduce the problem
 
MiniZip 1.1, demo of zLib + MiniZip64 package, written by Gilles Vollant
more info on MiniZip at http://www.winimage.com/zLibDll/minizip.html

Usage : minizip [-o] [-a] [-0 to -9] [-p password] [-j] file.zip [files_to_add]

  -o  Overwrite existing file.zip
  -a  Append to existing file.zip
  -0  Store only
  -1  Compress faster
  -9  Compress better

  -j  exclude path. store only the file name.

root@gv-w81x64:/mnt/n/virest# minizip -h
MiniZip 1.1, demo of zLib + MiniZip64 package, written by Gilles Vollant
more info on MiniZip at http://www.winimage.com/zLibDll/minizip.html

Usage : minizip [-o] [-a] [-0 to -9] [-p password] [-j] file.zip [files_to_add]

  -o  Overwrite existing file.zip
  -a  Append to existing file.zip
  -0  Store only
  -1  Compress faster
  -9  Compress better

  -j  exclude path. store only the file name.

root@gv-w81x64:/mnt/n/virest# exit
exit
gillesvollant@gv-w81x64:/mnt/n/virest$ mkdir uu
gillesvollant@gv-w81x64:/mnt/n/virest$ minizip zz.zip uu/
MiniZip 1.1, demo of zLib + MiniZip64 package, written by Gilles Vollant
more info on MiniZip at http://www.winimage.com/zLibDll/minizip.html

creating zz.zip
File : uu/ is 4096 bytes
error in reading uu/
gillesvollant@gv-w81x64:/mnt/n/virest$ ls -l zz.zip
-rwxrwxrwx 1 gillesvollant gillesvollant 106 Apr 11 12:02 zz.zip
gillesvollant@gv-w81x64:/mnt/n/virest$ unzip -v zz.zip
Archive:  zz.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Defl:N        2   0% 2020-04-11 12:02 00000000  uu/
--------          -------  ---                            -------
       0                2   0%                            1 file
gillesvollant@gv-w81x64:/mnt/n/virest$ unzip zz
zz      zz.zip
gillesvollant@gv-w81x64:/mnt/n/virest$ unzip zz.zip
Archive:  zz.zip
gillesvollant@gv-w81x64:/mnt/n/virest$ 7za x zz.zip -y

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,16 CPUs Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (906ED),ASM,AES-NI)

Scanning the drive for archives:
1 file, 106 bytes (1 KiB)

Extracting archive: zz.zip
--
Path = zz.zip
Type = zip
Physical Size = 106

Everything is Ok

Folders: 1
Files: 0
Size:       0
Compressed: 106
gi
`
