### ISSUE TITLE
Comment for z_stream::zalloc. NO THROW

### ISSUE THREAD

**Issue by dmitry-lipetsk** [madler/zlib#464]
Hello,

I review some C++ code, which uses zlib. And read manual for zlib :)

I see initialization of z_stream::zalloc by throw-based allocation function.

zlib manual say: "zalloc must return Z_NULL if there is not enough memory for the object."

I offer to correct comment for z_stream::zalloc

https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/zlib.h#L98

from " used to allocate the internal state" to  "used to allocate the internal state. **NO THROW**"

Or to any other text with attention about prevent of exception usage.

Thanks.

**Comment by madler** [comment]
I'll leave the comments as is. If an application wants to throw out of zlib from an allocation, that's its business.

**Comment by dmitry-lipetsk** [comment]
"That's its problem" you want to say.

Ok. I understood :)

Thanks.
