### ISSUE TITLE
unnecessary if-branch in gzread.c

### ISSUE THREAD

**Issue by qingkaishi** [madler/zlib#477]
In the following code, the condition "if (strm->avail_in)"  at Line 160 must be true and, thus, is an unnecessary branch.

The condition must be true (i.e., not zero) because if it is zero, the function will return at Line 129. From Line 130 to Line 160, the function will return as long as strm->avail_in is assigned zero.

https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/gzread.c#L124-L164

**Comment by tbeu** [comment]
Resolved by 9331fecc10d1409b8f63cbb3cc2365596255d672.
