### ISSUE TITLE
doubt about the coding of match len and distance

### ISSUE THREAD

**Issue by 361442342** [madler/zlib#479]
@madler
hello madler:
    recently i am focusing on compression algorithms。i read the zlib writed by you。
    in zlib,when encoding match length or distance，you first do a mapper，then make a entropy coding and write the extra bits immediately into the out buffer.
    i think the mapper can not improve the compression ratio,instead it will reduce the compression ratio a little.(From the perspective of entropy)
    it just improve the coding speed and reduce memory use,because the quantity of symbols have being reduced.
    am i right?
    i am expecting for you answer,thank you.

**Comment by madler** [comment]
1. I don't understand your question. (What's a mapper?)
2. This issue is not an issue.

So I am closing this issue.

I recommend that you instead ask your question on an appropriate stackexchange.com forum.

**Comment by 361442342** [comment]
@madler 
for example,
suppose the max match length is 255.match length is diveded into several range：
[0]
[1,2]
[3,4,5,6]
[7,8,9,10,11,12,13,14]
[15,16,17,18,19,20,21]
..
base_lenght = [0,1,3,7,15]
extra_bits = [0,1,2,4,4]

so when you coding the match length 13,
first you find it is in fourth range.so you use huffman coding to code '3'(index start with 0).
then you find its index in the range is 6. so you wirte '0110' to out buffer.
i called this ("10 -> (3,'0100')") mapping.
