### ISSUE TITLE
zlib 1.2.8 always uses Windows 8 - level API

### ISSUE THREAD

**Issue by Tvangeste** [madler/zlib#49]
When compiled with VS2012, zlib ends up always using Windows 8  level API, e.g.: `CreateFile2()`.

Looking at the code, I see that this regression has been introduced in the following commit: 5481269e1fa6d99a1

More specifically, the define on line 31 always defines `IOWIN32_USING_WINRT_API`. That happens because `WINAPI_FAMILY_PARTITION` _is_ defined, even on Windows 7.

I use Windows 7 and Visual Studio 2012 and experience errors since the library don't work (missing methods in kernel32.dll).

**Comment by alanblevins** [comment]
Thanks for the fix @DanKonigsbach. It was just what I needed to keep my weekend project moving.

**Comment by Glyth** [comment]
I'm on windows 7 compiling with Visual Studio 2015.  The WINAPI_FAMILY_ONE_PARTITION macro is apparently not defined, so I cannot use that solution.  As a workaround, I commented out the entire check and define.

The DLL will fail to load on Windows 7 if compiled with that `#define IOWIN32_USING_WINRT_API 1`.

It will complain about missing entry point on KERNEL32.dll CreateFile2().

**Comment by jozefizso** [comment]
Was this issue fixed in 1.2.9 and/or 1.2.10 releases?

**Comment by zouzou123gen** [comment]
Hi,

Sorry I just noticed this now as I was browsing issues in this project. Looks like a lot of time / effort could have been avoided had I been made aware of this issue earlier.

Back when I stumbled upon this problem (May 2013), I had no idea there even was a github project set up; I simply sent my patch via email.
It has been included in rev 89e335abb49cd5c7d29d94e8f506d3f8ed71315a and is part of the 1.2.9 release.

My fix was not limited to the macro fix but also included something necessary to properly unzip files. Below, the email I sent back then - hope it helps.

---

I have noticed 2 issues when trying to use iowin32 functions for a desktop (not Win RT) program.

1) IOWIN32_USING_WINRT_API is always defined.

The WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP) test always evaluates to true so WINRT APIs (CreateFile2, SetFilePointerEx) always get used.
There are 2 solutions:
- Use WINAPI_FAMILY_ONE_PARTITION(WINAPI_FAMILY, WINAPI_PARTITION_APP). The comments in the Include/shared/winapifamily.h file in the Windows Kit show that this is the test to include RT apps but exclude desktop.
- Add a test to ensure that _WIN32_WINNT >= 0x0602.
I have opted for the first solution in my attached patch.

2) dwMoveMethod is not propagated to SetFilePointer.

The dwMoveMethod flag is correctly passed to SetFilePointerEx but not to MySetFilePointerEx & SetFilePointer. It is always FILE_CURRENT.
As a result, it is impossible to unzip a file when not using Win RT APIs.

With the patch I am sending, I can unzip a file with desktop APIs (CreateFile, SetFilePointer) perfectly!

**Comment by timofonic** [comment]
@csware @zouzou123gen  @jozefizso  @Tvangeste @DanKonigsbach @leinadn @metux @mtl1979  @alanblevins  @Glyth @evoskuil @avdv @kreuzerkrieg  Does it happen in this fork? It seems more actively updated https://github.com/Dead2/zlib-ng/

**Comment by zouzou123gen** [comment]
I don't see how that would apply @timofonic, since <https://github.com/Dead2/zlib-ng/> does not have any `contrib/minizip` at all. :D

**Comment by madler** [comment]
This was apparently fixed in 1.2.9.
