### ISSUE TITLE
configure includes wrong zconf.h in out-of-tree builds

### ISSUE THREAD

**Issue by dankegel** [madler/zlib#499]
Out-of-tree compilation fails if you do out-of-tree cmake build and make build sequentially.

Evidently configure's out-of-tree build sometimes pulls in a stale zconf.h
(either the system's, or the default one checked into the top of the source tree)
rather than the one it generated.

**Comment by nmoinvaz** [comment]
CI #492 should have out of source build to ensure that future CMake changes still work with out of source builds.

**Comment by dankegel** [comment]
Oh, quite.  See https://github.com/dankegel/zlib/pull/5  :-)

**Comment by tbeu** [comment]
Duplicate of #344.

**Comment by dankegel** [comment]
No, not quite.  It's related, but even if there were no CMakeLists.txt at all, this bug would exist and be real.

**Comment by madler** [comment]
Should be addressed by https://github.com/madler/zlib/commit/9404df5a1f35866d441e8033b34186ca42962ea9 .
