### ISSUE TITLE
risk and warning

### ISSUE THREAD

**Issue by kouzhudong** [madler/zlib#503]
1>------ 已启动全部重新生成: 项目: zlibvc, 配置: Debug Win32 ------
1>Microsoft (R) Macro Assembler Version 14.27.28826.0
1>Copyright (C) Microsoft Corporation. All rights reserved.
1>
1> Assembling: match686.asm
1>Microsoft (R) Macro Assembler Version 14.27.28826.0
1>Copyright (C) Microsoft Corporation. All rights reserved.
1>
1> Assembling: inffas32.asm
1>adler32.c
1>compress.c
1>crc32.c
1>deflate.c
1>Assembler code may have bugs -- use at your own risk
1>gzclose.c
1>gzlib.c
1>gzread.c
1>gzwrite.c
1>infback.c
1>inffast.c
1>Assembler code may have bugs -- use at your own risk
1>inflate.c
1>inftrees.c
1>ioapi.c
1>iowin32.c
1>C:\Users\Administrator\Desktop\XXXXXXXXcontrib\minizip\iowin32.c(31,32): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
1>trees.c
1>uncompr.c
1>unzip.c
1>zip.c
1>zutil.c
1>正在生成代码...
1> 正在创建库 x86\ZlibDllDebug\zlibwapi.lib 和对象 x86\ZlibDllDebug\zlibwapi.exp
1>zlibvc.vcxproj -> C:\Users\Administrator\Desktop\XXXXXXX\zlib\contrib\vstudio\my\x86\ZlibDllDebug\zlibwapi.dll
1>已完成生成项目“zlibvc.vcxproj”的操作。
========== 全部重新生成: 成功 1 个，失败 0 个，跳过 0 个 ==========

**Comment by tbeu** [comment]
The warning seems to be resolved by ce12773790517034317274f5c65ba70cfeea29f7.
