### ISSUE TITLE
Access violation - code c0000005

### ISSUE THREAD

**Issue by kouzhudong** [madler/zlib#504]
0:000> g
(65e0.6600): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=00000fc0 ebx=baadf00d ecx=00000016 edx=00000000 esi=00f136a0 edi=00f0f628
eip=100100cf esp=00d3ef44 ebp=0000003e iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210202
zlibwapi!gzseek64+0x2cf:
100100cf 8b0483          mov     eax,dword ptr [ebx+eax*4] ds:002b:baae2f0d=????????
0:000> r
eax=00000fc0 ebx=baadf00d ecx=00000016 edx=00000000 esi=00f136a0 edi=00f0f628
eip=100100cf esp=00d3ef44 ebp=0000003e iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210202
zlibwapi!gzseek64+0x2cf:
100100cf 8b0483          mov     eax,dword ptr [ebx+eax*4] ds:002b:baae2f0d=????????
0:000> kv
 # ChildEBP RetAddr  Args to Child              
00 00d3f024 003b277d 00f0c288 00f0f628 00004000 zlibwapi!gzseek64+0x2cf (FPO: [Non-Fpo]) (CONV: stdcall) [C:\Users\Administrator\Desktop\XXX\lib\zlib\gzlib.c @ 439] 
01 00d3f2d0 003b23e1 00f0c288 00d3f3f4 00d3f62c zlib!do_extract_currentfile+0x29d (FPO: [Non-Fpo]) (CONV: cdecl) [C:\Users\Administrator\Desktop\XXX\zlib\zlib\zlib.cpp @ 349] 
02 00d3f3e8 003b1aa9 00f0c288 00000000 00d3f708 zlib!do_extract+0xa1 (FPO: [Non-Fpo]) (CONV: cdecl) [C:\Users\Administrator\Desktop\XXX\zlib\zlib\zlib.cpp @ 394] 
...
0:000> dv 
           file = 0x00f0c288
         offset = 0n70368759969320
         whence = 0n13890536
            ret = 0n-5547199890566565888
              n = 0xf0f628
          state = 0x003b8dc8

**Comment by madler** [comment]
Not enough information to replicate. Closing.
