### ISSUE TITLE
Access violation - code c0000005 (!!! second chance !!!)

### ISSUE THREAD

**Issue by kouzhudong** [madler/zlib#505]
Microsoft (R) Windows Debugger Version 10.0.18362.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.

*** wait with pending attach

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\symbols*http://msdl.microsoft.com/download/symbols
WARNING: Whitespace at end of path element

************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*C:\symbols*http://msdl.microsoft.com/download/symbols
WARNING: Whitespace at end of path element
Symbol search path is: srv*C:\symbols*http://msdl.microsoft.com/download/symbols;srv*C:\symbols*http://msdl.microsoft.com/download/symbols 
Executable search path is: 
ModLoad: 00400000 0040b000   F:\git\其他\zlib\contrib\vstudio\vc15\x86\MiniUnzipDebug\miniunz.exe
ModLoad: 775b0000 7774a000   C:\WINDOWS\SYSTEM32\ntdll.dll
ModLoad: 75ec0000 75fa0000   C:\WINDOWS\System32\KERNEL32.DLL
ModLoad: 74dc0000 74fbe000   C:\WINDOWS\System32\KERNELBASE.dll
ModLoad: 10000000 10030000   F:\git\其他\zlib\contrib\vstudio\vc15\x86\MiniUnzipDebug\zlibwapi.dll
ModLoad: 79230000 7924d000   C:\WINDOWS\SYSTEM32\VCRUNTIME140D.dll
ModLoad: 790b0000 79225000   C:\WINDOWS\SYSTEM32\ucrtbased.dll
(7098.4784): Access violation - code c0000005 (!!! second chance !!!)
*** WARNING: Unable to verify checksum for F:\git\其他\zlib\contrib\vstudio\vc15\x86\MiniUnzipDebug\zlibwapi.dll
eax=000e0fc0 ebx=cdcdcdcd ecx=00000016 edx=00000000 esi=0074e090 edi=0074c008
eip=1000215f esp=0019f998 ebp=0000003e iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00210202
zlibwapi!_inflate_fast+0x3af:
1000215f 8b0483          mov     eax,dword ptr [ebx+eax*4] ds:002b:ce060ccd=????????
*** WARNING: Unable to verify checksum for F:\git\其他\zlib\contrib\vstudio\vc15\x86\MiniUnzipDebug\miniunz.exe
0:000> kv
 # ChildEBP RetAddr  Args to Child              
00 0019f9e8 10010309 007493b4 00002000 00000000 zlibwapi!_inflate_fast+0x3af (FPO: [Uses EBP] [4,16,0]) (CONV: cdecl) [F:\git\其他\zlib\contrib\masmx86\inffas32.asm @ 669] 
01 0019fb00 00401c7e 00749290 0074c008 00002000 zlibwapi!inflate+0x1659 (FPO: [Non-Fpo]) (CONV: stdcall) [F:\git\其他\zlib\inflate.c @ 1047] 
02 0019fd20 00401df8 00749290 0019fd70 0019fd74 miniunz!do_extract_currentfile+0x2fe (FPO: [Non-Fpo]) (CONV: cdecl) [F:\git\其他\zlib\contrib\minizip\miniunz.c @ 435] 
03 0019fd64 004021f7 00749290 00000000 00000000 miniunz!do_extract+0x78 (FPO: [Non-Fpo]) (CONV: cdecl) [F:\git\其他\zlib\contrib\minizip\miniunz.c @ 494] 
04 0019fee4 00402d13 00000002 007468c0 00746750 miniunz!main+0x327 (FPO: [Non-Fpo]) (CONV: cdecl) [F:\git\其他\zlib\contrib\minizip\miniunz.c @ 652] 
05 0019ff04 00402b67 9b7607c3 004011db 004011db miniunz!invoke_main+0x33 (FPO: [Non-Fpo]) (CONV: cdecl) [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78] 
06 0019ff60 004029fd 0019ff70 00402d98 0019ff80 miniunz!__scrt_common_main_seh+0x157 (FPO: [Non-Fpo]) (CONV: cdecl) [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
07 0019ff68 00402d98 0019ff80 75ed6359 003b8000 miniunz!__scrt_common_main+0xd (FPO: [Non-Fpo]) (CONV: cdecl) [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 331] 
08 0019ff70 75ed6359 003b8000 75ed6340 0019ffdc miniunz!mainCRTStartup+0x8 (FPO: [Non-Fpo]) (CONV: cdecl) [d:\agent\_work\7\s\src\vctools\crt\vcstartup\src\startup\exe_main.cpp @ 17] 
09 0019ff80 77617c24 003b8000 23fa9f16 00000000 KERNEL32!BaseThreadInitThunk+0x19 (FPO: [Non-Fpo])
0a 0019ffdc 77617bf4 ffffffff 77638fff 00000000 ntdll!__RtlUserThreadStart+0x2f (FPO: [SEH])
0b 0019ffec 00000000 004011db 003b8000 00000000 ntdll!_RtlUserThreadStart+0x1b (FPO: [Non-Fpo])
0:000> dv
           strm = 0x00003faf
          flush = 0n0
             in = 0
           have = 1
            ret = 0n0
           copy = 0
            put = 0x0019fd1c "`J!"
           hbuf = unsigned char [4] "???"
           bits = 0xd0
           last = struct code
           hold = 0x47
          state = 0xfdfdfdfd
            out = 0x74bfe8
           here = struct code
           next = 0x00000000 ""
           left = 0xc007071
          order = unsigned short [19]
           from = 0x00000000 ""
            len = 0x67d782b3

看样子是栈破坏了。

汇编的编译是默认的。
DLL的编译是：否 (/SAFESEH:NO)。

**Comment by kouzhudong** [comment]
ml /safeseh /coff /Zi /c /Flmatch686.lst match686.asm
ml /safeseh /coff /Zi /c /Flinffas32.lst inffas32.asm

这样编译也是出问题。

**Comment by nmoinvaz** [comment]
See #200.

**Comment by kouzhudong** [comment]
这个zip文件有点问题。

但程序不能崩溃。

昨天用ReleaseWithoutAsm测试崩溃。

今天用ReleaseWithoutAsm测试可以，没问题，且也解压了。
