### ISSUE TITLE
Proposal of performance up (ZSWAP32())

### ISSUE THREAD

**Issue by yochy4671** [madler/zlib#51]
Hi there.

There is a suggestion of performance up to ZSWAP32() of zutil.h.

If the version of gcc seemed 4.3.0 above, proposes to replace the
gcc's builtin function __builtin_bswap32 ().

for example,

diff --git a/zlib/zutil.h b/zlib/zutil.h
index 24ab06b..95080ed 100644
--- a/zlib/zutil.h
+++ b/zlib/zutil.h
@@ -247,7 +247,11 @@ extern z_const char * const z_errmsg[10]; /* indexed by 2-zlib_error */
 #define TRY_FREE(s, p) {if (p) ZFREE(s, p);}
 
 /* Reverse the bytes in a 32-bit value */
+#if (__GNUC__ > 3) && (__GNUC_MINOR__ > 2)
+#define ZSWAP32(q) __builtin_bswap32(q)
+#else
 #define ZSWAP32(q) ((((q) >> 24) & 0xff) + (((q) >> 8) & 0xff00) + \
                     (((q) & 0xff00) << 8) + (((q) & 0xff) << 24))
+#endif
 
 #endif /* ZUTIL_H */

This modification affects the crc32.c(big endian only) and inflate.c.
The arm architecture, about 5 instructions of the object inflate.o is reduced.

Thank you.

----
よっちい

**Comment by mtl1979** [comment]
If you want to test for minimum GCC version of 4.3 you should use
#if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ > 2)

This way it also works when GCC version is 5.0, 5.1 or 5.2

**Comment by Dead2** [comment]
You might want to have a look at this commit, it implements the same thing but for several different compilers.
https://github.com/Dead2/zlib-ng/commit/71992cb562c7432a2a836982cbc7764fa062af63

There is also a followup commit to fix the lacking \ at the end of the clang line.

**Comment by mtl1979** [comment]
Hopefully there will be zlib 1.2.9 some day and it will include also enhancements like this... There is quite many pull requests already that are worth including in next version IMHO...

**Comment by madler** [comment]
This won't make anything faster.  `ZSWAP32()` is not used inside any loops.  Unless you are making the CRC tables dynamically, but even then you only make the tables once and it's complete in microseconds, so again it won't be noticed.

Even so, I may eventually incorporate Dead2's commit since it's been done, but it is not a "performance up".
