### ISSUE TITLE
uncompress second param always return same number

### ISSUE THREAD

**Issue by scorpion9111** [madler/zlib#515]
uncompress second param always return same number
Byte uncompr[512];
uLong uncomprLen=512;
uncompress(uncompr, &uncomprLen, compr, comprLen);
uncomprLen always = 512

try 1.2.8 and 1.2.11 both have this problem

code:

#define CHECK_ERR(err, msg) { \
    if (err != Z_OK) { \
        aos_printf(0, "%s error: %d\n", msg, err); \
    } \
}

void test_compress(void)
{
	z_const char hello[] = "hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello!";
	Byte compr[512], uncompr[512];
    uLong comprLen=512, uncomprLen=512;
    int err;
    uLong len = (uLong)strlen(hello)+1;

    err = compress(compr, &comprLen, (const Bytef*)hello, len);
    CHECK_ERR(err, "compress");

    strcpy((char*)uncompr, "garbage");

    err = uncompress(uncompr, &uncomprLen, (const Bytef*)compr, comprLen);
    CHECK_ERR(err, "uncompress");

    if (strcmp((char*)uncompr, hello)) {
        printf(0, "bad uncompress\n");
    } else {
        printf(0, "uncompress(): %s\n", (char *)uncompr);
    }
}

**Comment by madler** [comment]
When I run it, I get `uncomprLen` is 112 after the `uncompress()`.

**Comment by scorpion9111** [comment]
same code, just add print
![image](https://user-images.githubusercontent.com/13959441/88026994-418d3800-cb69-11ea-8b5d-598b822cdda0.png)
void test_compress(void)
{
	z_const char hello[] = "hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello!";
	Byte compr[512], uncompr[512];
    uLong comprLen=512, uncomprLen=512;
    int err;
    uLong len = (uLong)strlen(hello)+1;

    err = compress(compr, &comprLen, (const Bytef*)hello, len);
    CHECK_ERR(err, "compress");
	aos_printf(0, "compress before:%d after:%d\n",len,comprLen);
	
    strcpy((char*)uncompr, "garbage");

    err = uncompress(uncompr, &uncomprLen, (const Bytef*)compr, comprLen);
    CHECK_ERR(err, "uncompress");
	aos_printf(0, "compress before:%d after:%d\n",comprLen,uncomprLen);
	
    if (strcmp((char*)uncompr, hello)) {
        aos_printf(0, "bad uncompress\n");
        aos_printf(0, "uncompr:%s\n",uncompr);
    } else {
        aos_printf(0, "uncompress(): %s\n", (char *)uncompr);
    }
}

**Comment by scorpion9111** [comment]
@madler Can you help me analyze the reasons

**Comment by scorpion9111** [comment]
system type             : Ralink SoC
processor               : 0
cpu model               : MIPS 24Kc V5.0
BogoMIPS                : 386.04
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : yes
hardware watchpoint     : yes, count: 4, address/irw mask: [0x0004, 0x0ffc, 0x0ff8, 0x0ffb]
ASEs implemented        : mips16 dsp
shadow register sets    : 1
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by madler** [comment]
You didn't mention that the `uncompress()` fails. If it fails, it will not set the second parameter.

What is the `uncompress()` return code?

**Comment by scorpion9111** [comment]
if return != Z_OK will print error info in CHECK_ERR
a moment ago  I seem to have found the cause
have another uncompress() in my project, now i modify another uncompress() to diff name , this problem disapear
but another uncompress() param totally different ，compile and run ，There are no error messages
thank you very much

**Comment by madler** [comment]
Yes, I see it should print the error info, but you did not share that output from when you ran your code. Please share that output.

What was the cause that you found?

**Comment by scorpion9111** [comment]
code:
#define CHECK_ERR(err, msg) { \
    if (err != Z_OK) { \
        aos_printf(0, "%s error: %d\n", msg, err); \
    } \
}
void test_compress(void)
{
	z_const char hello[] = "hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello, hello!";
	Byte compr[512], uncompr[512];
        uLong comprLen=512, uncomprLen=512;
        int err;
        uLong len = (uLong)strlen(hello)+1;

        err = compress(compr, &comprLen, (const Bytef*)hello, len);
        CHECK_ERR(err, "compress");
	aos_printf(0, "compress before:%d after:%d ret:%d\n",len,comprLen,err);
	
        strcpy((char*)uncompr, "garbage");

        err = uncompress(uncompr, &uncomprLen, (const Bytef*)compr, comprLen);
        CHECK_ERR(err, "uncompress");
	aos_printf(0, "uncompress before:%d after:%d ret:%d\n",comprLen,uncomprLen,err);
	
        if (strcmp((char*)uncompr, hello)) {
            aos_printf(0, "bad uncompress\n");
            aos_printf(0, "uncompr:%s\n",uncompr);
        } else {
            aos_printf(0, "uncompress(): %s\n", (char *)uncompr);
        }
}
uncompress(), there is a function with the same name in my project（They have different parameters）
S32 uncompress(S8* arcfile,S8* outbuffer)
{	
   	currentpos = 0;
        read_header(arcfile);
        if( read_header(arcfile) )
        {
      
		CurOutBufPos = 0;
		if( extract(arcfile,outbuffer) )
			{
			//printf("\n\r Unarj successful!");  		   
			 return origsize;
		    }
		//printf("\n\rUnarj fails!");
        }
	return 0;
}
but compile and link no error messages
so run uncompress() error occurred
rename another uncompress() function ，There's no problem I said above
