### ISSUE TITLE
deflateInit2 requires next_in to be set?

### ISSUE THREAD

**Issue by Liam89** [madler/zlib#528]
The manual states next_in must be initialized before calling deflateInit2, is this true? Doesn't look like it from deflate.c. I was hoping to re-use the stream with deflateReset to reduce the internal allocations

**Comment by madler** [comment]
The code currently does not look at `next_in`. However it is still required to initialize `next_in` as part of the interface, because future versions _could_ use input data provided at initialization to determine the memory allocation, or for other purposes.

I do not understand the connection to using `deflateReset` to re-use the stream.

**Comment by Liam89** [comment]
Trying to do something along the lines of the below, so it doesn't keep allocating and deallocating internally

```
class GZCompress
{
public:
	GZCompress()
	{
		deflateInit2(&stream, Z_DEFAULT_COMPRESSION, Z_DEFLATED, 16 + 15, 8, Z_DEFAULT_STRATEGY);
	}

	~GZCompress()
	{
		deflateEnd(&stream);
	}

	int compress(unsigned char* dest, unsigned long * destLen, unsigned char* source, unsigned long sourceLen)
	{
		stream.next_in = source;
		stream.avail_in = sourceLen;
		stream.next_out = dest;
		stream.avail_out = *destLen;

		int err = deflate(&stream, Z_FINISH);
		if(err != Z_STREAM_END)
		{
			deflateReset(&stream);
			return err;
		}

		return deflateReset(&stream);
	}
private:
	z_stream stream = {};
};
```

**Comment by madler** [comment]
So what's the problem?

**Comment by Liam89** [comment]
Can't set next_in before deflateInit2 because its unknown and changes, other than to null, but wanted to check because its undefined

**Comment by madler** [comment]
Ah. `Z_NULL` counts as initializing `next_in`. Your `z_stream stream = {};` does that. There is no issue.

**Comment by Liam89** [comment]
okay thanks
