### ISSUE TITLE
Bug ? file size limit of 8ko 

### ISSUE THREAD

**Issue by snowgoon88** [madler/zlib#534]
On my Xubuntu 18.04, **zlib cannot create file with a size larger than 8ko**.

I have a simple example in the gist below where a create a file, with a loop to add data to it.

For small loop number, created file can be gunzipped. But for larger number, say looping more than 2000 times, the created file **always as a size of 8ko**. And cannot be gunzipped (gzip: gz_output.gz: unexpected end of file).

Is this a bug or I do someting wrong ??

Gist link : https://gist.github.com/snowgoon88/eead4a00e1441d405f1d30320fa999de
```
// g++ -o test_gzlib_g++ test_gzlib.cpp `pkg-config --cflags --libs zlib`

#include <iostream>
#include <cstring>
#include <zlib.h>

const char data[] = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse elementum varius lectus, quis tempor odio sodales eu. Nullam iaculis ante accumsan tortor molestie lacinia. Proin fringilla egestas enim id condimentum. Proin finibus vel neque eu posuere. Maecenas aliquet congue consectetur. Aenean dignissim, nisi id volutpat mollis, purus libero consectetur lorem, vitae bibendum orci eros id tortor. Proin efficitur enim leo, auctor commodo tortor gravida sit amet. Integer sit amet suscipit magna. Cras vel orci dolor. Nullam non ante ut magna mollis pretium. Aenean non ligula sapien. Etiam massa est, tristique vitae pharetra nec, interdum vitae turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam ut justo sit amet lacus pharetra hendrerit.";

int main(int argc, char *argv[])
{
  std::cout << "Data[" << strlen(data) << "]=" << data <<  std::endl;
  
  // open file
  gzFile fp = gzopen( "gz_output.gz", "w" );
  if( fp == nullptr ) {
    std::cerr << "Error opening gz_output.gz in writing" << std::endl;
    exit(1);
  }

  // write data
  for( unsigned int i = 0; i < 2000; ++i) {
    int nb_written = gzwrite( fp, data, strlen(data) );
    if( nb_written != strlen(data) ) {
      std::cerr << "Error writing nb_written=" << nb_written << " != " << strlen(data) << std::endl;
    }
  }  

  //close
  gzclose( fp );
      
  return 0;
}
```

**Comment by minchai23** [comment]
I tested it with your code and can decompress it.

**Comment by snowgoon88** [comment]
Thanks for the info.
BTW, I changed my Linux distro from Ubuntu 18.0 to Debian 10 and now it works. I believe "my" zlib module had a strange size limit (I had the same problem on 2 different software using zlib). Strange.
Guess you can close the issue, as this "bug" will not be easily reproduced.

**Comment by aleksandaratanasov** [comment]
> 
> 
> Thanks for the info.
> BTW, I changed my Linux distro from Ubuntu 18.0 to Debian 10 and now it works. I believe "my" zlib module had a strange size limit (I had the same problem on 2 different software using zlib). Strange.
> Guess you can close the issue, as this "bug" will not be easily reproduced.

Ubuntu is derived from Debian Sid. Ubuntu 18.04/18.10 (there is no 18.0) is Debian 9. Ubuntu adds patches and its own things so the two are not the same. However I would recommend to try Ubuntu 19.10 - 20.10 (Debian 10) or 21.04 (Debian 11) to see if the issue persists. If it is still there then we are talking about an Ubuntu-specific issue.

**Comment by snowgoon88** [comment]
Sorry, it was an Unbuntu 18.04.
Now, with a "true" Debian 10 (no Ubuntu patch, direct from debian.org), I do not have any problem with the zlib.
