### ISSUE TITLE
Bug: possible bug in zpipe.c example

### ISSUE THREAD

**Issue by kfiros** [madler/zlib#537]
Hello,

In examples/zpipe.c in line [140#](https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/examples/zpipe.c#L140), shouldn't you also test for strm.avail_in !=0 ?

I've encountered a case where strm.avail_out = 0 and also strm.avail_in = 0, which leads to an error.

Thanks,
Kfir

**Comment by madler** [comment]
No. In fact it is _essential_ to allow `strm.avail_in == 0`, because there may be available output yet to deliver, even once the available input has been consumed.

What do you mean "error"?

**Comment by kfiros** [comment]
Oh I'm sorry, you are right. The error I get is Z_BUF_ERROR, and AFAIU it determines there is no more input to consume/output to produce.

Thank you Mark
