### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by peterbmckinley** [madler/zlib#538]
Hi this isn't so much an issue as a request for help from the experts!!

I have a service which creates a log from GPS derived GPRMC NMEA sentences, and limits the overall log size to 100MB (the device is an SBC with everything running of an SD card).

The command is currently 

gpspipe -r | grep GPRMC | curtail -s 100M /path/to/gps.log

Could this be modified to use gzlog to compress the log file on the fly? The goal is to maximise the length of time the log can cover, within its 100MB limit

Thanks in advance!

Peter

**Comment by madler** [comment]
You should post such questions on stackoverflow, which increases the chances the answers are useful to others.

**Comment by peterbmckinley** [comment]
No problem' send me a link.

**Comment by madler** [comment]
stackoverflow.com

tag your question with "compression" and "gzip".

**Comment by peterbmckinley** [comment]
Thanks Mark
