### ISSUE TITLE
gzip inflate crash

### ISSUE THREAD

**Issue by CxMachine** [madler/zlib#544]
int data_decompress(Bytef *idata, unsigned int ilen, Bytef *odata, unsigned int *olen)
{
    int err;
    z_stream z = {0};
    z.next_in = idata;
    z.next_out = odata;
    z.opaque  = Z_NULL;
    //z.data_type = Z_BINARY;
    //z.adler = A_CRC32;
    //z.avail_in = z.avail_out = 1;
    LOG_INFO("z.next_in:%d, z.avail_in:%d, z.next_out:%d, z.avail_out:%d",
             z.next_in, z.avail_in, z.next_out, z.avail_out);
    if ((err=inflateInit2(&z, MAX_WBITS|16))!=Z_OK) {
        printf("inflateInit failed->err:%d\n", err);
        return err;
    }
    while(z.total_out<*olen && z.total_in<ilen){
        z.avail_in = z.avail_out = 1;
        LOG_INFO("inflate->err:%d, a_in:%d, a_out:%d, z.data_type:%d", err, z.avail_in, z.avail_out, z.data_type);
        err=inflate(&z, Z_NO_FLUSH);
        LOG_INFO("z.total_in:%d, z.total_out:%d", z.total_in, z.total_out);
        if(err!=Z_OK)break;
    }
    if (inflateEnd(&z) != Z_OK) {
        printf("inflateEnd failed!\n");
        return err;
    }
    *olen = z.total_out;
    return Z_OK;
}

run to  err=inflate(&z, Z_NO_FLUSH); crash

**Comment by madler** [comment]
Works fine for me, including on very large gzip files. You likely have an error in your buffer allocations.

**Comment by CxMachine** [comment]
> Works fine for me, including on very large gzip files. You likely have an error in your buffer allocations.

Thanks for answer！
I checked the buffer is ok.My system is embedded linux，CPU is arm.Zip uncompress is ok,the crash is only for gzip uncompress!The gzip data from js pako.gzip("sdfsfsdfsdfd").

**Comment by madler** [comment]
Please provide the gzip stream.

**Comment by CxMachine** [comment]
Thanks again！！！
The gzip stream->
1F 8B 08 00 00 00 00 00 00 03 53 35 77 52 35 32 2A 01 62 55 63 47 20 59 0C 62 19 39 03 C9 32 A8 98 A9 93 2A 58 4D 0A 84 6F 08 91 2D 86 F1 CC 5D 40 02 C8 2A 8C 50 54 18 60 51 61 8C A9 C2 D4 05 48 02 00 42 F6 AC E1 8D 00 00 00

**Comment by CxMachine** [comment]
> Please provide the gzip stream.

Thanks again！！！
The gzip stream->
1F 8B 08 00 00 00 00 00 00 03 53 35 77 52 35 32 2A 01 62 55 63 47 20 59 0C 62 19 39 03 C9 32 A8 98 A9 93 2A 58 4D 0A 84 6F 08 91 2D 86 F1 CC 5D 40 02 C8 2A 8C 50 54 18 60 51 61 8C A9 C2 D4 05 48 02 00 42 F6 AC E1 8D 00 00 00
This is the original text->{"t":"s","v":[{"d":1,"s":1},{"d":2,"s":0},{"d":3,"s":0}]}

**Comment by madler** [comment]
Still no issue. What version of zlib, what operating system, what compiler, what machine?

**Comment by CxMachine** [comment]
> Still no issue. What version of zlib, what operating system, what compiler, what machine? Also provide the complete program that results in the crash.

zlib version: 1.2.11
operating system: Linux version 4.1.15-g02fa222-dirty (eagle@ubuntu) (gcc version 4.9.2 20140904 (prerelease) (crosstool-NG linaro-1.13.1-4.9-2014.09 - Linaro GCC 4.9-2014.09) ) #97 SMP PREEMPT Tue Nov 17 15:18:18 CST 2020
compiler: gcc-linaro-arm-linux-gnueabihf-4.9-2014.09
machine: a embedded host->CPU:IMX6ULtraLite(Cortex-A7),Memery:256MB

complete program:
#define MAX_ONE_JSON_MESSAGE_SIZE   ( 1024*10)
static cJSON* mqtt_client_message_decode_compressed(const struct mosquitto_message *message){
    unsigned long payloadlen,json_str_len=MAX_ONE_JSON_MESSAGE_SIZE-1;
    char json_str[MAX_ONE_JSON_MESSAGE_SIZE];
    LOG_INFO("mqtt_client_message_decode_compressed");
    if(!strcmp(g_mqtt_client->subcribe_topic, message->topic)
       || !strcmp(g_mqtt_client->publish_topic, message->topic) ){
        // if(Z_OK!=uncompress((Bytef*)json_str, &json_str_len, message->payload, message->payloadlen)){
        LOG_INFO("uncompress gzip");
        payloadlen = message->payloadlen;
        print_buf((char*)message->payload, message->payloadlen);// this code is ok,gzip stream i provide for you comes here!
        if(Z_OK!=uncompress2_2((Bytef*)json_str, &json_str_len, message->payload, &payloadlen)){
           LOG_INFO("uncompress fail");
           return NULL;
        }
        json_str[json_str_len]='\0';
        LOG_INFO("mqtt_client_message_decode_compressed:%s",json_str);
        return cJSON_Parse(json_str);
    }
    return NULL;
}

uncompress function:
int uncompress2_2 (Bytef *dest,
    uLongf *destLen,
    const Bytef *source,
    uLong *sourceLen)
{
    z_stream stream;
    int err;
    const uInt max = (uInt)-1;
    uLong len, left;
    Byte buf[1];    /* for detection of incomplete stream when *destLen == 0 */

    len = *sourceLen;
    if (*destLen) {
        left = *destLen;
        *destLen = 0;
    }
    else {
        left = 1;
        dest = buf;
    }

    stream.next_in = (z_const Bytef *)source;
    stream.avail_in = 0;
    stream.zalloc = (alloc_func)0;
    stream.zfree = (free_func)0;
    stream.opaque = (voidpf)0;

    err = inflateInit2(&stream, MAX_WBITS|32);
    if (err != Z_OK) return err;

    stream.next_out = dest;
    stream.avail_out = 0;

    do {
        if (stream.avail_out == 0) {
            stream.avail_out = left > (uLong)max ? max : (uInt)left;
            left -= stream.avail_out;
        }
        if (stream.avail_in == 0) {
            stream.avail_in = len > (uLong)max ? max : (uInt)len;
            len -= stream.avail_in;
        }
        LOG_INFO("stream.avail_in:%d, stream.avail_out:%d", stream.avail_in, stream.avail_out);
        err = inflate(&stream, Z_NO_FLUSH);// crashed here!!! tryed many method,but still crash,i hava no idea now! please save me,thanks!!!
    } while (err == Z_OK);

    *sourceLen -= len + stream.avail_in;
    if (dest != buf)
        *destLen = stream.total_out;
    else if (stream.total_out && err == Z_BUF_ERROR)
        left = 1;

    inflateEnd(&stream);
    return err == Z_STREAM_END ? Z_OK :
           err == Z_NEED_DICT ? Z_DATA_ERROR  :
           err == Z_BUF_ERROR && left + stream.avail_out ? Z_DATA_ERROR :
           err;
}

**Comment by madler** [comment]
Please post a complete, compilable, minimal program that causes the crash. A complete program would have things like a `main()` routine and all the includes and definitions needs to compile. Use the <> operation in the menu bar just above the message editing box to format code to retain its formatting and be readable.

**Comment by CxMachine** [comment]
> Please post a complete, compilable, minimal program that causes the crash. A complete program would have things like a `main()` routine and all the includes and definitions needs to compile. Use the <> operation in the menu bar just above the message editing box to format code to retain its formatting and be readable.

I wrote a simple test program，It can work normally，x86、ARM all ok! But the same code->test_gzip() in my job dosen't work!

`#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "zlib-1.2.11/include/zlib.h"
#define DEST_BUFFER_SZIE 512

int uncompress2_2 (Bytef *dest,
    uLongf *destLen,
    const Bytef *source,
    uLong *sourceLen)
{
    z_stream stream;
    int err;
    const uInt max = (uInt)-1;
    uLong len, left;
    Byte buf[1];    /* for detection of incomplete stream when *destLen == 0 */

    len = *sourceLen;
    if (*destLen) {
        left = *destLen;
        *destLen = 0;
    }
    else {
        left = 1;
        dest = buf;
    }
    stream.next_in = (z_const Bytef *)source;
    stream.avail_in = 0;
    stream.zalloc = (alloc_func)0;
    stream.zfree = (free_func)0;
    stream.opaque = (voidpf)0;
    err = inflateInit2(&stream, MAX_WBITS|32);
    if (err != Z_OK) return err;
    stream.next_out = dest;
    stream.avail_out = 0;
    do {
        if (stream.avail_out == 0) {
            stream.avail_out = left > (uLong)max ? max : (uInt)left;
            left -= stream.avail_out;
        }
        if (stream.avail_in == 0) {
            stream.avail_in = len > (uLong)max ? max : (uInt)len;
            len -= stream.avail_in;
        }
        printf("stream.avail_in:%d, stream.avail_out:%d\n", stream.avail_in, stream.avail_out);
        err = inflate(&stream, Z_NO_FLUSH);
    } while (err == Z_OK);
    *sourceLen -= len + stream.avail_in;
    if (dest != buf)
        *destLen = stream.total_out;
    else if (stream.total_out && err == Z_BUF_ERROR)
        left = 1;
    inflateEnd(&stream);
    return err == Z_STREAM_END ? Z_OK :
           err == Z_NEED_DICT ? Z_DATA_ERROR  :
           err == Z_BUF_ERROR && left + stream.avail_out ? Z_DATA_ERROR :
           err;
}

void test_gzip(){
  Byte dest[DEST_BUFFER_SZIE],
       source[]={0x1F,0x8B,0x08,0x00,0x00,0x00,0x00,0x00,0x00,0x03,0xAB,0x56,0x2A,0x51,0xB2,0x52,0x2A,0x56,0xD2,0x51,0x2A,0x53,0xB2,0x8A,0xAE,0x56,0x4A,0x51,0xB2,0x32,0xD4,0x01,0xF2,0xAD
                 ,0x0C,0x6B,0x75,0xC0,0x3C,0x23,0x14,0x9E,0x31,0x94,0x17,0x5B,0x0B,0x00,0xB4,0x8A,0xB9,0x48,0x39,0x00,0x00,0x00};
  uLong dest_len=DEST_BUFFER_SZIE,
        source_len=sizeof(source);
  int err=uncompress2_2(dest, &dest_len, source, &source_len);
  if(Z_OK==err){
    dest[dest_len]='\0';
    printf("uncompress success:\n%s\n",dest);
  } else{
    printf("uncompress fail->err:%d",err);
  }
}

int main(int argc, char* argv[]){
  test_gzip();
  return 0;
}`

**Comment by CxMachine** [comment]
> Please post a complete, compilable, minimal program that causes the crash. A complete program would have things like a `main()` routine and all the includes and definitions needs to compile. Use the <> operation in the menu bar just above the message editing box to format code to retain its formatting and be readable.

Thanks again for you kind help.I found the cause of the problem. In my project, there is a function (crc32) that is the same as zlib.
I changed the function to a static function  and the problem was solved.
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000407e97 in crc32 (s=0x0, len=4294958384) at /usr/local/fprj/xuyuan-gateway/xuyuan-gateway/common/qc_map.c:256
256	    crc32_tab[(crc32val ^ s[i]) & 0xff] ^
(gdb)
