### ISSUE TITLE
Apparent dead branch in build script.

### ISSUE THREAD

**Issue by Kerdek** [madler/zlib#546]
We have something to the effect of
```
#
# Check to see if we have large file support
#
add_definitions(-D_LARGEFILE64_SOURCE=1)
# ...
if(HAVE_OFF64_T)
    add_definitions(-D_LARGEFILE64_SOURCE=1)
endif()
```

What is the intention here?

**Comment by AraHaan** [comment]
This would enable zlib to be able to compress files over the size of 2 gigabytes I think since the size of the content would be an 64 bit int.

**Comment by Kerdek** [comment]
Perhaps i have misunderstood. I will close the issue.
