### ISSUE TITLE
Misleading indentation compiler warning

### ISSUE THREAD

**Issue by jkflying** [madler/zlib#565]
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/contrib/minizip/zip.c#L529-L530

I get warnings on new versions of GCC that the indentation of these lines is misleading, since they are indented to be under the scope of the `for` loop, while actually there are no braces so they are in the scope of the outer `while` loop.

More cosmetic than functional, but I thought I'd mention it since everyone will get warnings now with new compilers.

**Comment by madler** [comment]
Fixed in a soon-to-be-pushed commit. Thanks.
