### ISSUE TITLE
deflateParams() may not fully flush before changing compression

### ISSUE THREAD

**Issue by tstuefe** [madler/zlib#57]
deflateParams() calls deflate(..., FLUSH) to flush the current block before changing compression levels. This may not fully flush the current block if the output buffer is too small. In that case, compression function may be changed in the middle of the current block, which may corrupt the deflated data.

Proposal for a solution:

- Change deflateParams(): if the deflate(..., FLUSH) is not able to fully flush the current block because it needs more output buffer, it shall not change the compression parameters but return a new return code (e.g. "Z_UNFINISHED_BLOCK") which the caller shall handle by repeating the call to deflateParams() with the same compression parameters and more output buffer.

- deflateParams() may also set z_stream->avail_in to 0 on its call to deflate(..., FLUSH) to temporarily defer new input till current block is fully flushed.

- All this would change the behaviour of deflateParams() incompatibly, so maybe a new deflateParams2() would be better instead.

This is related to a bug in the OpenJDK (https://bugs.openjdk.java.net/browse/JDK-8028804)

**Comment by madler** [comment]
I have updated the documentation to note the behavior.  I will leave the responsibility with the user to flush the stream before called `deflateParams()` if the parameter change is required to take effect at an exact location in the uncompressed data.  Note that `deflateParams()` already does signal an unfinished block with `Z_BUF_ERROR`.  In this case, the parameter change will take effect at an undefined location in the data provided so far, but the deflated data will _not_ be corrupted.

**Comment by tstuefe** [comment]
Thank you for adressing this! I think the comment is clear enough.
