### ISSUE TITLE
Recompress a gzip file

### ISSUE THREAD

**Issue by Pancrase** [madler/zlib#571]
**My problem**

I tried to decompress a gzip-compressed file and rebuild it. Why can't  I  reconstructed data be the same as the original compressed data?

**the original gzip-compressed data**: (compressed by gzip command in linux server)
0000: 1f 8b 08 08 18 02 e8 60 00 03 74 65 73 74 4e 41 5f 52 31 2e 66 61 73 74 71 00 cc fd cd 8e 2b b9
0020: b2 34 0a ce bf a7 68 40 93 04 5a 0d ac fc 8d cc 83 18 5c 07 d1 c1 06 d4 d0 a4 39 b8 ef ff 24 2d
0040: 77 33 23 19 c1 50 46 ac da fb ec 73 54 55 2b 33 f5 97 b5 5c 0c a7 bb b9 99 f1 ff fa ff 95 ff d7
0060: ff fb cf 9f d7 9f 9f ff fa f8 f9 af ff cf f4 ff fd ff bc a7 f4 7f ff df ff f5 f9 5f af af 7f 5e
0080: ff eb f3 ed fd fd bf 5e df 3f 3e fe 1f af ff 75 ff af 3f ff f5 e7 ff dc 8b 65 2b 25 59 ce c5 cc
00A0: 1e 5f 53 29 39 fb 7d f7 ec 5f f3 e3 b1 c7 e3 8f 7f e3 eb 9d 5f cd e2 9b 9c fd 15 fe c2 fb e3 a9
00C0: 8f af fe 26 8f bb fd 21 ...

**After decompress**
@ST-E00199:49:H7LH3CCXX:5:1101:5233:1344 1:N:0:0
NTAGATTCAGGTAAACAGCTTGGGATTNGGGGAGTCATTCTTCCATTCNTCCATTCAATCCATGGCAGCAAACNGAGAAATAAAATGCATGAATTCTGGAGCTTGATTGCTTGAGTTCTCNATTCCAGTTCTTGCTAGCTCTGAGACAC
+...

And then  I then recompressed it to expect it to be restored, but I failed! The header is the same as the original data, but the compressed block is different. (The level is 6, I've tried other levels and still failed.)
**recompressed data**
0000: 1f 8b 08 08 18 02 e8 60 00 03 74 65 73 74 4e 41 5f 52 31 2e 66 61 73 74 71 00 cc bd cb 8e e4 ca
0020: ae 2c 38 3f 5f d1 40 4c 0a 68 35 90 6f 65 6e 68 70 09 47 cb 2f a0 86 26 ed 83 fb ff 5f d2 22 cd
0040: cc e5 7a 44 4a b5 ce 3e a7 6f ac aa ca 78 28 22 56 52 14 9d 34 1a cd ff c7 ff 5b fe af ff fb e5
0060: e5 f5 e7 e7 5f 1f 3f ff fa 9f fd ff f3 3f df 53 fa 5f ff eb 5f 9f ff 7a 7d 7d 79 fd d7 e7 db fb
0080: fb bf 5e df 3f 3e fe 8f d7 7f cd ff 7a f9 d7 cb 7f cc c5 b2 95 92 2c e7 62 66 cb cf 54 4a ce fe
00A0: dc 9c fd 67 5e 5e 5b 5e 5f fe c4 cf 99 3f cd e2 4e ce fe 0e 7f e3 bc 1c ba fc f4 0f 59 9e f6 97...

This is my implementation code. For code brevity, all memory freeing has been omitted:
**Code**
```
// function: get cstream, dstream, gzipHeader
z_stream* getdstream()
{
    z_stream *dStream = new z_stream;
    dStream->zalloc = Z_NULL;
    dStream->zfree = Z_NULL;
    dStream->opaque = Z_NULL;
    int ret = inflateInit2(dStream, 31);
    if (ret != Z_OK) return nullptr;
    return dStream;
}

z_stream* getcstream(int level)
{
    z_stream *cStream = new z_stream;
    cStream->zalloc = Z_NULL;
    cStream->zfree = Z_NULL;
    cStream->opaque = Z_NULL;
    int ret =  deflateInit2(cStream, level, Z_DEFLATED, 31, 8, Z_DEFAULT_STRATEGY); // i need gzip header windowBits=31
    if (ret != Z_OK) return nullptr;
    return cStream;
}

gz_header* constructGzipHeader(int len)
{
    gz_header* head = new gz_header();
    Bytef* extra = new Bytef[len];
    Bytef* name = new Bytef[len];
    Bytef* comment = new Bytef[len];
    head->extra = extra;
    head->extra_max = len;
    head->name = name;
    head->name_max = len;
    head->comment = comment;
    head->comm_max = len;
    head->done = 0;
    return head;
}

int main()
{
    //the original gzip-compressed data, all memory space is enough
    char* readBuf;  // compressed buffer Assume that a value has been assigned
    int readBufLen; // compressed bufferLen Assume that a value has been assigned
    int decompressedBufLen = 50 * 1024;
    char* decompressedBuf = new char[decompressedBufLen];
    int rebuildBufLen = 50 * 1024;
    char* rebuildBuf = new char[rebuildBufLen];

    // decompress
    z_stream* dStream = getdstream();
    gz_header* head = constructGzipHeader(50 * 1024);
    dStream->next_in = (Bytef*)readBuf;
    dStream->avail_in = readBufLen;
    dStream->next_out = (Bytef*) decompressedBuf;
    dStream->avail_out = decompressedBufLen;
    inflateGetHeader(dStream, head);
    inflate(dStream, Z_FINISH); // we get the decompressed data in decompressedBuf

    // compress
    z_stream* cStream = getcstream(6);
    cStream->next_in = (Bytef*) decompressedBuf;
    cStream->avail_in = decompressedBufLen;
    cStream->next_out = (Bytef*) rebuildBuf;
    cStream->avail_out = rebuildBufLen;
    deflateSetHeader(cStream, head);
    deflate(cStream, Z_FINISH);
    return 0;
}
```

**Comment by madler** [comment]
A lossless compressor guarantees that if you compress something, and then decompress that, you get exactly the original thing you compressed. However there is _neither_ a guarantee _nor_ any expectation whatsoever that decompressing compressed data and recompressing it will give you the same thing. There are many, many ways to generate valid compressed data given an input, as evidenced by the very existence of compression levels.

That lack of guarantee or expectation applies to different settings of a given compressor, to different versions of the same compression code, and certainly to different compression codes. In this case you were trying to get zlib to produce the same compressed data as gzip, where those two have different code and strategies for the emission of compressed blocks. (They happen to have been written by the same person, but he changed the approach for zlib, written after gzip.) For anything but very small inputs, you will never be able to get the same compressed output from gzip and zlib, no matter the settings or versions.

Your desire to regenerate the same output is flawed in the first place. There is no need for that. The only thing you need from a compressor and decompressor is the lossless guarantee.

**Comment by Pancrase** [comment]
Oh, I see. Thank you!
