### ISSUE TITLE
How to include zlib into CMake project correctly?

### ISSUE THREAD

**Issue by folibis** [madler/zlib#574]
I use the `zlib` source tree as a subfolder of another project. But my build has failed due to missing `zconf.h`   
After searching the issues I still don't understand why we need to rename the `zconf.h`.  
I include zlib in the following way:

```cmake
set(ZLIB_VERSION zlib-1.2.11)
add_subdirectory(external/${ZLIB_VERSION})
add_dependencies(${PROJECT_NAME} zlibstatic)
target_link_libraries(${PROJECT_NAME} PRIVATE zlibstatic)
include_directories(PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}/external/${ZLIB_VERSION}
)
```
Is that wrong? Is there some fix/instruction ?

**Comment by nmoinvaz** [comment]
Include zlib build directory also.

**Comment by nmoinvaz** [comment]
Maybe something like: include_directories(PUBLIC
        ${CMAKE_CURRENT_BINARY_DIR}/external/${ZLIB_VERSION}
)

**Comment by nmoinvaz** [comment]
Then you have to specify that directory as the second argument to add_subdirectory.

**Comment by folibis** [comment]
@nmoinvaz, first of all, I would like to thank you for the help. I've added `${CMAKE_CURRENT_BINARY_DIR}/external/${ZLIB_VERSION})` to the `include_directories()` and to the `add_subdirectory` as you've suggested. Looks that that fixed my problem.
