### ISSUE TITLE
Veracode scan complains the malloc is not checked for return value.

### ISSUE THREAD

**Issue by KrishnaRLolage** [madler/zlib#577]
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/zutil.c#L311

We use Veracode for scanning our mobile application. It complains the following when pugixml lib is used.

The result of this call to malloc() is not checked for success before being used. This can result in application instability or crashing if memory is not available.

Can this be fixed?

**Comment by madler** [comment]
Veracode is wrong. The result of `zcalloc` is always checked. `zcalloc` is assigned the the stream structure variable `strm->zalloc`. That is used in the macro `ZALLOC()`. Every result of `ZALLOC()` is checked for `NULL`.
