### ISSUE TITLE
I am not able to build my application when I upgraded zlib from V0.8 to the latest version 1.2.11

### ISSUE THREAD

**Issue by Praveer1981** [madler/zlib#578]
Hi,
We were using very old version of  zlib(0.8) in our application and recently we decided to upgrade it to the latest(1.2.11). 
Now, my build is broken, it looks like there are many files have been deleted.
An Example: earlier we were using inflate_flush() function which was defined in infutil.c file. since this files file does not exist hence our build is broken now.
When I dig deeper, I found that this file was removed from the project since 
https://github.com/madler/zlib/commit/7c2a874e50b871d04fbd19501f7b42cff55e5abc commit.
How can I  solve this issue? 

Do you have any test case  ?

**Comment by madler** [comment]
`inflate_flush()` was an unexposed, internal zlib function, not for use by applications. Right there at the top of `infutil.h` in zlib 0.8, it says:

```
/* WARNING: this file should *not* be used by applications. It is
   part of the implementation of the compression library and is
   subject to change. Applications should only use zlib.h.
 */

```

And, what do you know, it was changed!

You need to rewrite your code to use the interfaces provided in `zlib.h`. Had you done that to begin with, you would have had no problem migrating to the latest version zlib.
