### ISSUE TITLE
Misleading comment on deflateReset

### ISSUE THREAD

**Issue by tstuefe** [madler/zlib#58]
Small issue but potentially misleading:

Comment to deflateReset states:

"The stream will keep the same compression level and any other attributes that may have been set by deflateInit2."

should be changed to

"The stream will keep the same compression level and any other attributes that may have been set by deflateInit2 or changed by deflateParams."

because otherwise one might think the compression level gets activly reset to the value set with deflateInit2, even if deflateParams was called in the meantime.

**Comment by madler** [comment]
Thanks.  I have updated the documentation.
