### ISSUE TITLE
Proper way to use zlib in another project?

### ISSUE THREAD

**Issue by VaasKahnGrim** [madler/zlib#583]
So I'm looking at the library but not seeing any include folder in the repo anywhere(unless I'm overlooking it) Normally when ever I use a library there is one but seems not the case here. I tried checking the repo wiki but thats just an empty home page for it. When I looked at the site it was rather dated in looks so I didn't manage to find any sort of doccumentation either.

**Comment by madler** [comment]
The Makefile installs the header files and object code files in the appropriate include and lib directories on your machine. This is documented in README. Please read the documentation in README, INDEX, and FAQ. The library itself is documented in zlib.h and examples/zlib_how.html.

**Comment by hopeless-programmer-online** [comment]
What is the reason to have the source files in the root?
Why not to move them to `include` + `src`?
