### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by arnavbhate** [madler/zlib#584]
The version of the library built from source does not give me access to any zlib functions.
The version downloaded from the website also does not work as it requires unistd.h which is absent on windows.

**Comment by madler** [comment]
Is that two different issues? What do you mean "does not give me access"? What are you doing and what happens? How are you trying to build it? What version are you using? What platform, operating system, and compiler are you using?

**Comment by arnavbhate** [comment]
In the precompiled version, there is a line
```c
# include <unistd.h>
```
However, this header is unavailable on windows.
If I build it myself using makefile.msc or using cmake, the header no longer has that problem but the compiler, for each zlib function I use, gives an error saying that it was not found. I have tried with clang, GCC and MSVC.

**Comment by madler** [comment]
What is this "precompiled version" you speak of? In any case, it is not part of the zlib distribution, so you would need to report that issue to wherever that thing came from. Not here.

You are starting to provide some scant information about how you built it and are trying to use it. From that, I can only guess that you are simply not telling the linker to use the compiled library and where to find it.

**Comment by arnavbhate** [comment]
The precompiled version available on zlib.net.
I am telling it to use the library.
Let me try building zlib with cmake instead of makefile.msc

**Comment by arnavbhate** [comment]
The version built with cmake links without any error
My program is not working as expected, but it may be a bug on my side rather than with zlib
I tested with clang now I'll test with the others later

**Comment by madler** [comment]
There is no pre-compiled version of zlib on zlib.net.

You seem to not be able to answer any of my questions, such as what version of zlib, platform, compiler, exactly how you are building and attempting to use zlib. I am closing this issue. I recommend that you instead try stackoverflow.com for basic help with compiling and linking.

**Comment by arnavbhate** [comment]
Commandline:
```none
clang src/*.c -Izlib/include -lzlib/lib/zlibstatic.lib -o output.exe
```
Gives the following output:
```none
LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
LINK : warning LNK4217: symbol 'free' defined in 'libucrt.lib(free.obj)' is imported by 'zlibstatic.lib(zutil.obj)' in function 'zcfree'
LINK : warning LNK4217: symbol 'malloc' defined in 'libucrt.lib(malloc.obj)' is imported by 'zlibstatic.lib(zutil.obj)' in function 'zcalloc'
```
However, it does compile.

**Comment by arnavbhate** [comment]
The version I built with CMake is decompressing properly
I think it was just a problem with makefile.msc maybe
