### ISSUE TITLE
Run-Time Check Failure #1 when inflating gzip file

### ISSUE THREAD

**Issue by jzer0** [madler/zlib#587]
Hello,

I am encountering a runtime error when attempting to inflate a gzip file.  This is thrown during the initial call to inflate during the CRC check, specifically:

(inflate.c ln 668):

#ifdef GUNZIP
            if ((state->wrap & 2) && hold == 0x8b1f) {  /* gzip header */
                if (state->wbits == 0)
                    state->wbits = 15;
                state->check = crc32(0L, Z_NULL, 0);
                **CRC2(state->check, hold);** <- runtime error thrown here
                INITBITS();
                state->mode = FLAGS;
                break;

When it reaches this call to CRC2 the following Run-Time error is thrown:

Run-Time Check Failure #1 - A cast to a smaller data type has caused a loss of data.  If this was intentional, you should mask the source of the cast with the appropriate bitmask.  For example:  
	char c = (i & 0xFF);
Changing the code in this way will not affect the quality of the resulting optimized code.

It is possible to continue past this error, and the file is decompressed successfully.  No data is missing as far as I can tell.  The zlib library was built with the Smaller Type Check set to No rather than /RTCc, but in the main project I need to have this check set.  I'm trying to determine where this cast is occurring as I've attempted to use the exact data types for my buffer as is expected during this call, but so far I've had no luck.  Any assistance would be greatly appreciated.

**Comment by madler** [comment]
The truncation is happening on this line of a macro in inflate.c:

            hbuf[0] = (unsigned char)(word); \
 
However this also occurs in subsequent lines for `CRC4`, and I suspect in many places in zlib. It is a perfectly normal, common, and correct usage of C to truncate information when casting. The cast itself _already signals_ the intent of the programmer to do exactly that. There is no need for further masking. Your runtime check will cause lots of correct code to fail for no good reason. You should turn it off.
