### ISSUE TITLE
Z_SOLO: ptrdiff_t guess is wrong on Windows LLP64

### ISSUE THREAD

**Issue by apodtele** [madler/zlib#593]
Compiling ZLib with Z_SOLO on Windows LLP64, MSVC chokes:
```
\freetype\src\gzip\zutil.h(33,17): error C2371: 'ptrdiff_t': redefinition; different basic types (compiling source file ..\..\..\src\gzip\ftgzip.c) [\freetype\builds\windows\vc2010\freetype.vcxproj]
```

We do include <stddef.h> in a wrapper file, which hardly qualifies as other library because it is just a standard typedef. Perhaps _STDDEF_H can be used to verify if it is included already.

**Comment by madler** [comment]
Is "33" supposed to be the line number? What version of zlib are you using? I'm not seeing where this is happening. What is `ftgzip.c`? That's not part of zlib.

**Comment by apodtele** [comment]
That was FreeType issue which resolved itself.
