### ISSUE TITLE
Access of uninitialized field strm->next_in

### ISSUE THREAD

**Issue by ebiggers** [madler/zlib#61]
Running the following program linked to zlib 1.2.8...

```c
#include <zlib.h>

int main(void)
{
	gzclose(gzopen("test.gz", "w"));
}
```

... produces the following output in valgrind:

```
==12682== Conditional jump or move depends on uninitialised value(s)
==12682==    at 0x4E37B1A: deflate (deflate.c:678)
==12682==    by 0x4E4742F: gz_comp (gzwrite.c:115)
==12682==    by 0x4E47E32: gzclose_w (gzwrite.c:562)
==12682==    by 0x4E4537C: gzclose (gzclose.c:21)
==12682==    by 0x400607: main (in /home/e/test/zlib/write_empty)
```

This occurs because ``deflate()`` on line 679 of ``deflate.c`` performs the following check:

``(strm->next_in == Z_NULL && strm->avail_in != 0)``

which accesses the field ``next_in`` *before* ``avail_in``, even though ``gz_reset()`` only initializes ``avail_in``, not ``next_in``.

This is unlikely to make a difference, but it is still undefined behavior.  This check should be changed to

``(strm->avail_in != 0 && strm->next_in == Z_NULL)``

**Comment by madler** [comment]
Thank you for the report.  I have pushed a commit to fix this on both sides.
