### ISSUE TITLE
Odd bug with zlib 1.2.12 configure on macOS with clang

### ISSUE THREAD

**Issue by mathomp4** [madler/zlib#615]
First, my particulars:

* OS: macOS 11.6.5
* C Compiler: clang 13.0.0
* zlib version: 1.2.12

So this is a weird one. I maintain a [set of libraries](https://github.com/GEOS-ESM/ESMA-Baselibs) for an earth system model and today I was doing a "Let's look for new updates" and saw the new zlib. 🎉 

I updated my submodule and found, weirdly, that curl wouldn't link to zlib. I mean, it was built, but it just didn't like it. I did some pondering and realized that on my MacBook Pro where I was building zlib with clang, I was getting out `libz.so` *not* `libz.dylib` as it should have been. I went back to my last build and I did get dylib there.

So, I did some "add print statements" debugging and I found that this somewhat-changed-in-1.2.12 code:
https://github.com/madler/zlib/blob/21767c654d31d2dccdde4330529775c6c5fd5389/configure#L170-L191
seemed to be the culprit.

The issue is on my system `CC=/usr/bin/clang` so that means in this this test is skipped:
```sh
if test -z "$CC"; then
  echo Checking for ${CROSS_PREFIX}gcc... | tee -a configure.log
  if ${CROSS_PREFIX}gcc -v >/dev/null 2>&1; then
    cc=${CROSS_PREFIX}gcc
  else
    cc=${CROSS_PREFIX}cc
  fi
fi
```
So we go to this:
```sh
case "$cc" in
  *gcc*) gcc=1 ;;
  *clang*) gcc=1 ;;
esac
case `$cc -v 2>&1` in
  *gcc*) gcc=1 ;;
  *clang*) gcc=1 ;;
esac
```
The problem is, since it skipped that `test -z $CC` test above, `cc` is now not defined. So then `gcc` is not defined, and I never get here:
https://github.com/madler/zlib/blob/21767c654d31d2dccdde4330529775c6c5fd5389/configure#L249-L250
where the `shared_ext` is set to `.dylib` because the `else` part of that if-block has no `Darwin` case.

For now I have a workaround (`export cc=$CC`) when I build zlib, but I'm hoping someone here can make a more permanent fix.

**Comment by madler** [comment]
See if this commit helps: https://github.com/madler/zlib/commit/05796d3d8d5546cf1b4dfe2cd72ab746afae505d

**Comment by mathomp4** [comment]
@madler Soooort of? I mean, I get dylibs, but I now get:
```
libz.1.2.12.1-motley.dylib
```
instead of:
```
libz.1.2.12.dylib
```

I'm a bit baffled as to where "motley" is coming from!

**Comment by madler** [comment]
If that commit resolves this issue, then you can close it.

**Comment by mathomp4** [comment]
It solves for me. Closing!
