### ISSUE TITLE
Flyway migrations CRC32 checksum different after upgrading to 1.2.12 (from 1.2.11)

### ISSUE THREAD

**Issue by nmapx** [madler/zlib#618]
There are multiple projects that rely on this library. In my case it is `Flyway` migrations that is using it to calculate checksum. 2 days ago it started producing different values for CRC32 what caused app crash on startup. It seems your recent release is not backwards compatible and shouldn't be a patch. Please verify it.

**Comment by nmapx** [comment]
Flyway is using following code to calculate CRC32
```
    private static int calculateChecksumForResource(LoadableResource resource) {
        final CRC32 crc32 = new CRC32();

        BufferedReader bufferedReader = null;
        try {
            bufferedReader = new BufferedReader(resource.read(), 4096);
            String line = bufferedReader.readLine();

            if (line != null) {
                line = BomFilter.FilterBomFromString(line);
                do {
                    //noinspection Since15
                    crc32.update(line.getBytes(StandardCharsets.UTF_8));
                } while ((line = bufferedReader.readLine()) != null);
            }
        } catch (IOException e) {
            throw new FlywayException("Unable to calculate checksum of " + resource.getFilename() + "\r\n" + e.getMessage(), e);
        } finally {
            IOUtils.close(bufferedReader);
        }

        return (int) crc32.getValue();
    }
```

**Comment by madler** [comment]
This commit should remedy the incorrect CRC inputs: https://github.com/madler/zlib/commit/ec3df00224d4b396e2ac6586ab5d25f673caa4c2 .

**Comment by nmapx** [comment]
It would require some effort to test it on my side before you actually release it. I trust you if you are confident enough. If you need any more details in order to test it locally I can provide it, just tell me what you need.

**Comment by madler** [comment]
What code is saying "Migration checksum mismatch"?

**Comment by nmapx** [comment]
https://github.com/flyway/flyway/blob/21519baaf861ff06d0b5aa87271793707964edf5/flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoImpl.java#L394

This one i guess. If you follow the `createMismatchMessage` method you will find this
https://github.com/flyway/flyway/blob/21519baaf861ff06d0b5aa87271793707964edf5/flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoImpl.java#L437

and

https://github.com/flyway/flyway/blob/21519baaf861ff06d0b5aa87271793707964edf5/flyway-core/src/main/java/org/flywaydb/core/internal/info/MigrationInfoImpl.java#L403

**Comment by nmapx** [comment]
Any progress here?

**Comment by phiresky** [comment]
This also seems to affect google closure compiler and thus breaks emscripten:

```
$ google-closure-compiler
java.util.zip.ZipException: invalid entry CRC (expected 0x4e1f14a4 but got 0xb1e0eb5b)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:410)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:199)
	at java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:143)
	at java.util.zip.ZipInputStream.getNextEntry(ZipInputStream.java:121)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.getBuiltinExterns(AbstractCommandLineRunner.java:481)
	at com.google.javascript.jscomp.CommandLineRunner.createExterns(CommandLineRunner.java:2083)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.doRun(AbstractCommandLineRunner.java:1168)
	at com.google.javascript.jscomp.AbstractCommandLineRunner.run(AbstractCommandLineRunner.java:532)
	at com.google.javascript.jscomp.CommandLineRunner.main(CommandLineRunner.java:2241)
```

**Comment by phiresky** [comment]
I can confirm that installing zlib from the develop branch fixes this issue and allows me to start google-closure-compiler. 

It would be great if you could release a new version since this seems to affect multiple unrelated things.

**Comment by madler** [comment]
Thank you for the verification. There will be a new release. However all instances of zlib 1.2.12 impacting CRC calculations should be reported as bugs in those applications. The problem is caused by invalid CRC-32 values being giving to zlib's CRC function.

**Comment by demitriusbelai** [comment]
@madler I am not a C expert but I have taken a look at the [java implementation](https://github.com/openjdk/jdk/blob/master/src/java.base/share/native/libzip/CRC32.c) and I do not realise the problem. There is no `crc32(0L, Z_NULL, 0);` but it will [just return 0](https://github.com/madler/zlib/blob/ec3df00224d4b396e2ac6586ab5d25f673caa4c2/crc32.c#L626) and 0 is the default inital value for integer in Java. The int in Java (jint in C code) is a 32 bits signed integer and it is [converted to long signed](https://github.com/openjdk/jdk/blob/4cd0921cf6075cedd710e96d939df3df6c007d74/src/java.base/share/classes/java/util/zip/CRC32.java#L130) at the end of crc32 computation. Using signed 32 bits integer can be a problem?

I do not know why it occur only on my computer with i7 870. It do not occur on my i5 7600k. Can it be a CPU related behaviour?

Thank you in advance.

**Comment by LanceAndersen** [comment]
> Thank you for the verification. There will be a new release. However all instances of zlib 1.2.12 impacting CRC calculations should be reported as bugs in those applications. The problem is caused by invalid CRC-32 values being giving to zlib's CRC function.

Hi Mark,

Wanted to ask, based on your comment above, do you have a timeframe that you were thinking for a patch release to 1.2.12 or perhaps a 1.2.13 release?
