### ISSUE TITLE
Minizip Version mismatch in Zlib 1.2.12

### ISSUE THREAD

**Issue by rupalimittal** [madler/zlib#636]
Hello Team
Please help me with below question:
1.  why minizip related files are not updated to 1.2.12 version inside the contrib subfolder.
For instance , i can see that miniunz.c is having "Version 1.2.0, September 16th, 2017 " as well available but in zlib 1.2.12 ,it is kept as  "Version 1.1, February 14h, 2010"(You can find this in miniunz.c file in topmost comment)
Is it just the comment and we can ignore the version mentioned in the comment ?

**Comment by Neustradamus** [comment]
@rupalimittal: Because there is a fork, a lot of people were lost, now called minizip-ng:
- https://github.com/zlib-ng/minizip-ng

Original from @gvollant into zlib: https://github.com/madler/zlib/search?q=February+14h
I think it is the moment to update this date!

**Comment by nmoinvaz** [comment]
AFAIK minizip has its own version number and it is not related to zlib version.

**Comment by uis246** [comment]
What about this one: https://chromium.googlesource.com/external/github.com/nmoinvaz/minizip/+/refs/heads/1.2/README.md

Unzipping from memory is useful

**Comment by madler** [comment]
Yes, minizip has its own version number.
