### ISSUE TITLE
What is the principle of  multiplication of D-normalized polynomials ?

### ISSUE THREAD

**Issue by minchai23** [madler/zlib#641]
I'm studing the principle of crc from  [crc-doc.1.0.pdf](https://github.com/madler/zlib/blob/master/doc/crc-doc.1.0.pdf)
I can't understand:
```c
bPowX[k+1] = (bPowX[k] >> 1) ^ P    // in Listing 1: Multiplication of normalized polynomials

//XpowN returns (x**N mod P(x))
result ^= Multiply(temp, Multiply(m, XpowN(d)));      // in Listing 2: Multiplication of unnormalized polynomial
```
why XOR P ?
why mod P(x) ?

**Comment by madler** [comment]
This is not the place to ask that. Ask on cs.stackexchange.com. Far more people will see your question there, and more could benefit from the answer.
