### ISSUE TITLE
[1.2.12] missing "ZLIB_1.2.x" breaks other applications such as lmod

### ISSUE THREAD

**Issue by rsdmse** [madler/zlib#642]
I built 1.2.12 with GCC 11.2.0 on our cluster as I did before with 1.2.11. The build itself was successful. However, when I run any module command such as `module list` I get an error:
```
/usr/bin/lua: error loading module 'tcl2lua' from file '/usr/share/lmod/lmod/libexec/../lib/tcl2lua.so':
	/apps/software/standard/compiler/gcc/11.2.0/zlib/1.2.12/lib/libz.so.1: version `ZLIB_1.2.2' not found (required by /lib64/libtcl8.6.so)
```
When I run `strings` on the `.so` file, I don't see any `ZLIB_*`. For 1.2.11, on the other hand, I would see a long list like
```
ZLIB_1.2.0
ZLIB_1.2.0.2
ZLIB_1.2.0.8
ZLIB_1.2.2
ZLIB_1.2.2.3
<snip>
```
I wonder what has changed in this version and how can I fix it?

(Just to clarify, we didn't build lmod with a zlib module. It's just picking up the first `libz.so.1` in `LD_LIBRARY_PATH`.)

**Comment by jhdub23** [comment]
Thank you @rjdave.  We just ran into this problem and your solution fixed the problem.  The patch file:
[configure.patch.txt](https://github.com/madler/zlib/files/9679444/configure.patch.txt)

**Comment by madler** [comment]
Fix incorporated.
