### ISSUE TITLE
(RESOLVED) Zlib-1.2.12 fails to Make

### ISSUE THREAD

**Issue by ghost** [madler/zlib#646]
Not sure what I am doing wrong.  I have done this process from the .Tar file hundreds of times with 1.2.11.  I have exported my terminal output in the attached file.  Maybe someone can see what is going on

[zlib-1.2.12 error.txt](https://github.com/madler/zlib/files/8602447/zlib-1.2.12.error.txt)
?

**Comment by Mr-Clam** [comment]
Why is it compiling with `-DPIC` instead of `-fPIC`?

**Comment by whatheway** [comment]
> Why is it compiling with `-DPIC` instead of `-fPIC`?

I have no idea, I'm doing the same process from 1.2.11 and not changing any compile code.

**Comment by Mr-Clam** [comment]
I just tried reproducing this on my Mac and it passed both parameters, so for some reason it's not setting one of them for you.  You can share more info about your environment?  Starting with Linux distribution, compiler version and configure.log?

**Comment by whatheway** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal

gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.

will@will-XPS-8940:~$ cd zlib-1.2.12/
will@will-XPS-8940:~/zlib-1.2.12$ export CC=gcc
will@will-XPS-8940:~/zlib-1.2.12$ export CXX=g++
will@will-XPS-8940:~/zlib-1.2.12$ export FC=gfortran
will@will-XPS-8940:~/zlib-1.2.12$ export F77=gfortran
will@will-XPS-8940:~/zlib-1.2.12$ ./configure --prefix=$HOME/
Checking for shared library support...
Building shared library libz.so.1.2.12 with gcc.
Checking for size_t... Yes.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for stdarg.h... Yes.
Checking whether to use vs[n]printf() or s[n]printf()... using vs[n]printf().
Checking for vsnprintf() in stdio.h... Yes.
Checking for return value of vsnprintf()... Yes.
will@will-XPS-8940:~/zlib-1.2.12$ make
gcc -O -D_LARGEFILE64_SOURCE=1 -I. -c -o example.o test/example.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o adler32.o adler32.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o crc32.o crc32.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o deflate.o deflate.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o infback.o infback.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o inffast.o inffast.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o inflate.o inflate.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o inftrees.o inftrees.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o trees.o trees.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o zutil.o zutil.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o compress.o compress.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o uncompr.o uncompr.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o gzclose.o gzclose.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o gzlib.o gzlib.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o gzread.o gzread.c
gcc -O -D_LARGEFILE64_SOURCE=1  -c -o gzwrite.o gzwrite.c
ar rc libz.a adler32.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o zutil.o compress.o uncompr.o gzclose.o gzlib.o gzread.o gzwrite.o 
gcc -O -D_LARGEFILE64_SOURCE=1 -o example example.o -L. libz.a
gcc -O -D_LARGEFILE64_SOURCE=1 -I. -c -o minigzip.o test/minigzip.c
gcc -O -D_LARGEFILE64_SOURCE=1 -o minigzip minigzip.o -L. libz.a
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/adler32.o adler32.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/crc32.o crc32.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/deflate.o deflate.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/infback.o infback.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/inffast.o inffast.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/inflate.o inflate.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/inftrees.o inftrees.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/trees.o trees.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/zutil.o zutil.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/compress.o compress.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/uncompr.o uncompr.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/gzclose.o gzclose.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/gzlib.o gzlib.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/gzread.o gzread.c
gcc -O -D_LARGEFILE64_SOURCE=1  -DPIC -c -o objs/gzwrite.o gzwrite.c
cc -shared -O -D_LARGEFILE64_SOURCE=1 -o libz.so.1.2.12 adler32.lo crc32.lo deflate.lo infback.lo inffast.lo inflate.lo inftrees.lo trees.lo zutil.lo compress.lo uncompr.lo gzclose.lo gzlib.lo gzread.lo gzwrite.lo  -lc 
/bin/ld: deflate.lo: relocation R_X86_64_PC32 against symbol `_length_code' can not be used when making a shared object; recompile with -fPIC
/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:282: libz.so.1.2.12] Error 1
will@will-XPS-8940:~/zlib-1.2.12$

**Comment by whatheway** [comment]
The only time it works is when I build it within the $HOME directory.
If I try to install zlib-1.2.12 in a sub-folder it fails every time.

This is the code I'm using when it fails


export HOME=`cd;pwd`
mkdir $HOME/WRF
cd $HOME/WRF
mkdir Downloads
mkdir Libs
mkdir Libs/grib2
mkdir Libs/NETCDF
mkdir Libs/MPICH

cd Downloads
wget -c https://github.com/madler/zlib/archive/refs/tags/v1.2.12.tar.gz
export DIR=$HOME/WRF/Libs
export CC=gcc
export CXX=g++
export FC=gfortran
export F77=gfortran

cd $HOME/WRF/Downloads
tar -xvzf v1.2.12.tar.gz
cd zlib-1.2.12/
./configure --prefix=$DIR/grib2
make

**Comment by Mr-Clam** [comment]
There's something about setting $CC and $CXX that trips up the configure script.  It even causes it to use different optimisation flags.  Can you unset these?

Alternatively, can you use Cmake instead?  Replace the configure and make steps from your repro case with:
```
cmake -B build_release -S . -DCMAKE_INSTALL_PREFIX=$DIR/grib2
cmake --build build_release/
cmake --install build_release/
```

This doesn't fix the problem, but rather it's just a workaround.  Maybe somebody else enjoys debugging these GNU configure scripts.

**Comment by whatheway** [comment]
Going to leave this open for now, unless repo author wants to close it.
