### ISSUE TITLE
thread safety for zalloc/zfree

### ISSUE THREAD

**Issue by qdztxc** [madler/zlib#651]
In the zlib manual it says that "If zlib is used in a multi-threaded application, zalloc and zfree must be thread safe. In that case, zlib is thread-safe. ".

My scenario is that I have three threads (let me call them A, B and C).
Each thread uses individual z_stream and call inflateInit2/inflate/inflateEnd within its own thread function. Each z_stream uses different memory pool for zalloc/zfree/opaque. 

I this case, shall my customized zalloc/zfree to be thread-safe?
I don't have race condition in my code but I'm not sure whether is it thread safe for zlib internals.

Thanks and regards.

**Comment by madler** [comment]
Yes.
