### ISSUE TITLE
Better control/API over runtime logging from zlib?

### ISSUE THREAD

**Issue by jaikiran** [madler/zlib#655]
zlib has the ability to log runtime log messages. These log messages are only logged if a compile/build time flag is enabled `ZLIB_DEBUG`. This then means that it all depends on who/how the library is built for logging to be available at runtime.

Recently, we have been trying to solve an issue in zlib that's shipped in macos aarch64 systems. The zlib shipped in that system wasn't built with `ZLIB_DEBUG` enabled (we verified it by calling `zlibCompileFlags()` at runtime and checking its output as noted in https://github.com/madler/zlib/blob/master/zlib.h#L1185). This effectively means that to be able to investigate the issue we need to rebuild that library with `ZLIB_DEBUG`, which isn't feasible given the lack of access to the actual source and the actual build command/configurations that were used to build it originally.

Would it be feasible to introduce a way where this crucial logging can be enabled at runtime without having to rebuild the library? Perhaps an explicit API on the zlib library which enables the logging or maybe some runtime environment variable which enables it? I don't know if there's a precedent to allow environment variables to enable things like this, so if that's not a possibility then an API that the library's client is expected to call, should be fine perhaps?

**Comment by madler** [comment]
What is the issue in the macOS zlib?

**Comment by madler** [comment]
I currently have no plans to incorporate debug logging in every build of zlib. By the way, it might not help in your case anyway, as Apple appears to have their own, modified version of zlib.

**Comment by jaikiran** [comment]
Hello Mark,

> What is the issue in the macOS zlib?

The version of zlib shipped in macos aarch64 systems runs into very odd intermittent issues when inflating an existing zip content. This is reproducible in Java applications and the details have been noted in https://bugs.openjdk.org/browse/JDK-8282954

**Comment by madler** [comment]
Interesting. Have you continued to run your test with new versions of macOS? If so, are you still seeing the intermittent failure with 12.6?

What is the probability of the intermittent failure?

**Comment by jaikiran** [comment]
Hello Mark,

> Interesting. Have you continued to run your test with new versions of macOS? If so, are you still seeing the intermittent failure with 12.6? 

I remember testing it with a 12.5 Beta version and the Apple issue that we have filed is still open, so this isn't yet fixed. I can run some more tests later next week to be certain (but I'm sure it's still an issue even in 12.6).

> (I can't run the test due to some internal reference: `import jdk.internal.org.objectweb.asm.*;`. 

The linked JDK issue has a script that includes the necessary --add-export options while launching the `java` command. I will review it again on Monday to see if that command needs an update and if so, I will update it with the latest script.


> Also if the JDK now uses a zlib built from source, as opposed to the zlib that comes with macOS, perhaps that's the JDK I have.)

The issue is reproducible only on aarch64 of macos. So you will need an aarch64 system to test this (a Mac M1 should do). Furthermore, we (the JDK) switched to using a bundled version on aarch64 of macos, starting Java 19, to workaround this issue. So if you are using Java 19, then yes you won't be able to reproduce this.

If there's interest and if you have the necessary setup to build Java from source, then I can provide precise instructions on how to use the system provided zlib and build the JDK instead of using the bundled version - let me know.

Looking at https://bugs.openjdk.org/browse/JDK-8286623, the issue where we started using bundled zlib, I don't see any backports of that change to Java 17, so I think using Java 17 to reproduce this would be another option.

> 
> What is the probability of the intermittent failure?

Our experiments have shown that it's 100% guaranteed that it will be reproduced. The duration it takes to reproduce however is not fixed. Sometimes it takes a few hours and some times a day or two.

When I was investigating this I had written down some notes on what seems to be happening (or rather a pattern that is common in all these failures). I am not an expert on zlib so I couldn't take that theory to conclusion and without the exact source and build instructions to build the version of zlib that macos aarch64 ships, it was difficult to debug this further. Perhaps that pattern that I noticed might give you some hints? I will update this issue with my notes shortly (I don't have it on this current setup).

**Comment by madler** [comment]
Thank you for the detailed response! I look forward to your notes.

Yes, I have two M1 machines. Also I have JDK 18.0.1.1 installed on both of them! So I'm in luck.

By probability, I mean the probability of getting the error when decompressing the file. That would be related to the variable time you note that it takes to reproduce the issue. How many decompressions of the jmod file, on average, did it take to run into the failure? One divided by that average is an estimate of the probability. Or even one over the number of decompressions from a single test is an estimate. It looks like you write the number to `status.txt`.

Did the error always occur on the same entry in the jmod file? There are 1813 entries in that file (`jdk.localedata.jmod`), of which 1809 end in `.class`, and so are processed in your loop.

**Comment by madler** [comment]
Ok, I got it running. However I'm not sure it's working right. It seems to fail within minutes, the longest being about 30 minutes, whereas you indicated hours or days. So far it has stopped after 348, 158, 915, 3615, and 615 iterations. Also the exception cause and trace can be different. Four times it was this:

```
Exception in thread "main" java.lang.IllegalArgumentException
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:290)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:208)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:194)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:315)
	at StripDebugJmodWithZip.main(StripDebugJmodWithZip.java:31)
```

But once it was this:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 10438 out of bounds for length 8435
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:247)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:208)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:194)
	at java.base/jdk.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:315)
	at StripDebugJmodWithZip.main(StripDebugJmodWithZip.java:31)
```

Were you seeing the same or similar signatures? What is happening at ClassReader.java:290 and ClassReader.java:247?

By the way, it stopped at five different entries in the jmod file the five times. So it's not something particular about the compressed data that's hanging it up.

**Comment by madler** [comment]
While it only takes on the order of minutes to fail on my laptop (an M1 Max), the first failure took 7.5 hours on my desktop (an M1 Ultra), after over 50,000 runs. So maybe this is like your experience, where there can be considerable variation depending on the processor. p(on Max) ~= 0.001, p(on Ultra) ~= 0.00002.

**Comment by jaikiran** [comment]
Hello Mark, sorry I didn't have access to the necessary setup to reply sooner to some of your recent questions. 

> How many decompressions of the jmod file, on average, did it take to run into the failure? One divided by that average is an estimate of the probability. 

I didn't compute that number. As you noticed, I write out to `status.txt` the number of times `java` program (that reads the jmod/zip file) was launched before the program ran into a failure. The numbers I saw in that file varied wildly. Sometimes it failed after 1000 odd launches, sometimes 6K, sometimes even more than 10K. Given the unpredictability on the number of `java` launches, I didn't focus on this area to try and find a pattern.

> Did the error always occur on the same entry in the jmod file? 

No, there wasn't a specific pattern (actually there was, but I will explain that detail later in a separate comment). The entries that failed varied across runs.

> There are 1813 entries in that file (jdk.localedata.jmod), of which 1809 end in .class, and so are processed in your loop.

That is correct.

> Ok, I got it running. However I'm not sure it's working right. It seems to fail within minutes, the longest being about 30 minutes, whereas you indicated hours or days. So far it has stopped after 348, 158, 915, 3615, and 615 iterations. Also the exception cause and trace can be different. Four times it was this: `java.lang.IllegalArgumentException` But once it was this: `java.lang.ArrayIndexOutOfBoundsException: Index 10438 out of bounds for length 8435`

This is "good" news. You seem to have found a system where this is reproducible much more quickly. The ones I had access to were CI systems and it took longer there. As for the different exception types that you see, that's the result of the same root cause issue.

> Were you seeing the same or similar signatures? What is happening at ClassReader.java:290 and ClassReader.java:247?

What that loop in the test/reproducer program does is - find an entry for .class file within the zip and reads its content (i.e. bytes from the inflated entry). These bytes are then (without any modification) passed on to a class file parser (which understands the class file structure bytes) to parse a Class data out of it. The parser notices that the byte content is "corrupt" i.e. it has been fed some byte array which doesn't represent a valid class data. Depending on which byte index in the array was corrupt, the parser can throw different exception types. This all boils down to inflater (via zlib) returning "incorrect" inflated data for an entry. If I wasn't clear previously, the zlib calls itself don't error out. The zlib calls from within Java all complete without errors, it's just that the inflated data for some entry ends up with corrupt/incorrect content which then manifests as issues like the one above.


> By the way, it stopped at five different entries in the jmod file the five times. So it's not something particular about the compressed data that's hanging it up.

You are right and our experiments have shown that it isn't related to a specific entry (there's a pattern though, which I explain later)

**Comment by jaikiran** [comment]
> > While it only takes on the order of minutes to fail on my laptop (an M1 Max), the first failure took 7.5 hours on my desktop (an M1 Ultra), after over 50,000 runs. So maybe this is in fact like your experience, where there can be considerable variation depending on the processor.

We have noticed the variation even on the same setup. But that was a CI (shared) setup, so things like load from other processes might have played a role in context of how long it takes to fail.

**Comment by jaikiran** [comment]
> Thank you for the detailed response! I look forward to your notes.

I went back to my notes and here's some relevant details.

In that test program, we inflate each deflated entry from that jmod/zip file. Let's consider one such deflated entry of size `D1`. `java.util.zip.InflaterInputStream` in combination with its backing `java.util.zip.Inflater` instance has the following flow (at a high level):
1. Construct an (Java) in-memory byte array `IB` of the deflated content of D1 size
2. Construct an (Java) byte array `XB` of size 8192, which acts as the output array into which zlib will inflate the data
3. Do a JNI call which ultimately will trigger a call to zlib's inflate method, which looks like:

```
ret = inflate(strm, Z_PARTIAL_FLUSH);

```

the passed `strm` instance is setup such that `strm->next_in` will point to the `IB` byte array and `strm->avail_in` will be `D1` (the entire size of the deflated content). Similarly `strm->next_out` is set to point to `XB` and `strm->avail_out` to the size of `XB`, which is 8192.
4. zlib inflates the data and returns back a `ret` result which contains details like how much content was read from `IB` and how much written into `XB` and detail like whether the inflater is "finished" (i.e. all data is inflated).
5. The inflated data in `XB` is then stored in a Java in-memory temporary list of byte array, which is then "accumulated" to form the completed inflated content.
6. Java then checks if the inflater is "finished" and if it isn't then it first creates a new output byte array of 8192 size and calls the zlib's `inflate(strm, Z_PARTIAL_FLUSH);` again. This time it sets up the `strm->next_in` such that it has advanced the position by the number of `read` bytes from the previous call to zlib's `inflate`. Similarly, it adjusts the `strm->avail_in`. The `strm->next_out` is set to point to the new byte array `XB` and `strm->avail_out` to the size of new byte array `XB`, which is 8192.
7. Step 4 through 6 is repeated till the inflater is "finished" after the call to zlib's inflate.
8. Once "finished", all this accumulated inflated bytes (which is held on the Java side) is returned as the final inflated content for that entry.

The one consistent pattern that has been observed in all these failures is that the issue is reproducible only if a entry requires more than one call to zlib's inflate. i.e. the entry cannot be inflated in one single output buffer of size 8192. Various experiments have been run to ensure that there's no bug in the Java side or the JNI side when it comes to the byte array management of both the input and output arrays, both in terms of contents and in terms of the values that are set for `strm->next_in`, `strm->avail_in`, `strm->next_out` and `strm->avail_out`. Data (actual byte content) collected from successful and failed runs of a particular entry within the jmod/zip file has been compared to make sure that the call to `inflate(strm, Z_PARTIAL_FLUSH);` has the exact same byte content and positions.

Furthermore, the returned `ret` has been analyzed for both successful runs and failed runs for the same byte array content. Their values are consistent i.e. the failing case doesn't differ from the successful case which implies that the `read` count `write` count, the `strm->avail_in` and `strm->avail_out` after the inflate call have the exact same value. What however differs is the content that is written out in the `strm->next_out` (i.e. the output byte array).

I have no previous experience with zlib or its API, but while investigating this, I happened to read the code comment about how inflate() works https://github.com/madler/zlib/blob/develop/inflate.c#L543. Based on all the data collected and analyzed, this specific section https://github.com/madler/zlib/blob/develop/inflate.c#L601 in that code comment, appears relevant to the issue at hand:

> A state may also return if there is not enough output space available to complete that state.  Those states are copying stored data, writing a literal byte, and copying a matching string.

For some entry the calls notices that the output buffer size of 8192 isn't enough, so it writes out to the output buffer whatever has been inflated so far and then internally maintains the other states noted in that comment. I suspect it ends up either copying wrong data or storing incorrect state or perhaps even using this stored data incorrectly in a subsequent call to inflate(). I don't have any theory why it would run into this kind of issue only occasionally and that too against different entries in different runs.

As I noted above, one thing is certain (from the data collected and numerous runs) - entries in that jmod/zip file, that can be inflated in only on call to inflate() with an output buffer size of 8192, never run into this issue. Do note that for entries that fail, it needn't necessarily be the second call to inflate() that might fail. I haven't seen any pattern there - it could the second, third or any other subsequent call that might fail for an entry which can't be inflated in one call to inflate().

Also note that macos appears to be using their own version of zlib, so I'm unsure what has changed, if anything. We have never been able to reproduce this with your repo's zlib. Apple's documentation suggests that the zlib source for macos resides at https://github.com/apple-oss-distributions/zlib. Comparing that code with your repo shown no relevant difference at all. So that brings into question the build/compile time configurations that Apple might have used for macos aarch64. I don't have any insight on that and haven't received any response from Apple into this issue.

I hope some of these details are useful. Without access to the right source and build instructions and with no deeper knowledge of zlib and lack of runtime log (Apple doesn't build with zlib debug logs enabled), I have hit a dead end. I'm glad that at least you now have a way to reproduce this. Please feel free to ask any further questions. I will try to get back with the necessary details. Thank you for your time and interest on this.

**Comment by madler** [comment]
Can you point me to the code making the zlib calls?

**Comment by madler** [comment]
I don't see how this is could get past the CRC check.

**Comment by jaikiran** [comment]
Hello Mark,

> I don't see how this is could get past the CRC check.

Java by default disables CRC check. It instantiates a (Java) Inflater with `nowrap` true here https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/zip/ZipFile.java#L734 which as per the javadoc of Inflater https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/zip/Inflater.java#L122:
```
If the parameter 'nowrap' is true then
* the ZLIB header and checksum fields will not be used. This provides
* compatibility with the compression format used by both GZIP and PKZIP.
```
(it ultimately leads to the zlib inflaterinit2 call with second param value as `-MAX_WBITS` https://github.com/openjdk/jdk/blob/master/src/java.base/share/native/libzip/Inflater.c#L67)

> Can you point me to the code making the zlib calls?

The calls to zlib happen from within the JNI layer of Java from this file here https://github.com/openjdk/jdk/blob/master/src/java.base/share/native/libzip/Inflater.c. The Java side code (in `java.util.zip.Inflater`) invokes the JDK's JNI function. The function of interest in the context of this issue is `Java_java_util_zip_Inflater_inflateBytesBytes` here https://github.com/openjdk/jdk/blob/master/src/java.base/share/native/libzip/Inflater.c#L186. It internally calls `doInflate` (which resides in the same file) which then calls the zlib's inflate https://github.com/openjdk/jdk/blob/master/src/java.base/share/native/libzip/Inflater.c#L140

**Comment by madler** [comment]
No, I mean the check against the CRC in the zip file. It would be done in the Java zip code.

**Comment by madler** [comment]
![facepalm-statue](https://user-images.githubusercontent.com/240717/195643423-89c5d45c-b9af-4c78-94c5-a5cee6cf1fb2.jpg)
