### ISSUE TITLE
Error: incorrect header check, with high level of concurrency 

### ISSUE THREAD

**Issue by atulrokade** [madler/zlib#658]
I am getting following error 

error: Error -3 while decompressing data: incorrect header check

is zlib thread safe with high level of concurrency. as per documentation it is thread safe but is it greenlets safe as well ?

**Comment by madler** [comment]
I had to google "greenlets", and I don't see how there would be a concurrency problem with zlib. However I can't speak to how zlib was integrated into the Python library. I recommend a question on stackoverflow with much more information about what you're trying to do and what problem you're running into.
