### ISSUE TITLE
crc32_combine with len2==0

### ISSUE THREAD

**Issue by cmm** [madler/zlib#659]
Prior to 1.2.12, `crc32_combine()` had an explicit check for zero `len2` argument (in which case it returned `crc1`).
1.2.12 does not check any more, and naturally its result when called with zero `len2`, well, at least not necessarily equals `crc1`.

I realize that `len2==0` is considered a degenerate case, but it is not explicitly illegal, so this is an undocumented behavioral change.

**Comment by madler** [comment]
If `len2` is zero, then `crc2` must be zero. The CRC-32 of a zero-length message is zero. Given that, the result is `crc1`. If `crc2` is not zero in this case, then that is a bug in the application.
