### ISSUE TITLE
TRYFREE macro should be used here

### ISSUE THREAD

**Issue by minchai23** [madler/zlib#669]
```c
// zip.c

// Line 1136
zi->ci.central_header = (char*)ALLOC((uInt)zi->ci.size_centralheader + zi->ci.size_centralExtraFree);

// Line 1700
free(zi->ci.central_header);  
```
ALLOC ->  malloc   **OR**   free -> TRYFREE?

**Comment by fredgan** [comment]
Yes, `free` should be replaced with `TRYFREE` !

**Comment by madler** [comment]
I will leave it to Gilles to update minizip. For now, this change would inconsequential anyway, since `free()` is specified to behave properly and do nothing with a `NULL` argument.
