### ISSUE TITLE
Issue with _LARGEFILE64_SOURCE test

### ISSUE THREAD

**Issue by hmaarrfk** [madler/zlib#674]
On windows and LLVM (clang) it seems that `_LARGEFILE64_SOURCE` is defined but the system doesn't have unistd.h

https://github.com/madler/zlib/blob/master/zconf.h.in#L474

I seem to be getting the same error as 
https://github.com/madler/zlib/issues/584

My build are available for review in:
- https://github.com/conda-forge/ffmpeg-feedstock/pull/126
- https://github.com/conda-forge/ffmpeg-feedstock/pull/148

zlib was built in https://github.com/conda-forge/zlib-feedstock/blob/main/recipe/bld.bat with visual studio.

**Comment by madler** [comment]
Thank you for the report. It will be fixed to not do that if `_WIN32` is defined.

**Comment by hmaarrfk** [comment]
Thank you for acknowledging the issue.

Is it ok to leave it open until the issue is fixed in the source? otherwise, it is really difficult for us downstream to track.

**Comment by madler** [comment]
If you consider the develop branch to be "the source", then it's there.

**Comment by hmaarrfk** [comment]
Sorry, I scanned through PRs and didn't see anything merged recently so I was confused.

I understand you pushed this directly to the branch.
https://github.com/madler/zlib/commit/19f8551627d2a89b910d961fc9c7f626f3af7b21

Thanks!
