### ISSUE TITLE
Missing Z_PREFIX for `crc32_combine` functions

### ISSUE THREAD

**Issue by alfonso-soto** [madler/zlib#676]
These 3 functions:
```
crc32_combine_gen64
crc32_combine_gen
crc32_combine_op
```
Are not present on the zconf.h file under the definition Z_PREFIX. This will trigger an error of multiple definitions for these 3 symbols if two Zlib libraries are linked even if one of them has been compiled with -DZ_PREFIX

**Comment by madler** [comment]
Fixed.
