### ISSUE TITLE
What's the reason of Unknown 3rd party lib zlib?

### ISSUE THREAD

**Issue by okayabc** [madler/zlib#679]
When i integrate zlib2.1.12 to mysql source to replace origin zlib folder(version is 2.1.11),  and cmake, it reports the following error:
CMake Error at cmake/libutils.cmake:343 (MESSAGE):
  Unknown 3rd party lib zlib
Call Stack (most recent call first):
  libmysql/CMakeLists.txt:277 (MERGE_CONVENIENCE_LIBRARIES)

**Comment by fluesvamp** [comment]
MySQL devs may have modified the code for the specific purposes of the build and/or use of the bundled code.

That being said this is not the MySQL Forum (where issues are tracked), so I would at this point of time closing.

**Comment by okayabc** [comment]
Yes, MySQL has modified zlib. I should do it  according to mysql's requirement, thanks!
