### ISSUE TITLE
Incorrect build flag (-DPIC) in Makefile.in

### ISSUE THREAD

**Issue by sgbeal** [madler/zlib#684]
The 1.2.12 build fails to link on Linux x64 (specifically, Mint 20.3 with clang 10) because the build uses -DPIC instead of -fPIC. Insofar as i grep can see, there is no macro named "PIC" used by the source files, so this appears to be a typo in Makefile.in. Globally replacing -DPIC with -fPIC fixes the build.

**Comment by madler** [comment]
Incorporated. Thanks.
