### ISSUE TITLE
Deflate parameter searching problem

### ISSUE THREAD

**Issue by BLUEMEEEE** [madler/zlib#685]
Hello! I'm trying to search for a certain ZIP file's deflate parameter. And I found that even I searched for each combination of parameters(include level, windowBits, memLevel, strategy), I cannot find the certain zip's correct deflate parameters combination(the zip file is generated by using 7zip tool). Is there any deflate parameter I didn't include in? Or I might  searched it in the wrong way? Is it possible to find a certain ZIP file's deflate parameter (the zip file is generated by other tools, like 7zip).

Deflate parameters I seached:
level: 0 to 9
windowBits: -15, -14, -13, -12, -11, -10, -9,  8, 9, 10, 11, 12, 13, 14, 15
memLevel: 1 to 9
strategy: 0 to 4

**Comment by BLUEMEEEE** [comment]
I also try to search for a certain zip file's deflate parameter(the zip is generated using Java SDK java.util.zip package). As far as I known, java.util.zip package is implented with zlib. Is there any difference between zlib and java.util.zip package. Or it's simply because I search it wrong.

**Comment by BLUEMEEEE** [comment]
Thanks for your time.

**Comment by madler** [comment]
What are you searching _for_? What does "correct" mean? If you are trying to recreate the exact same compressed data that 7zip made, using zlib, you can't.

**Comment by BLUEMEEEE** [comment]
这是来自张殷齐的自动回复邮件。您好，您的邮件我已经收到，我将尽快给您回复。

**Comment by minchai23** [comment]
zlib不支持压缩解压zip格式，minizip支持（路径：zlib/contrib/minizip）java.util.zip应该是与minizip类似：依赖zlib，支持zip格式

**Comment by BLUEMEEEE** [comment]
Thanks for your time. I was trying to recreate compressed data that other tools made. After doing some research, I found that the algorithm details of 7z and zlib may not be the same, so I can't recreate compressed data that 7z made. As for java.util.zip, I assume there might be some bugs in my code, and I already fixed it. Thanks for your answers which help a lot.
