### ISSUE TITLE
add Lzma support？

### ISSUE THREAD

**Issue by anjiahao1** [madler/zlib#689]
i see zlib support bzip2 ,but not support lzma. why? hava legal issues or other issuses ？

**Comment by madler** [comment]
zlib does _not_ support bzip2. There are no plans currently to incorporate either bzip2 or lzma2.

**Comment by nmoinvaz** [comment]
@anjiahao1 perhaps you are referring to the minizip code which supports bzip2. There are other libraries that do support lzma such as mine here https://github.com/zlib-ng/minizip-ng or https://github.com/nih-at/libzip
