### ISSUE TITLE
My manually compiled zlib is slower than the system's

### ISSUE THREAD

**Issue by biolxy** [madler/zlib#690]
## 1. install zlib (ubuntu18.04)
```
apt-get install zlib1g zlib1g.dev zlib
```
## 2. download zlib1.2.11 and  static  compilation (ubuntu18.04)

```
cd /opt
wget https://github.com/madler/zlib/archive/refs/tags/v1.2.11.tar.gz
tar -zxvf v1.2.11.tar.gz
cd zlib-1.2.11
mkdir _build
./configure --prefix=/opt/zlib-1.2.11/_build --shared --static
make && make install
```

## 3. compile program
```
gcc -o fq2fa_zlib-1.2.11 fq2fa.c /opt/zlib-1.2.11/_build/lib/libz.a -I/opt/zlib-1.2.11/_build/include
gcc -o fq2fa_zlib-ubuntu fq2fa.c -lz -Lzlib
```
I found that program `fq2fa_zlib-ubuntu`  was 30% faster than program  `fq2fa_zlib-1.2.11`.
I suspect that zlib on ubuntu is compiled with some optimized parameters, right?
I'd like to know why. Thank you.

**Comment by thesamesam** [comment]
GCC's default optimisation level is -O0 and Ubuntu likely builds with -O2.

**Comment by biolxy** [comment]
> GCC's default optimisation level is -O0 (you didn't give one in your commands above, neither to the zlib build itself nor to your program) and Ubuntu likely builds with -O2.

Thanks for your reply.(●'◡'●) I looked in the project build.log file and found that the compile optimization parameters were indeed used
