### ISSUE TITLE
minizip has two risks

### ISSUE THREAD

**Issue by minchai23** [madler/zlib#693]
1. zip.c line 1962
```c
  if(pData == NULL || *dataLen < 4)  // NULL pointer deference, dataLen could be NULL
```

2. unzip.c  line 1569 and line 1589
```c
TRYFREE(pfile_in_zip_read_info);     // MemoryLeak, forget to free pfile_in_zip_read_info->read_buffer
```

**Comment by Neustradamus** [comment]
@madler: What do you think?

cc @nmoinvaz.

**Comment by nmoinvaz** [comment]
I don't maintain minizip in this distribution, that would be @madler and @gvollant.

**Comment by fredgan** [comment]
I think so, it would be better if a PR is submitted

**Comment by gvollant** [comment]
see https://github.com/madler/zlib/pull/694

**Comment by madler** [comment]
Applied. Thank you Gilles.

**Comment by Neustradamus** [comment]
@minchai23: @madler has done the new build : 1.2.13 has been released!

**Comment by Neustradamus** [comment]
Merged commit:
- https://github.com/madler/zlib/commit/138c93cffb76f5c24e4ae6e81e6210428856f825
