### ISSUE TITLE
Reading "disk number start"

### ISSUE THREAD

**Issue by kalibera** [madler/zlib#699]
Minizip reads the disk number start from the zip64 extended information extra field, when the value of disk_num_start is 0xffffffff (MAXU32). However, the specification seems to be saying that one should read from the extra field when the value is 0xffff (4.4.13). Is my reading of the specification correct?

https://github.com/madler/zlib/blob/21767c654d31d2dccdde4330529775c6c5fd5389/contrib/minizip/unzip.c#L1062
https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT

I don't have any use case/archive for this, just came across this possible inconsistency in the code while analyzing a bug report.

**Comment by madler** [comment]
You are correct. I will leave it to @gvollant to suggest the fix.

**Comment by gvollant** [comment]
you are right, unz64local_getShort is used to fill disk_num_start

**Comment by madler** [comment]
Applied fix.

**Comment by madler** [comment]
Applied fix manually. (Due to indentation issues.)

**Comment by Neustradamus** [comment]
Merged commit from @gvollant PR: https://github.com/madler/zlib/pull/829
- https://github.com/madler/zlib/commit/e0bd0ad6e4d8afd2bc3d55d84d459a0e2c0e2890
