### ISSUE TITLE
tagged release files (*.tar.gz) are not found

### ISSUE THREAD

**Issue by felixf4xu** [madler/zlib#709]
Hi,

I have a build script which downloads the .tar.tz file from the tagged release link, for example, https://github.com/madler/zlib/archive/refs/tags/v1.2.11.tar.gz, this link address is from the tag page (https://github.com/madler/zlib/releases/tag/v1.2.11) and it seems to be valid. But If I click the link to follow, it's "not found" error.

Is this a github change or a new tag release page should be re-generated?

**Comment by madler** [comment]
Your link to the .tar.gz seems to work fine. Closing the issue.
