### ISSUE TITLE
The check sum of Packages on the Official Website Different from those on Github

### ISSUE THREAD

**Issue by minchai23** [madler/zlib#710]
Take zlib-1.2.12.tar.gz as an example:
check sum in official website: 91844808532E5CE316B3C010929493C0244F3D37593AFD6DE04F71821D5136D9
check sum in github tag: D8688496EA40FB61787500E863CC63C9AFCBC524468CEDEB478068924EB54932

After comparing the files in the two packages, I find that the github tag package contains a .gitignore file, but the package downloaded from the official website does not contain the file.

Why not keep the software packages in the two places consistent?

**Comment by madler** [comment]
The ones I make are smaller. E.g. 607698 bytes vs. 644492 from GitHub. (Not just due to the .gitignore.) Neither contain the .git directory, so I don't see what the purpose of the .gitignore is in the GitHub archive. I'll just leave things are they are. Both have signatures you can verify.
