### ISSUE TITLE
Simple deflate implementation

### ISSUE THREAD

**Issue by tansy** [madler/zlib#715]
It's more of discussion and request. Does anyone know some simple deflate implementation tutorial as it is [puff](https://github.com/madler/zlib/tree/master/contrib/puff) in zlib? Puff is great but I'm looking for deflate similarily simple so it can be easily comprehended. Doesn't have to be in C but anything in similar syntax is a plus.

**Comment by madler** [comment]
I am not aware of one.

**Comment by nmoinvaz** [comment]
This resource may be of value to you https://www.euccas.me/zlib/

**Comment by tansy** [comment]
Thanks.
It looks good although there is no source.
Good, general, resource anyway.

**Comment by tansy** [comment]
One question, correct me if I'm wrong.
The whole huffman coding is realised in this line (@deflate.c:deflate_huff(...)):
```
_tr_tally_lit(s, s->window[s->strstart], bflush);
s->lookaheaf--;
s->strstart++;
```
Is that right?
I thought I could comprehend this encoding and maybe try to use something else.

**Comment by madler** [comment]
No. The Huffman coding is done in `build_tree()` in trees.c.

**Comment by tansy** [comment]
Thanks anyway. If it's not where it is invoked then I don't get how this function works. But it works.
That's the function called with Z_HUFFMAN_ONLY,  and FLUSH_BLOCK_ONLY is not used in this strategy.

**Comment by tansy** [comment]
Yes, thanks. Now, when I know I got to this in "reverse order".

**Comment by data-man** [comment]
https://www.hanshq.net/zip.html is the best, IMO.

**Comment by madler** [comment]
@data-man That is a nice write up! I hadn't seen that before. Thanks. I have added it to the links at zlib.net.

**Comment by data-man** [comment]
@madler Have you seen the continuation? https://www.hanshq.net/zip2.html
