### ISSUE TITLE
How to use example `fitblk.c` and compilation errors

### ISSUE THREAD

**Issue by Basilisvirus** [madler/zlib#716]
I use Visual studio 2022 with ISO C++17 Standard (/std:c++17) and I have already compiled the Zlib, following the instructions. I do not intend to use the Zlib to make any software, I just want to compile successfully any example to check that the compilation I did is correct, as Zlib is used by another library that I use. ([libharu](https://github.com/libharu/libharu)).

I thought I would try [firblk.c example](https://github.com/madler/zlib/blob/master/examples/fitblk.c), as it seems smaller and easier to compile/test. The example `fitblk.c` does not explain how should I use the example. 

I understand that there is a input to be compressed. But what is the input to the program (string, file?) and how do I define it?

I can understand from the code that the input values (or data to be compressed) are passed from the `int argc, char **argv` variables, aka when the program is called. But will it compress the string I pass to the argv value? or do I pass a directory/file to be compressed? 

Also, since I use C++, I get compilation errors with `malloc` when compling this example, which I can fix, but I want to make sure its correct:

in the line: `blk = malloc(size + EXCESS);` and `tmp = malloc(size + EXCESS);` I get:
` a value of type "void *" cannot be assigned to an entity of type "unsigned char *"`

I change these lines to: `blk = new unsigned char [size + EXCESS];` and `tmp = new unsigned char[size + EXCESS];` and no longer get any errors when compiling. 

Please let me know if the conversion will not cause any issues, and more information on how to use this example.

**Comment by madler** [comment]
First off, it's C, so compile it with a C compiler.

Second, it is a command line program that takes input from stdin, and write the output to stdout. So it would be used like:

`./fitblk 1024 < inputfile > outputfile`

`inputfile` could be, for example, `fitblk.c`. The output file could be `partial.zz`, which will be a zlib stream containing as much of `fitblk.c` as it could in 1024 bytes of output.

**Comment by Basilisvirus** [comment]
I managed to compile the library and run the default example. I am ok.
But then, I want to note that the instructions to run `fitblk.c` are unclear of I am missing something. I compiled the fitblk.c as well, and when I try to input the CMD arguments I get these errors, so then I checked the code, and it actually needs only one argument:
![image](https://user-images.githubusercontent.com/18421898/194706150-588a9ea6-341e-4e46-8be5-80dca42e73b5.png)

And then the issue is, when I run the program with only one argument it just stucks there? the CMD becomes unusable and I need to ctrl+C to wake it up again.

It doesnt want a file to be defined as an input? I do not get it.

Can you check the instructions again?

**Comment by madler** [comment]
No, it doesn't take file names as arguments. It is a filter, so you pipe in the input, and pipe out the output. You didn't read what I wrote. Again: `./fitblk 1024 < inputfile > outputfile`. So your examples need to be:

```.\example.exe 1024 < to zip.txt > output.zz```

Note the less-than and greater-than signs.

**Comment by Basilisvirus** [comment]
All right all right, I first used PowerShell to run `.\example.exe 1024 < tozip.txt > output.zz` , and got its error:
![image](https://user-images.githubusercontent.com/18421898/194724007-7f0f7074-99a1-4265-b503-058cd6f19f0f.png)

So I thought the less/greater-than signs were not meant to be used.

But since you mentioned it a second time, I thought I would use CMD to run the command, and it worked there. Command prompt does not have issues with  < > signs.

**Comment by madler** [comment]
In PowerShell you need to pipe the input (the `>` does work, just not `<`):

`Get-Content tozip.txt | .\example.exe 1024 > output.zz`
