### ISSUE TITLE
Non-signed commit in Tag 1.2.13

### ISSUE THREAD

**Issue by rfrht** [madler/zlib#725]
Hello, @madler !

I see that [Tag 1.2.13](https://github.com/madler/zlib/tags) does *not* contain a commit signature - just checking if is it a overlook or... Well, heh.

Thanks,

- RF.

**Comment by nmoinvaz** [comment]
It is hard for people to believe there is a new release! 😂

**Comment by madler** [comment]
It does have a commit signature. Just verified it:

```
% git tag -v v1.2.13
object 04f42ceca40f73e2978b50e93806c2a18c1281fc
type commit
tag v1.2.13
tagger Mark Adler <fork@madler.net> 1665646511 -0700

zlib 1.2.13
gpg: Signature made Thu Oct 13 00:35:11 2022 PDT
gpg:                using DSA key 5ED46A6721D365587791E2AA783FCD8E58BCAFBA
gpg: Good signature from "Mark Adler <madler@alumni.caltech.edu>" [ultimate]
```

**Comment by rfrht** [comment]
Ah, Github failed to parse it - doesn't show the "Verified" in the Tag Page at https://github.com/madler/zlib/tags

Thanks for stopping by!

**Comment by madler** [comment]
Hmm. So why is github failing to verify it, when it worked all the other times?

**Comment by madler** [comment]
Ok, I figured it out. github is picky about the email address in the tag signature. For some reason it was different than before. I changed it back and the tag now shows as verified. Thanks for the heads up.
