### ISSUE TITLE
Please stop yanking versions.

### ISSUE THREAD

**Issue by mihaimaruseac** [madler/zlib#726]
Over the past months, zlib has yanked 1.2.11 and 1.2.12, causing downstream projects to scramble and update. Sure, you can justify the yanking is justified to cause downstream projects to upgrade past security vulnerabilities, but unfortunately this has other externalities.

For example, projects can no longer run bisects and/or do patch releases for versions previous to the yanking. Because they will fail to build.

Given how widespread the use of zlib is, please consider not yanking versions anymore, or maybe giving a grace period.

**Comment by madler** [comment]
"Yanking"?

**Comment by mihaimaruseac** [comment]
Oh, I see that now all previous versions are at https://zlib.net/fossils/ 

The download URL TensorFlow and downstream projects was `https://zlib.net/zlib-<version>.tar.gz`, but this only works for the last version.

Thank for the question, helped me debug the issue better and will have a fix for TF and downstream.

**Comment by madler** [comment]
The current version is also always in fossils. https://zlib.net/zlib.tar.gz will always give you the latest version.

**Comment by mihaimaruseac** [comment]
Yeah, we were using the wrong link and for 1.2.11 got confused by reports of it being fully yanked from the internet. My bad.
