### ISSUE TITLE
Z_BUF_ERROR detected when calling function "inflate" with parameter flush = Z_TREES

### ISSUE THREAD

**Issue by cfg1234** [madler/zlib#728]
Decompress some specific compressed data using inflate() function with flush parameter Z_TREES will return Z_BUF_ERROR，because code will executed in [https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/inflate.c#L887](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/inflate.c#L887) without consume any input and produce any output，and return in  [https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/inflate.c#L1300](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/inflate.c#L1300)

**Comment by madler** [comment]
It sounds like that's what it's supposed to do. You would need to provide minimal, reproducible example code that illustrates your concern, showing what you get and saying what you expected instead.

**Comment by cfg1234** [comment]
#include <stdlib.h>
#include <stdio.h>
#include <zlib.h>
#include <string.h>
#define ZLIB_V "1.2.13"
#define charf char*
int main(int argc, char* argv[]) {
charf input = "aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrssstttuuuvvvwwwxxxyyyzzz000111222333444555666777888999```~~~!!!@@@###$$$%%%^^^&&&((()))---===\_\_\_+++AAABBBCCCDDDEEEFFFGGGHHHIIIJJJKKKLLLMMMNNNOOOPPPQQQRRRSSSTTTUUUVVVWWWXXXYYYZZZ";
int input_size = strlen(input);
charf compress_buf = (charf)malloc(input_size * 2);
charf decompress_buf = (charf)malloc(input_size);
z_stream cstrm, dstrm;
int winBits = 15;
memset(&cstrm, 0, sizeof(z_stream));
memset(&dstrm, 0, sizeof(z_stream));
int ret;
do {
ret = deflateInit2\_(&cstrm, 1, Z_DEFLATED, winBits, 1, 4, ZLIB_V, (int)sizeof(z_stream));
if (ret) break;
cstrm.next_in = input;
cstrm.next_out = compress_buf;
cstrm.avail_in = input_size;
cstrm.avail_out = input_size * 2;
ret = deflate(&cstrm, Z_FINISH);
if ((ret != Z_OK && ret != Z_STREAM_END) || cstrm.avail_in != 0) break;
deflateEnd(&cstrm);
int comp_len = input_size * 2 - cstrm.avail_out;
ret = inflateInit2\_(&dstrm, winBits, ZLIB_V, (int)sizeof(z_stream));
if (ret) break;
dstrm.next_in = compress_buf;
dstrm.next_out = decompress_buf;
dstrm.avail_in = comp_len;
dstrm.avail_out = input_size;
while (dstrm.avail_in && ret == Z_OK) {
int oriin = dstrm.avail_in;
int oriout = dstrm.avail_out;
ret = inflate(&dstrm, Z_TREES);
printf("ret=%d input_len=%d output_len=%d\n", ret, oriin - dstrm.avail_in, oriout - dstrm.avail_out);
}
inflateEnd(&dstrm);
} while (0);
if (ret != 0 && ret != 1) printf("err return %d\n", ret);
return ret;
}

// expected normally returned but actually return -5 (Z_BUF_ERROR)

**Comment by madler** [comment]
There is nothing wrong. `inflate()` is behaving as documented. To get the next fixed block header, the three bits of the header were already available, so no input was consumed. `Z_TREES` says to stop at the end of the block header, so no output was produced. If no input is consumed and no output is produced, then `Z_BUF_ERROR` is returned.

You just need to proceed with your loop, and the decompression completes successfully.

**Comment by cfg1234** [comment]
But I have a question: Why dont we return Z_OK instead?Z_BUF_ERROR means insufficient output buffer which is actually sufficient.In some cases, output buffer size is fixed because compressed data size is known.If `inflate()` return Z_BUF_ERROR,the result will be ambiguous: Does it mean we read the wrong compressed data, or just a warning that no progress in decompression was made?

**Comment by madler** [comment]
It is just a warning that no progress in decompression was made.
