### ISSUE TITLE
got zlib multiple defined error when building Open3D

### ISSUE THREAD

**Issue by 1939938853** [madler/zlib#730]
Hello,

When I build Open3D, I got zlib multiple defined error. How to solve it?

Thank you!

`
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB8066	Custom build for 'D:\git\open3d_0.15\build_0.16\CMakeFiles\120eb681c97351abe762cc432ece25cf\generate.stamp.rule' exited with code 1.	ZERO_CHECK	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	
Error	MSB8066	Custom build for 'D:\git\open3d_0.15\build_0.16\CMakeFiles\5ef9c6b1004a79529d8b433530887f53\ext_zlib-build.rule;D:\git\open3d_0.15\build_0.16\CMakeFiles\5ef9c6b1004a79529d8b433530887f53\ext_zlib-install.rule;D:\git\open3d_0.15\build_0.16\CMakeFiles\0dcc2ef3167d87326574770afabe7d39\ext_zlib-complete.rule;D:\git\open3d_0.15\build_0.16\CMakeFiles\120eb681c97351abe762cc432ece25cf\ext_zlib.rule' exited with code 1.	ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib)	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets	241	
Error	LNK1169	one or more multiply defined symbols found [D:\git\open3d_0.15\build_0.16\zlib\src\ext_zlib-build\zlib.vcxproj]	ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib)	D:\git\open3d_0.15\build_0.16\zlib\src\ext_zlib-build\Release\zlib.dll	1	
Error	LNK2005	inflate already defined in inflate.obj [D:\git\open3d_0.15\build_0.16\zlib\src\ext_zlib-build\zlib.vcxproj]	ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib)	D:\git\open3d_0.15\build_0.16\zlib.lib(zlib1.dll)	1	
Error	LNK2005	inflateEnd already defined in inflate.obj [D:\git\open3d_0.15\build_0.16\zlib\src\ext_zlib-build\zlib.vcxproj]	ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib)	D:\git\open3d_0.15\build_0.16\zlib.lib(zlib1.dll)	1	
Error	LNK2005	crc32 already defined in crc32.obj [D:\git\open3d_0.15\build_0.16\zlib\src\ext_zlib-build\zlib.vcxproj]	ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib)	D:\git\open3d_0.15\build_0.16\zlib.lib(zlib1.dll)	1	
Error	LNK2005	inflateInit2_ already defined in inflate.obj [D:\git\open3d_0.15\build_0.16\zlib\src\ext_zlib-build\zlib.vcxproj]	ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib)	D:\git\open3d_0.15\build_0.16\zlib.lib(zlib1.dll)	1	
Error	LNK2005	get_crc_table already defined in crc32.obj [D:\git\open3d_0.15\build_0.16\zlib\src\ext_zlib-build\zlib.vcxproj]	ext_zlib (ExternalProjectTargets\ext_zlib\ext_zlib)	D:\git\open3d_0.15\build_0.16\zlib.lib(zlib1.dll)	1	

`

**Comment by madler** [comment]
This is a build and linking issue, not a zlib issue. You should ask your question on stackoverflow.com.
