### ISSUE TITLE
Valgrind error "Conditional jump uninitialised value" not fixed on 1.2.11? 

### ISSUE THREAD

**Issue by eitanlevi** [madler/zlib#743]
I am using zlib 1.2.11 on bionic and bumped into Valgrind error:

```
==74113== Thread 2:
==74113== Conditional jump or move depends on uninitialised value(s)
==74113==    at 0x55D7119: longest_match (in /opt/lib/libz.so.1)
==74113==    by 0x55D8457: deflate_slow (in /opt/lib/libz.so.1)
==74113==    by 0x55D8E3F: deflate (in /opt/lib/libz.so.1)
==74113==    by 0x5225D9: compressData (compress.c:136)
==74113==    by 0x441BA0: processEvents (events.c:453)
....
```
According to ZLIB FAQ, it is written that:

> versions 1.2.4 and later was changed to not stimulate these checkers.

One way to understand it is that it should not happen anymore. Another way might be is that it should happen less.
Is this issue still probable for zlib 1.2.11 or can my implementation caused it?

Thank you.

**Comment by madler** [comment]
Can you provide a minimal, reproducible example that results in this Valgrind error?

**Comment by eitanlevi** [comment]
Hi @madler.
I apologize for the delayed response. Despite trying my best, I was unable to reproduce the problem.

Can you tell me pleaase if the issue is expected?

**Comment by madler** [comment]
No, it is not expected.
