### ISSUE TITLE
dead link to mark nelson dr. dobb journal entry

### ISSUE THREAD

**Issue by bachittle** [madler/zlib#747]
http://marknelson.us/1997/01/01/zlib-engine/ this link is now a 404. Should either remove or find the link and replace.

**Comment by LowLevelMahn** [comment]
where is this dead link to find?
correct link is https://marknelson.us/posts/1997/01/01/zlib-engine.html

**Comment by bachittle** [comment]
in the readme: https://github.com/madler/zlib/blob/master/README

**Comment by bachittle** [comment]
https://github.com/madler/zlib/pull/748 can use that as the diff to another PR or just merge, up to you

**Comment by spaette** [comment]
The current PR  removed after the url a space and  a period.

> another PR

IMHO, it's best to fix and/or update all README urls in one PR eliminating redirects* and using `https` where available.

\* _e.g._ metacpan now hosts Perl modules

In the below it's better to not link to a specific Java SE release.

README

```diff
- zlib is available in Java using the java.util.zip package, documented at
- http://java.sun.com/developer/technicalArticles/Programming/compression/ .
+ zlib is available in Java using the java.util.zip package, 
+ see the API Documentation for java.base at
+ https://www.oracle.com/pls/topic/lookup?ctx=en/java/javase&id=javaselatest .
```

**Comment by bachittle** [comment]
the PR now redirects all to https and fixes the redirects.

**Comment by bachittle** [comment]
I was looking around and mark adler apparently made the fixes in a local branch somewhere. So I closed the PR and will let it be handled.

**Comment by spaette** [comment]
_copied from the linked to PR_

Here is my approach to the Perl content.

```diff
- A Perl interface to zlib written by Paul Marquess <pmqs@cpan.org> is available
- at CPAN (Comprehensive Perl Archive Network) sites, including
- http://search.cpan.org/~pmqs/IO-Compress-Zlib/ .
+ A Perl interface to zlib and bzip2 written by Paul Marquess <pmqs@cpan.org>
+ is available at CPAN (Comprehensive Perl Archive Network) sites, including
+ https://metacpan.org/dist/IO-Compress .
```

for reference

```
$ sed -n 15,16p IO-Compress-2.201/README
This distribution provides a Perl interface to allow reading and writing of
compressed data created with the zlib and bzip2.
$ 
```

**Comment by Neustradamus** [comment]
@madler: Have you seen this issue?

**Comment by spaette** [comment]
@madler

Would this work for you?

```patch
- zlib is available in Java using the java.util.zip package, documented at
- http://java.sun.com/developer/technicalArticles/Programming/compression/ .
+ zlib is available in Java using the java.util.zip package, 
+ see the API Documentation for java.util.zip at
+ https://docs.oracle.com/search/?q=java.util.zip .
```

As of today's date one has to click thereafter the additional hyperlink on `java.util.zip (Java SE 20 & JDK 20)`.

**Comment by madler** [comment]
Applied.
