### ISSUE TITLE
upgrade from 1.2.8 to 1.2.13 causes STREAM_ERROR on deflateInit2

### ISSUE THREAD

**Issue by jmbnyc** [madler/zlib#752]
The following commit is responsible for code that worked with 1.2.8 to no longer work with 1.2.13 (and most likely 1.2.9 etc, but I only tried 1.2.13).

Reject a window size of 256 bytes if not using the zlib wrapper.
There is a bug in deflate for windowBits == 8 (256-byte window).
As a result, zlib silently changes a request for 8 to a request
for 9 (512-byte window), and sets the zlib header accordingly so
that the decompressor knows to use a 512-byte window. However if
deflateInit2() is used for raw deflate or gzip streams, then there
is no indication that the request was not honored, and the
application might assume that it can use a 256-byte window when
decompressing. This commit returns an error if the user requests
a 256-byte window when using raw deflate or gzip encoding.

The code was doing:

deflateInit2(&zs,
                       Z_DEFAULT_COMPRESSION,
                       Z_DEFLATED,         // has to be this value
                       -8,                           // naked, nowrap for IE
                       9,                            // maximum memlevel (fastest)
                       Z_DEFAULT_STRATEGY);
and it no longer works because of the addition of this condition:
(windowBits == 8 && wrap != 1)

So, what is the right thing to do here? This code is being used in an http server to deflate a response and thus those values were chosen to satisfy the receiving web browsers.

**Comment by jmbnyc** [comment]
Hmm, hit send too quick. According to the manual and the code, it would appear that I should change -8 to -9 and then the code will work as I expect (I tried that and it does not work) but I want to confirm.

**Comment by madler** [comment]
If this code has been working all along with the "receiving web browsers", then you can change the `-8` to `-9`, and it will still work. It has always been changed to 9 internally.

What exactly are these "receiving web browsers" that require `windowBits` to be 8? Where is this documented?
