### ISSUE TITLE
When Z_SOLO is defined on 64-bit Windows, z_size_t is defined incorrectly

### ISSUE THREAD

**Issue by mtl1979** [madler/zlib#756]
Documentation says `z_size_t` should be defined as smallest integer type that can hold a pointer, but `unsigned long` is 32 bits on 64-bit Windows and as such can't hold a pointer and will truncate. Only integer type that doesn't require any header file and can contain a pointer is `unsigned __int64`. This will also affect `total_in` and `total_out` in `z_stream_s`; `compress`, `compress2`, `compressBound`, `uncompress` and `uncompress2` that use `unsigned long` to hold length.

To detect 64-bit Windows, preprocessor macro `_WIN64` can be used.

**Comment by madler** [comment]
There is no `unsigned long long`?

**Comment by mtl1979** [comment]
> There is no `unsigned long long`?

There is no `long long` or `unsigned long long` on Windows.

**Comment by madler** [comment]
What compiler are you using? I just checked on Visual C and they're there.

**Comment by mtl1979** [comment]
I have Visual C++ 2015, 2017.9, 2019 and 2022... None of them will give error when trying to use `long long`, but it's silently mapped to 32-bit integer, not 64-bit integer, just like `long` is.

**Comment by madler** [comment]
Wow, that would be in flagrant violation of the standard. Fortunately you are incorrect, at least for the 2022 version I tested. It is indeed a 64-bit type. Here is my test code:

```
int main(void) {
    unsigned long long n = 8528817511, m = n;
    do {
        n = n & 1 ? 3 * n + 1 : n >> 1;
        if (n > m)
            m = n;
    } while (n != 1);
    return m != 18144594937356598024;
}
```
I check that the exit code is zero to verify the 64-bit arithmetic. That code is computing the maximum value reached for the Collatz sequence that has the largest such maximum value less than 2<sup>64</sup>-1. This does several hundred operations requiring 64-bit arithmetic in order to get the right answer. (Overkill, I know.)

**Comment by mtl1979** [comment]
Partial support for `long long` and `unsigned long long` was added in Visual C++ 2015 but it wasn't complete. I can't check every possible update where it has been improved..

As zlib is supposed to work even with old compilers, optionally using `long long` for Visual C++ 2015 and later might be an usable choice.

**Comment by mtl1979** [comment]
Even with Visual C+ 2022, the compiler will give warnings like "Arithmetic overflow" when mixing 64-bit constants and variables, requiring implicit `static_cast<>` or C-style cast to silence the warning... Some functions in Windows API like `printf` don't support `long long` or `size_t` type, but do support `__int64`. This kind of has nothing to do with compiler used to compile the user application or library, but more about what is used to compile the C++ run-time library (MSVCRT) itself.

I've filed quite a lot of bug reports against different versions of Visual C++, so I know there is still issues when compiling code that use 64-bit integers.

**Comment by madler** [comment]
It looks like `long long` was added in VS 2005.

I received no warnings compiling my test code above, either as C or as C++, with 64-bit constants and variables in the 2022 version.

**Comment by mtl1979** [comment]
With the first Visual C++ versions, the 64-bit compiler was separate download, like ARM compilers are with modern versions, so it wasn't tied to specific Visual C++ version, but instead to the version of Windows SDK being installed.

Your example code is too simplified to test full support for `long long`.... It's better to use full source code of zlib as it tests the support more thoroughly...

I get overflow warnings when I try to shift `1` any number of bits and pass it to function like `malloc` or `memcpy` that expects `size_t`, which should map to 64-bit integer type. This type of shifting is common to calculating for example window size. The overflow warning is obviously false positive, but still good example of how the support is incomplete. This isn't unique to Windows as FreeBSD also checks last parameter of `memcpy` and gives warning if it detects possible overflow. 

Core reason is that the intermediate result is truncated to 32-bit integer and then cast back to 64-bit integer, causing the overflow warning.

**Comment by madler** [comment]
> I get overflow warnings when I try to shift `1` any number of bits and pass it to function like `malloc` or `memcpy` that expects `size_t`, which should map to 64-bit integer type.

Can you provide example code that generates these warnings?

> FreeBSD also checks last parameter of `memcpy` and gives warning if it detects possible overflow.

Can you provide example code with this detection?

> Core reason is that the intermediate result is truncated to 32-bit integer and then cast back to 64-bit integer, causing the overflow warning.

Can you provide example code that shows this truncation?

**Comment by mtl1979** [comment]
Simplest code that fails with Visual C++ 2022 is:

```
#include <stdlib.h>
#include <string.h>

int main()
{
   int bits = 8;
   char* a = (char*)malloc(1 << bits);
   char* b = (char*)malloc(1 << bits);
   memcpy(b, a, 1 << bits);
   return 0;
}
```
With FreeBSD, you can just increase the last parameter of `memcpy` to 9223372036854775808 or higher, which still fits in `size_t`, but not `ssize_t` (highest bit is set). That's basically copying first half of the address space over second half of the address space... This error can't happen on 32-bit programs, only on 64-bit programs. Same logic works with shifts, as in you can't shift so that the highest bit changes from `0` to `1`.

**Comment by madler** [comment]
Thanks. I just tried it that code on 2022, both as .c and .cpp, and in neither case did I see any warnings or errors on compilation or execution. What are you seeing?

**Comment by mtl1979** [comment]
@madler I only get warnings when I try to compile in IDE, which suggests IntelliSense is giving the warnings... I also tried Visual C++, gcc and clang in Compiler Explorer and all three generate incorrect code when optimizations are disabled. I haven't yet filed bug reports against gcc and clang as those are generally really slow at fixing bugs related to rare issues like integer promotion rules.

**Comment by madler** [comment]
I can't make heads or tails out of your comments on shifting. I have found no evidence that there are any issues with `long long` in MSVC, or that it was ever 32 bits, so the fix for this issue uses `long long`: https://github.com/madler/zlib/commit/fa8cd50ada68b873c754766bc73b12080b7b309e
