### ISSUE TITLE
Add FetchContent compatibility

### ISSUE THREAD

**Issue by hopeless-programmer-online** [madler/zlib#759]
I prefer to use `FetchContent` for dependency management.
With this:
```cmake
FetchContent_Declare(
    zlib
    GIT_REPOSITORY "https://github.com/madler/zlib.git"
    FIND_PACKAGE_ARGS NAMES ZLIB
)
FetchContent_MakeAvailable(zlib)
```
the whole process of cloning the repo, generating and building it **as a dependency** might be automated by cmake.

The problem is that the `example` executable relies on the assumption that the whole project with the headers is the top-level cmake project.
And of course this is not true in case of `FetchContent` which will download zlib as a subdirectory.

There are several different approaches on how to fix this.
But the simplest one I can see is to add an option to disable tests and examples, like `ZLIB_BUILD_TESTS`.

I can provide an example project that uses zlib as 3rdparty via `FetchContent` to reproduce the issue if needed.

**Comment by glebm** [comment]
We do it like this:

`CMake/functions/FetchContent_MakeAvailableExcludeFromAll.cmake`:

```cmake
# Like `FetchContent_MakeAvailable` but passes EXCLUDE_FROM_ALL to `add_subdirectory`.
macro(FetchContent_MakeAvailableExcludeFromAll)
    foreach(contentName IN ITEMS ${ARGV})
        string(TOLOWER ${contentName} contentNameLower)
        FetchContent_GetProperties(${contentName})
        if(NOT ${contentNameLower}_POPULATED)
            FetchContent_Populate(${contentName})
            if(EXISTS ${${contentNameLower}_SOURCE_DIR}/CMakeLists.txt)
                add_subdirectory(${${contentNameLower}_SOURCE_DIR}
                    ${${contentNameLower}_BINARY_DIR} EXCLUDE_FROM_ALL)
            endif()
        endif()
    endforeach()
endmacro()
```

`3rdParty/zlib/CMakeLists.txt`:

```cmake
include(functions/FetchContent_MakeAvailableExcludeFromAll)

set(CMAKE_POLICY_DEFAULT_CMP0048 NEW)

include(FetchContent)
FetchContent_Declare(zlib
    URL https://www.zlib.net/zlib-1.2.13.tar.gz
        https://www.zlib.net/fossils/zlib-1.2.13.tar.gz
        https://github.com/madler/zlib/releases/download/v1.2.13/zlib-1.2.13.tar.gz
    URL_HASH MD5=9b8aa094c4e5765dabf4da391f00d15c
)
FetchContent_MakeAvailableExcludeFromAll(zlib)

if(DEVILUTIONX_STATIC_ZLIB)
  add_library(ZLIB::ZLIB ALIAS zlibstatic)
  target_include_directories(zlibstatic INTERFACE ${zlib_BINARY_DIR} ${zlib_SOURCE_DIR})
else()
  add_library(ZLIB::ZLIB ALIAS zlib)
  target_include_directories(zlib INTERFACE ${zlib_BINARY_DIR} ${zlib_SOURCE_DIR})
endif()

# 1. Set the variables that are usually set by FindZLIB.cmake.
# 2. Add the module that stubs out `find_package(ZLIB ...)` calls.
set(ZLIB_FOUND ON PARENT_SCOPE)
set(ZLIB_LIBRARY ZLIB::ZLIB PARENT_SCOPE)
set(ZLIB_LIBRARIES ZLIB::ZLIB PARENT_SCOPE)
set(ZLIB_INCLUDE_DIR ${zlib_SOURCE_DIR} ${zlib_BINARY_DIR} PARENT_SCOPE)
set(ZLIB_INCLUDE_DIRS ${zlib_SOURCE_DIR} ${zlib_BINARY_DIR} PARENT_SCOPE)
set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_CURRENT_LIST_DIR}/CMake" PARENT_SCOPE)
```

`3rdParty/zlib/CMake/FindZLIB.cmake`:

```cmake
# No-op, ZLIB::ZLIB is built from source.
```

**Comment by Molochnik** [comment]
Do you have a plan on adding this feature in the nearest future?

**Comment by Oodini** [comment]
> The problem is that the `example` executable relies on the assumption that the whole project with the headers is the top-level cmake project.
> And of course this is not true in case of `FetchContent` which will download zlib as a subdirectory.

So, what is the effect ?
I have some troubles (ZLIB_LIBRARY and ZLIB_INCLUDE_DIR not found), but I don't know if there are related to what you set out.

**Comment by madler** [comment]
> But the simplest one I can see is to add an option to disable tests and examples, like `ZLIB_BUILD_TESTS`.

Such an option has been added.
