### ISSUE TITLE
zLib 1.2.3.5 and newer do not work with z/OS datasets

### ISSUE THREAD

**Issue by jmvdkolk98** [madler/zlib#76]
I have been using zLib for the longest time as part of a z/OS (mainframe) application. Unfortunately I cannot update zLib beyond version 1.2.3.4 as changes zLib version 1.2.3.5 include use of I/O functions based on file descriptors instead of I/O functions based on streams. Functions like fopen() were replaced with open(). Looks like I have to reimplement all of gzlib.c, based on stream I/O functions.

Any reason why gzlib.c should keep using the file descriptor versions going forward?

**Comment by mtl1979** [comment]
z/OS should support open() when _POSIX_SOURCE is defined and &lt;fcntl.h&gt; is included.

**Comment by madler** [comment]
zlib uses the lower-level I/O functions for improved performance.  I have added a `#define _POSIX_SOURCE` to gzguts.h.  Hopefully that doesn't break anything.

**Comment by jmvdkolk98** [comment]
Thank you. I just got back from vacation but will validate if it works before the end of august.

Kind Regards, Schöne Grüße, Atenciosamente, Vriendelijke groet,

Jean-Marc van der Kolk

IntelliMagic – Availability Intelligence
T: +31 (0) 71 – 5796000
M: +31 (0) 6 – 50238934
http://www.intellimagic.com
