### ISSUE TITLE
Password-protected zip file from WinRar fails to extract

### ISSUE THREAD

**Issue by UltraEngine** [madler/zlib#760]
When I try to extract a file from a password-protected Zip file made by WinRar (latest version, but this happens in old versions too) I get a UNZ_BADZIPFILE error. I traced the problem to this code, around line 1425 of minizip/unzip.c:
```
    if ((err==UNZ_OK) && (s->cur_file_info.compression_method!=0) &&
/* #ifdef HAVE_BZIP2 */
                         (s->cur_file_info.compression_method!=Z_BZIP2ED) &&
/* #endif */
                         (s->cur_file_info.compression_method!=Z_DEFLATED))
        err=UNZ_BADZIPFILE;
```
The problem is that cur_file_info.compression_method is equal to 99.

File is attached. The password is "password":
[test.zip](https://github.com/madler/zlib/files/10299808/test.zip)

**Comment by UltraEngine** [comment]
AES is not supported:
https://access.redhat.com/solutions/59700

In WinRar, there is an option to use "legacy" encryption you can check.

**Comment by nmoinvaz** [comment]
Feel free to try https://GitHub.com/zlib-ng/minizip-ng
