### ISSUE TITLE
Invalid stream in a Firebase server response

### ISSUE THREAD

**Issue by ricardopieper** [madler/zlib#773]
Hi guys!

I opened this ticket https://github.com/nodejs/node/issues/46359 and here https://github.com/denoland/deno/issues/17565 regarding a response from a Firebase server. Node (which uses zlib) and Deno are unable to understand the response, but some other implementations, such as Python and C#, can decompress the gzip file without trouble. Browsers also seem to have no problem at all decompressing and interpreting the file. Additionally, gzip, Java, and async-compression in Rust are unable to deal with it.

I am asking for help whether the zlib library is really unable to handle this byte stream and why. Is it truly incorrect? This has been a mistery and the behavior among many decompressing libraries across many languages has been very inconsistent.

I submitted the file here. This is the result of running `curl -o compressed.gz -H 'accept-encoding: gzip' https://elza-c332f.firebaseapp.com/__/auth/handler.js`.  This is a firebase server response, which leads me to believe the file is at least correct enough that browsers can understand it. This leads to the scenario where the `fetch` JS function works in browsers, but Node, which uses zlib, doesnt work, even in Node 19.

[compressed.gz](https://github.com/madler/zlib/files/10522405/compressed.gz)

Any light you guys can shine here at all would help. You can close if this is too off topic, but I think it's at least an interesting thing to look at.

**Comment by madler** [comment]
That is an incomplete and therefore invalid gzip stream.

It's fine as far as it goes, but it is cut off before it ends. A valid gzip stream has a deflate stream with a deflate block marked as the last block, followed by a gzip trailer containing a CRC and length check. This stream ends with a deflate block, and empty stored block, that is not marked as the last block and nothing after that.
