### ISSUE TITLE
Using zran with raw DEFLATE streams

### ISSUE THREAD

**Issue by forrestfwilliams** [madler/zlib#780]
I'm excited about using `zran` to create indexes for `zlib` compressed data. However, I'm working with raw [`DEFLATE`](https://www.rfc-editor.org/rfc/rfc1951) streams that do not have [`zlib`](https://www.rfc-editor.org/rfc/rfc1950) or [`gzip`](https://www.rfc-editor.org/rfc/rfc1952) headers/footers. My understanding is that `zran` currently expects the input data to be in either a `zlib` or `gzip` format. What modifications would need to be made to ensure that `zran` is compatible with raw `DEFLATE` streams?

**Comment by madler** [comment]
There is a rewrite of zran that'll do that here: https://github.com/madler/zlib/tree/develop/examples .

**Comment by forrestfwilliams** [comment]
Thank you for implementing this @madler, really appreciate it!
