### ISSUE TITLE
Enable exporting/importing zran index information to/from a file.

### ISSUE THREAD

**Issue by forrestfwilliams** [madler/zlib#785]
`zran` is an incredibly useful utility for obtaining portions of data from DEFLATE compressed archives. In particular, I would love to use it in the context of write-once-read-many scientific data archives, where setting up `zran` indexes for the data could greatly increase data retrieval speeds for subsequent reads.

To accomplish this however, I would like to be able to save an index created by `zran` to an external file, then be able to load this external index file back into `zran` so that the index does not need to be re-created each time the data is read. Others have added this functionality to a modified version of `zran` (see [zran_export_index](https://github.com/pauldmccarthy/indexed_gzip/blob/42557f6146e8ca7ad7858b4012c57b800fd5a42f/indexed_gzip/zran.c#L3001) and [zran_import_index](https://github.com/pauldmccarthy/indexed_gzip/blob/42557f6146e8ca7ad7858b4012c57b800fd5a42f/indexed_gzip/zran.c#L3171)), but it would be great if this was implemented in the canonical version of `zran`.

If there is anything I can do to assist in this effort, please let me know.

**Comment by madler** [comment]
That is why I exposed the `point_t` structure in zran.h in the rewrite. With that, you can trivially write your own exporter and importer to your liking, possibly including other information that you need for your application. I would also recommend compressing the index on export. Nearly all of it will be 32K dictionaries, which will be about as compressible as the file you're indexing.

**Comment by forrestfwilliams** [comment]
Ah OK, that makes sense. Thank you!
