### ISSUE TITLE
when uncompress data below, the data is uncompressed successfully, but the return value is wrong.

### ISSUE THREAD

**Issue by baosj0** [madler/zlib#786]
`const uint8 data[] = {0x78,0x01,0xec,0x58,0x6f,0x6c,0x14,0xc7,0x15,0x7f,0xbb,0x77,0x06,0xfb,0x82,0xc1,0x06,0x43,0x80,0x38,0x64,0xf1,0x95,0x3f,0x21,0x3e,0x77,0x77,0xef,0x0f,0x77,0x90,0x23,0xde,0xbd,0xdb,0xc3,0xa4,0x76,0xce,0x85,0x08,0x57,0xea,0xb5,0xdc,0xfa,0x7c,0x8e,0x8f,0xda,0x77,0xd6,0xdd,0xb9,0x98,0x22,0xe8,0x19,0x22,0x85,0x7c,0xa0,0x8a,0xda,0x0a,0x45,0xf9,0x92,0x54,0xed,0x07,0x54,0x54,0x29,0x69,0xa5,0xb6,0x6a,0xda,0x06,0x22,0x14,0x55,0x55,0x95,0x46,0x2a,0xa2,0xa5,0x69,0x95,0xa4,0xdf,0xf8,0x50,0x89,0x6f,0x95,0xaa,0x96,0xeb,0xef,0xed,0xde,0xe2,0xb5,0x71,0xf1,0xd5,0xf9,0x10,0xa1,0x32,0xab,0xdf,0xce,0xdb,0x37,0x33,0xef,0xbd,0x99,0x79,0x33,0xfb,0x66,0x3e,0xf8,0x7d,0xe7,0xc7,0xdf,0x7b,0x6b,0xeb,0x27,0xb4,0x28,0x1d,0x20,0x0f,0xdd,0xa9,0xb7,0xd1,0x2a,0x17,0x5f,0x00,0xcd,0xb0,0x52,0x07,0x91,0x08,0x82,0xbf,0xef,0xd4,0xeb,0x75,0x8b,0x87,0x17,0xc8,0x87,0xe9,0x01,0x1a,0x81,0x7f,0xc3,0xd6,0xd5,0x8d,0x39,0xf4,0x22,0x6f,0x01,0x78,0xce,0x5b,0x1b,0xbc,0x36,0xe4,0x3e,0xe0,0x11,0x60,0x4d,0x83,0xf7,0x00,0x75,0xef,0xa1,0xa9,0xcb,0x8c,0xc0,0x61,0x2a,0xe1,0xa9,0x92,0x44,0x06,0x15,0x91,0x97,0xe9,0x24,0x66,0xb9,0xf9,0xb4,0x09,0x1e,0xe3,0xa8,0x60,0xdf,0xb9,0x5f,0xea,0xff,0xa4,0xfd,0xc3,0x9b,0xc6,0x4d,0xc1,0x83,0x4a,0x57,0x3a,0xed,0x9a,0x47,0x49,0x27,0xed,0x7e,0x8d,0x96,0x29,0x6b,0xc5,0x0e,0xe4,0xe8,0x67,0xb9,0x4b,0x25,0xf9,0x17,0xb6,0x5e,0x47,0xbf,0xbb,0xce,0x18,0x15,0xd0,0xe7,0x95,0xa7,0x56,0xec,0x82,0x8e,0x7e,0xce,0x9b,0x95,0xf4,0x1e,0x6f,0x9c,0x48,0xdb,0x8f,0x8f,0x8c,0x28,0x36,0xb9,0xa2,0x37,0xf4,0x0b,0xbc,0x0f,0xf3,0xda,0x6d,0x56,0x3f,0xaf,0xed,0x2d,0x8d,0xc9,0x62,0x33,0xb8,0x3d,0x8f,0x9d,0x7b,0xfd,0x3b,0x7b,0xc2,0xe2,0xf5,0xdf,0x8e,0x7a,0x6b,0x81,0x75,0x40,0x07,0xd0,0x09,0xac,0x07,0x36,0x00,0x5d,0xc0,0x46,0x60,0x13,0xf0,0x28,0xb0,0x19,0xd8,0x02,0x6c,0x05,0x1e,0x03,0xba,0x01,0xfe,0x57,0x6c,0x43,0xfe,0x04,0x20,0x01,0xdb,0x81,0x1e,0xc0,0x0f,0x7c,0x0e,0xd8,0x01,0xec,0x04,0x76,0x01,0xbb,0x81,0x27,0x81,0x3d,0xc0,0x53,0x40,0x2f,0x10,0x00,0xfa,0x80,0xcf,0x03,0x32,0xa0,0x00,0x2a,0x10,0x04,0x42,0x40,0x18,0x88,0x00,0x7b,0x81,0x28,0x10,0x03,0xf6,0x01,0xfb,0x81,0xa7,0x81,0x38,0x70,0x00,0x78,0x06,0x60,0x5b,0x34,0xe4,0x3a,0x90,0x00,0x92,0x80,0x01,0x30,0x9f,0xf1,0xff,0x90,0x84,0x77,0xdf,0xaa,0x09,0xd6,0xcc,0x0b,0x24,0xef,0x11,0xc5,0x57,0xda,0x68,0xba,0x6b,0xd5,0x80,0x87,0xce,0x8a,0x34,0x76,0xc9,0xe3,0xc5,0xe6,0xdf,0x4d,0x47,0x75,0x6d,0xb8,0x5c,0x3a,0x9e,0x3f,0x9f,0xab,0xb6,0xf0,0x28,0xf7,0x8b,0x5d,0xc7,0x57,0x89,0xbe,0xb8,0xe8,0x5b,0x2d,0x96,0x85,0xae,0xd6,0x96,0x55,0xeb,0xdb,0xc4,0xf5,0x1f,0x7e,0xfb,0xef,0x79,0xe1,0xbb,0xb4,0x46,0x7c,0xf6,0x69,0xd1,0xb7,0x89,0x84,0x72,0xad,0x52,0x1d,0x2b,0x4d,0xe6,0x0f,0x88,0x5b,0xa8,0x82,0xad,0x65,0x0c,0x1b,0x4d,0x6d,0x92,0xf2,0xd4,0x4e,0x13,0xb4,0x43,0xfc,0x2a,0x79,0xf6,0x64,0x0e,0x9e,0x92,0xe5,0x9a,0xac,0xca,0xa1,0xa0,0x1c,0xa0,0xd6,0xc7,0xbd,0xde,0x04,0xf9,0xc4,0xb5,0xc2,0x7a,0x59,0x0e,0x51,0xe4,0xb4,0x5f,0xed,0x93,0xfd,0x32,0xf9,0x13,0xfb,0x32,0x23,0x85,0x22,0xda,0x9f,0xa8,0x64,0x8e,0x9c,0xac,0x8c,0x48,0xe9,0x91,0x48,0x28,0xe3,0xc9,0xab,0x7d,0x54,0x9d,0x1c,0xf5,0xa7,0x07,0x0d,0x89,0xb4,0x99,0x6a,0x69,0xca,0xac,0x16,0xba,0x4b,0x45,0xca,0x92,0x70,0xce,0x48,0x8f,0x8f,0x27,0x0b,0xb9,0x17,0x8d,0x34,0x8d,0xd7,0xa8,0x70,0x9d,0x72,0x67,0x8d,0x1f,0xd4,0x3a,0x5f,0xab,0x09,0x73,0x06,0xa9,0xc9,0x54,0x34,0x29,0x87,0x12,0x14,0x08,0xeb,0x29,0x2d,0xa0,0xc8,0x35,0x45,0x0f,0xe8,0x49,0x23,0x5c,0x33,0xae,0x6b,0x5a,0x2d,0x11,0xaa,0xb5,0xa8,0xe7,0x8d,0xda,0xab,0xf4,0x42,0xd9,0x9c,0x92,0x52,0x05,0x58,0x5d,0x91,0x76,0xcf,0x46,0x23,0x4f,0xd6,0x32,0x89,0xd2,0xd4,0x54,0xa9,0xe8,0x69,0xa3,0xcc,0x50,0x21,0x57,0x2e,0x55,0x4a,0x34,0x5e,0x95,0x8e,0x4c,0x98,0xe5,0x3c,0x8d,0x65,0xd2,0xa9,0xd4,0xa1,0x84,0x41,0x8a,0x92,0x19,0x3a,0x92,0xee,0x4b,0x6e,0x1e,0x1c,0xf4,0xbf,0xd4,0x71,0x6e,0x58,0x52,0x14,0xa9,0x4f,0x96,0xd2,0xa3,0x73,0xd7,0xa4,0xc1,0x2b,0x85,0xd1,0xb2,0x59,0x3e,0x49,0xcf,0x91,0xd0,0xb3,0xee,0xec,0x1f,0x05,0xda,0x70,0xd6,0x73,0xe3,0xb2,0x77,0x0b,0xcd,0x5d,0xbf,0xf6,0xfd,0x77,0x6e,0x29,0xe2,0x41,0xf1,0x67,0xf6,0xb6,0xf0,0xc3,0xad,0xab,0x1f,0x51,0xcf,0xb7,0x74,0x8b,0x9d,0x03,0xba,0x70,0x5c,0xd1,0xa7,0xae,0xf6,0x9f,0xdb,0xa6,0x8b,0x42,0x4b,0xef,0x17,0xf5,0x8d,0x17,0x2f,0x6c,0xd7,0x5b,0x9f,0xd2,0x85,0x0e,0x41,0x17,0xe0,0xb4,0x9c,0xde,0x98,0x83,0x6b,0x0f,0xb3,0xab,0x37,0x9d,0x84,0x4d,0x68,0x7c,0x1b,0xd5,0xbb,0x45,0xa2,0xeb,0xc8,0xcf,0xe3,0x9b,0x1d,0xdf,0x8f,0xef,0xb7,0xbd,0xb6,0x1c,0x96,0x7f,0xe3,0xf2,0xc5,0x0b,0x5c,0xe2,0xb1,0x59,0xf4,0x53,0xd0,0x82,0xa5,0x98,0x6b,0x33,0x93,0xf3,0xe6,0x37,0xc0,0x86,0x98,0x46,0xd6,0x81,0x9c,0x25,0xb7,0x00,0xbc,0xf5,0xd8,0xb2,0x58,0x03,0x6f,0x56,0xfc,0x35,0x8b,0x1c,0x26,0xdd,0x3f,0xd9,0xea,0x87,0xb0,0x88,0x6d,0x01,0x5c,0xdb,0x31,0xce,0x36,0xf6,0xa3,0xbb,0xdf,0x8e,0x8a,0xcf,0x2a,0xb7,0x6d,0xb3,0xad,0xb2,0x7b,0xc5,0x96,0x2c,0xec,0xb0,0x63,0xbd,0x5d,0xee,0xf4,0x6a,0x65,0x16,0x2f,0x96,0x61,0xeb,0xbf,0x9f,0x2c,0xbb,0xc5,0x47,0x8f,0x3b,0x2d,0x57,0x90,0xdf,0xf9,0xad,0x40,0x68,0x3f,0xd7,0x3a,0x7f,0x90,0x68,0xd0,0x3c,0xaf,0x0e,0xbf,0xc3,0x45,0x6f,0x76,0xd1,0x92,0x8b,0xde,0xed,0xa2,0x65,0x17,0x1d,0x75,0xd1,0xfd,0x2e,0x7a,0xc0,0x45,0x0f,0xbb,0xe8,0x2f,0xb9,0xe8,0xac,0x8b,0x9e,0x70,0xd1,0xd3,0x2e,0x7a,0xd6,0x45,0xd7,0x5c,0xf4,0x79,0x17,0xfd,0x8a,0x8b,0x7e,0xd5,0x45,0xbf,0xe1,0xa2,0x2f,0xb9,0xe8,0x37,0x5d,0xf4,0xcf,0x5d,0xf4,0x15,0x17,0xfd,0x1b,0x17,0xfd,0x81,0x8b,0xfe,0x93,0x8b,0xfe,0x18,0xb4,0xed,0x34,0xb7,0x41,0x69,0xfd,0x9b,0xac,0x05,0xa2,0xf5,0x6f,0x6e,0xe4,0xce,0xf7,0xd6,0xc6,0xf7,0x83,0x9e,0xdb,0xfd,0xe2,0x1e,0x77,0x34,0x7a,0x8e,0x03,0xe8,0xf3,0x6f,0x92,0x56,0xad,0x96,0x0b,0xa3,0x33,0x55,0xca,0x4b,0x47,0xf5,0x63,0xcf,0x99,0x53,0x20,0xe2,0x52,0x0f,0x76,0xd3,0xda,0x2d,0xa5,0xa7,0xdd,0x37,0x61,0x7a,0x5a,0xbd,0xe6,0x84,0xd0,0xdd,0xee,0x33,0x2b,0x63,0xef,0x8e,0xb7,0xac,0xa9,0x98,0x63,0xe3,0x4f,0xbc,0xe8,0x39,0xf3,0xaf,0x09,0x73,0xe3,0xd9,0xfa,0x33,0x89,0x5a,0xfd,0xa5,0xab,0x9d,0xe9,0x4b,0xeb,0x12,0x8f,0xd6,0x5f,0xaf,0xef,0xfa,0xc3,0xae,0x76,0x3e,0xf3,0x2c,0x95,0x58,0x39,0xd1,0x37,0x10,0x2e,0xf8,0x01,0xa2,0xdf,0x99,0x27,0xf9,0x10,0x5c,0xf7,0xb6,0x12,0xb5,0x61,0xbb,0xbc,0xe4,0xb1,0xf6,0x44,0xab,0x29,0xff,0x57,0x45,0xfa,0x27,0xe2,0x97,0x0c,0x1d,0xa4,0x53,0x88,0x57,0xf8,0x51,0x81,0x10,0xe2,0x8c,0x14,0x62,0x19,0x9b,0x23,0x2f,0xa0,0x12,0x0d,0xee,0x7c,0xa9,0x53,0x8b,0x73,0xfc,0x16,0xe9,0x34,0xa2,0xa5,0x10,0xa2,0x20,0xfc,0x19,0x11,0xdf,0xf8,0x11,0xbb,0xec,0x83,0x86,0x61,0x3a,0x4c,0x69,0xe8,0x39,0x8c,0x78,0xfa,0x0c,0xb4,0x64,0xc0,0x4f,0xd3,0x10,0x9e,0x34,0x7e,0x35,0x67,0x10,0x29,0x65,0x40,0x1f,0x02,0x97,0xeb,0x1d,0x69,0x70,0x8e,0x91,0x1d,0x81,0x1f,0x6b,0xb4,0x7f,0x16,0x96,0x25,0xe8,0xf9,0xa5,0xba,0xbe,0x24,0x6f,0x2b,0x7a,0xc8,0x63,0xe2,0xa4,0x25,0x2b,0x2d,0x62,0xf2,0x86,0x72,0x09,0xe3,0xc5,0xc9,0xb6,0xfa,0x7f,0xd5,0x6a,0xb7,0xe5,0x77,0x07,0xe2,0x5f,0x1e,0x71,0x3e,0xb3,0xb2,0x0d,0xcc,0x5b,0x2e,0xf5,0xa3,0xc2,0x48,0x63,0x9a,0x16,0xea,0x3f,0x41,0x53,0xcb,0x35,0x5e,0x54,0xde,0xb5,0x82,0xfe,0xa7,0x20,0xa3,0x63,0x91,0x9c,0x4f,0xf3,0xe9,0x8c,0x7d,0xb3,0xfd,0x77,0xeb,0xb2,0x67,0x3f,0xd3,0xf0,0x82,0x08,0x7c,0x84,0x39,0x06,0xbc,0xac,0x0f,0xf1,0xf0,0x20,0x1e,0x3f,0x38,0x05,0x04,0x70,0x33,0x64,0xd2,0x24,0x49,0x28,0x35,0xf1,0x55,0xa0,0x1c,0xe8,0x14,0x42,0xba,0x32,0x72,0x8d,0xa6,0xf1,0x4c,0x5a,0x5c,0x13,0xa1,0x5e,0x01,0xfc,0x22,0x6a,0xb9,0xd3,0x4e,0xc1,0x59,0x07,0x31,0xf8,0x62,0x08,0x9e,0x1b,0xc4,0x3b,0x04,0x2f,0x0e,0x20,0x6a,0xd7,0xf0,0xad,0x80,0x52,0xf0,0x24,0xac,0xb5,0x11,0x45,0x0c,0xcf,0x1e,0x6f,0xaf,0x03,0x0d,0x35,0xf8,0x2b,0x02,0xa8,0x78,0x07,0x61,0x07,0xaf,0x03,0x15,0x76,0x46,0x91,0xf3,0x5a,0x70,0xd6,0x41,0x19,0xda,0x5f,0x80,0x5d,0x26,0x66,0x93,0x6d,0x2c,0xc0,0xb2,0x3c,0xac,0x91,0x70,0xa2,0x98,0x45,0xed,0x08,0x4e,0x15,0xbc,0x16,0xb8,0x0f,0x5c,0xb7,0x02,0x8c,0x5b,0x67,0x60,0xc4,0x8a,0x78,0x98,0x9f,0x47,0x8d,0x34,0xda,0xa6,0xac,0x15,0x83,0x88,0x0e,0x4f,0x06,0xf2,0x2a,0x56,0x4f,0xab,0xd0,0x5a,0x82,0xd4,0x51,0x68,0x5d,0x4a,0xce,0x30,0x4a,0x4f,0x40,0x46,0x19,0xfe,0x5d,0x82,0x3c,0x3e,0x59,0x4b,0x96,0x0c,0x5e,0xb5,0x12,0x24,0x8f,0xd2,0x71,0x94,0xe7,0x2c,0xfe,0x20,0x6a,0x8c,0x5a,0xf6,0x2e,0x3e,0x7d,0xff,0x72,0xc9,0xbd,0x23,0x08,0x19,0xf3,0xbb,0x83,0x9b,0x6a,0x6e,0xef,0xe0,0x31,0xe3,0xf1,0x9a,0x1f,0xb3,0x11,0xcb,0x46,0x0e,0xd0,0x4f,0xa0,0x87,0x19,0xec,0x0e,0x27,0x91,0x8f,0xc0,0xce,0x11,0x8c,0x56,0x08,0x1c,0x27,0x80,0xe7,0x91,0xe4,0xf6,0xd5,0x46,0xef,0xd3,0xf0,0x10,0x03,0x3d,0xd2,0xe0,0x1f,0x55,0xb4,0x9f,0xc2,0xa8,0x3b,0xf3,0xef,0x9e,0xfd,0xd0,0xdd,0xd9,0x57,0xe1,0x57,0x29,0xcc,0x42,0x12,0xfa,0x43,0x98,0x33,0x9e,0x7d,0x1d,0x1c,0xcd,0x9a,0x7d,0x19,0xa3,0xa4,0x83,0xd2,0x51,0x6e,0xa0,0x64,0xe1,0xec,0xb3,0xbf,0xd8,0x7c,0xf5,0xee,0xec,0x07,0x17,0xf4,0x64,0xd8,0x9a,0xd1,0xe5,0x67,0x3f,0x61,0xd9,0x3a,0x85,0x77,0x11,0xd6,0xcf,0xfb,0xc8,0xd2,0x7e,0x71,0x04,0x27,0x16,0x13,0x92,0x11,0xe2,0x2f,0xe9,0x17,0x43,0x18,0xb1,0x34,0x46,0xc5,0x59,0x31,0x4b,0xf9,0x84,0xdb,0xb7,0x56,0xe2,0x0b,0x02,0x7e,0x33,0x5e,0xf2,0xe2,0x57,0xbe,0x4a,0x14,0xa8,0x15,0xb9,0x0f,0xf9,0x1a,0xd1,0x5e,0xfd,0x3c,0xd6,0xbc,0xfb,0x59,0x87,0xb0,0x05,0x3b,0xb2,0x7b,0x77,0x58,0x9e,0x6e,0x04,0x14,0xee,0xa9,0x6b,0xd0,0x37,0x2e,0x0b,0xd8,0x65,0xed,0x83,0x49,0x17,0xe6,0x4e,0x81,0x67,0x84,0xad,0x11,0x89,0xc1,0x23,0xc6,0x30,0xa3,0xf5,0xfa,0x7a,0xd1,0xa9,0x51,0xaf,0x5f,0xbc,0xd0,0x68,0xc8,0xc1,0xc7,0x55,0xfc,0x1a,0x6d,0xe5,0x82,0x20,0x81,0xb1,0xbc,0x21,0x76,0x0d,0xec,0xae,0x4d,0xd7,0x6d,0x56,0xe6,0xc3,0x7a,0x9f,0xfd,0x08,0x44,0xff,0xfc,0xbe,0x3c,0xb7,0x7f,0xe6,0x0b,0xbf,0xfa,0xd6,0x5f,0x0e,0x5f,0xfb,0x6b,0xe0,0x6d,0xb6,0x48,0x80,0x9f,0x70,0x9e,0x45,0x5e,0x03,0x88,0xda,0x85,0xb5,0x54,0xa7,0xdb,0x3b,0xe0,0xea,0xde,0xe1,0xd2,0x89,0x7c,0x79,0xb8,0x54,0x28,0x56,0x1f,0xbb,0x95,0x25,0x8f,0x17,0x77,0x12,0xff,0xf8,0x5b,0x96,0x5a,0xbc,0xb8,0x19,0x50,0x22,0x57,0xcf,0x34,0xc8,0xa0,0xba,0xfa,0x9b,0x5c,0x3c,0x64,0xe6,0x7e,0xf2,0xe3,0x2c,0x79,0xb9,0x5e,0xe4,0x47,0xfe,0x2c,0x24,0x38,0xb7,0x18,0xb9,0xea,0xaf,0xdf,0xc9,0xc2,0x95,0xed,0xdb,0x89,0xef,0x64,0x99,0xc6,0x65,0x41,0x21,0x97,0xdf,0x38,0xc3,0x52,0xac,0x43,0xf8,0x7b,0xb9,0x2c,0xb5,0xd1,0x31,0xe3,0xeb,0xe6,0xe4,0x8c,0x59,0xcd,0x6f,0xbe,0x99,0xc5,0xb5,0xd7,0x84,0x69,0x3f,0xe6,0x04,0xe7,0x87,0xdf,0xcf,0xe2,0x37,0x8e,0x80,0x72,0xdc,0x01,0x47,0x95,0x45,0xe8,0xda,0x76,0x0f,0x77,0x61,0xcb,0x97,0xf7,0x64,0x09,0xeb,0x56,0x10,0x06,0xd0,0xc9,0x0e,0xd1,0x83,0x6e,0x6f,0x80,0xa3,0xcf,0xdf,0x64,0xf2,0x30,0x20,0xb0,0x01,0x5f,0xbc,0xef,0x02,0xb0,0x57,0xff,0x5a,0x54,0xe2,0xe1,0x5b,0x03,0x69,0x82,0x75,0x1b,0x07,0xa2,0xc9,0x74,0x28,0x19,0xef,0x39,0x15,0xd6,0x94,0xbd,0x51,0xdd,0x50,0x03,0xd1,0x50,0x54,0x0e,0x84,0x42,0x51,0x0d,0x54,0x2c,0x1c,0x50,0xb5,0x60,0x24,0x99,0x8c,0x06,0x63,0x4a,0xc8,0x38,0x8d,0x38,0x7a,0xa8,0x34,0x36,0x33,0x99,0x8f,0x5b,0x03,0xd4,0xee,0x43,0x9c,0x9d,0x8f,0xf7,0xcc,0x8f,0x2a,0x2a,0x0c,0xe4,0x27,0xa7,0x13,0xa5,0x62,0x35,0x3f,0x5b,0x65,0xc1,0x32,0x58,0x47,0xf3,0xe5,0x4a,0xa1,0x54,0xc4,0xad,0xc9,0x34,0x6e,0x67,0x46,0x27,0xf3,0x41,0x35,0xde,0x13,0x8c,0x05,0x55,0x55,0x95,0x65,0xae,0x90,0x18,0x3a,0x18,0xef,0x31,0x62,0x86,0x1e,0x0e,0x6b,0xc1,0x70,0xcc,0x0d,0x94,0x26,0x87,0xf5,0x78,0x4f,0x52,0x4d,0xca,0x11,0x23,0x12,0x0e,0x47,0x22,0x11,0x1b,0x28,0x39,0x98,0x88,0xf7,0xe8,0xba,0x1e,0x93,0xf7,0xc6,0x12,0x29,0x25,0x96,0x64,0xc8,0x06,0x0a,0xda,0x7d,0x5f,0x1e,0x28,0x55,0xaa,0x92,0x31,0x5b,0xcd,0x17,0xc7,0xf2,0x65,0xe9,0x50,0x71,0xbc,0xf4,0x95,0x76,0xdf,0xce,0x01,0x28,0xe4,0xa4,0xc4,0x4f,0x05,0xa3,0x41,0x35,0x19,0x09,0xc9,0x81,0x44,0x2a,0x26,0x07,0x14,0x25,0x91,0x0a,0x44,0x8d,0x50,0x30,0x20,0xcb,0x9a,0x9c,0x88,0x29,0x8a,0x2c,0x87,0xb5,0xd3,0xfb,0x8f,0xea,0xc6,0xfe,0xbb,0xad,0x64,0x4b,0xf2,0x48,0xa9,0xfc,0xb5,0xca,0xb4,0x99,0xcb,0x43,0xa0,0x35,0x0e,0x71,0x35,0xdc,0x2b,0x31,0x14,0x55,0x8d,0xf5,0x4a,0xe1,0x48,0xb0,0x57,0xfa,0xaf,0xa7,0x87,0x7b,0x27,0xc5,0x92,0xf1,0xa9,0x6f,0x81,0xef,0x95,0xdb,0x2c,0xe7,0x3f,0x00,0x00,0x00,0xff,0xff};`
the data len compressed is 0x90a, the data len uncompressed is 0x1c00.
when I call uncompress like this:
`uncompress(destbuf, &destlen, srcbuf, srclen); // destlen is 0x1c00, srclen is 0x90a`  the return value is Z_BUF_ERROR which means destbuf too small;  but in fact the uncompression succeeded.
and then when I call uncompress with larger dest buf:
`uncompress(destbuf,&destlen, srcbuf, srclen); // destlen is 0x1c01, and no other change`   the return value is Z_DATA_ERROR which means the input data was corrupted or incomplete.
I'm using the newst version of zlib.

**Comment by baosj0** [comment]
I step into the zlib src code, 
`    do {
        if (stream.avail_out == 0) {
            stream.avail_out = left > (uLong)max ? max : (uInt)left;
            left -= stream.avail_out;
        }
        if (stream.avail_in == 0) {
            stream.avail_in = len > (uLong)max ? max : (uInt)len;
            len -= stream.avail_in;
        }
        err = inflate(&stream, Z_NO_FLUSH);
    } while (err == Z_OK);`
the first time calling inflate, all data has been uncompressed, the err is Z_OK;
the second time calling inflate, the avail_out and avail_in is all zero,  then the return value is z_buf_error.

**Comment by madler** [comment]
That is an incomplete zlib stream. It's fine as far as it goes, but it ends before ever having a last deflate block or a zlib trailer. It appears to have been deliberately cut off using `Z_SYNC_FLUSH`, since it ends with an empty, non-last stored block.
