### ISSUE TITLE
DEBUG pre-processor causing Symbolic errors when zlib compiled for Static Release and built in a Debug Targeted Xcode Project

### ISSUE THREAD

**Issue by danoli3** [madler/zlib#79]
###  Issue:
In Xcode when building a Debug targeted project the IDE adds ```-DEBUG``` to the target. This is causing many errors for libraries that use zlib in it's release form and include headers which expose these parts of zlib when that ```-DEBUG``` command is turned on (default action).

#### Causing Symbolic link errors:
```
Undefined symbols for architecture i386:
  "_z_error", referenced from:
      _deflate in deflate.o
      _deflate_stored in deflate.o
      _deflate_slow in deflate.o
      _fill_window in deflate.o
      _longest_match in deflate.o
      _longest_match_fast in deflate.o
      _check_match in deflate.o
      ...
  "_z_verbose", referenced from:
      _deflate_stored in deflate.o
      _deflate_fast in deflate.o
      _deflate_slow in deflate.o
      _check_match in deflate.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Found in many places in zlib:
- ```#ifdef DEBUG``` https://github.com/madler/zlib/search?utf8=✓&q=%23ifdef+DEBUG&type=Code
- ```#ifndef DEBUG``` https://github.com/madler/zlib/search?utf8=✓&q=%23ifndef+DEBUG&type=Code

### Proposed change:
Swap out ```DEBUG``` for ```ZLIB_DEBUG```

**Comment by madler** [comment]
I have pushed a commit changing `DEBUG` to `ZLIB_DEBUG`.
