### ISSUE TITLE
Z_VERSION_ERROR test causes UBSan error

### ISSUE THREAD

**Issue by kai-renshaw** [madler/zlib#796]
Line 382 of `infcover.c`:

`ret = inflateInit_(&strm, ZLIB_VERSION - 1, (int)sizeof(z_stream));`

causes the following UBSan error:

`index -1 out of bounds for type 'char[7]'`

**Comment by fredgan** [comment]
It's just a test case. You can ignore this error.

**Comment by kai-renshaw** [comment]
Unfortunately we run the tests as part of the build process, so this error is breaking the build

**Comment by madler** [comment]
Remedied in https://github.com/madler/zlib/commit/3365464851a972fe8ad217b93e80c7cd185a8179 .
