### ISSUE TITLE
There are som PVS warnings in your zlib library.

### ISSUE THREAD

**Issue by morozmv** [madler/zlib#797]
Lvl ErrorCode CWE          Message                                                                                   Project Short file Line
2   V547         CWE-570   Expression 'sourceLen > (uLong) max' is always false.            ZLib compress.c 56
2   V547         CWE-570   Expression 'left > (uLong) max' is always false.                       ZLib compress.c 52
2   V1048       CWE-1164 Variable was assigned the same value.                                    ZLib ioapi.c 83
2   V1048       CWE-1164 The 'ret' variable was assigned the same value.                      ZLib iowin32.c 292
2   V1048       CWE-1164 The 'ret' variable was assigned the same value.                      ZLib iowin32.c 318
2   V1048       CWE-1164 The 'ret' variable was assigned the same value.                      ZLib iowin32.c 400
2   V1048       CWE-1164 The 'ret' variable was assigned the same value.                      ZLib iowin32.c 359
2   V1048       CWE-1164 The 's->pos_in_central_dir' variable
was assigned the same value.                                                                                         ZLib unzip.c 1284
2   V1048       CWE-1164 The 's->num_file' variable was assigned the same value. ZLib unzip.c 1283
2   V1051       CWE-754   Consider checking for misprints.
It's possible that the 'tmp_err' should be checked here.                                                ZLib zip.c 1586
2   V575         CWE-628   The potential null pointer is passed into 'memcpy' function.
Inspect the first argument. Check lines: 1980, 1965.                                                      ZLib zip.c 1980
2   V575         CWE-628   The potential null pointer is passed into 'memcpy' function.
Inspect the second argument. Check lines: 1994, 1965.                                                ZLib zip.c 1994
2   V769         CWE-119   The 'zi->ci.central_header' pointer in the 'zi->ci.central_header + 4' expression could be nullptr. In such case, resulting value will be senseless and it should not be used.
Check lines: 1141, 1136.                                                                                                 ZLib zip.c 1141
2   V793        CWE-691   It is odd that the result of the '+' operator is a part of the condition.
Perhaps, this statement should have been compared with something else.                 ZLib deflate.c 636
2   V1048      CWE-1164 The 'state->lencode' variable was assigned the same value. ZLib infback.c 463
2   V1048      CWE-1164 The 'state->mode' variable was assigned the same value.     ZLib infback.c 522
2   V547        CWE-570   Expression 'left > (uLong) max' is always false.                       ZLib uncompr.c 64
2   V547        CWE-570   Expression 'len > (uLong) max' is always false.                       ZLib uncompr.c 68
2   V793        CWE-691   It is odd that the result of the 'left + stream.avail_out' statement is a part of the condition.
Perhaps, this statement should have been compared with something else.                 ZLib uncompr.c 83

**Comment by irwir** [comment]
It should have been clearly specified what version of the library was analysed; otherwise line numbers might be incorrect.
Also, such lists usually have a few false positives and therefore require thorough manual investigation before posting.

For example, the very first warning would be invalid if sizeof(uInt)<sizeof(uLong).

> 2 V547 CWE-570 Expression 'sourceLen > (uLong) max' is always false. ZLib compress.c 56

**Comment by madler** [comment]
Those warnings provide no useful information, so I am closing the issue.
