### ISSUE TITLE
random access/zran using aligned byte entry points

### ISSUE THREAD

**Issue by jnorthrup** [madler/zlib#802]
I have contributed a PR  #801 for this issue.

I have made an attempt to continue the zran.c inflater loop and chunk it to 1 byte prior to allowing a call to `add_point` in order to proceed (the average of 4 bytes) on a byte boundary.  

the goals that this issue makes available is http range requests of data on aligned boundaries, and in-browser zlib clients and jdk zlib/JZLib libraries which are not current with the necessary inflatePrime function for bit-stuffing.

I have not found ports of zlib which contain inflatePrime and would go with those if they suited the usecases.

**Comment by madler** [comment]
See https://github.com/madler/zlib/commit/7e6dc429af8e430e3ae5e748fb34dd61128c5546 , and my comments on the PR.
