### ISSUE TITLE
Possible changes in minizip/unzip.c and minizip/zip.c

### ISSUE THREAD

**Issue by irwir** [madler/zlib#803]
Commit 138c93cffb76f5c24e4ae6e81e6210428856f825 has changed `TRYFREE` macro in `unzip.c`, but not in `zip.c`
It might be worth creating a local header file with common includes and definitions that are the same in zip and unzip code.

Another thing, `#ifdef STDC` block may repeatedly include `string.h` and `stdlib.h` that were already unconditionally included about ten lines above.

**Comment by fredgan** [comment]
> Commit https://github.com/madler/zlib/commit/138c93cffb76f5c24e4ae6e81e6210428856f825 has changed TRYFREE macro in unzip.c, but not in zip.c

YES, you are right. It should be changed, too.

> It might be worth creating a local header file with common includes and definitions that are the same in zip and unzip code.

Maybe worth or maybe not. This may change user's usage compatibility. 

> Another thing, #ifdef STDC block may repeatedly include string.h and stdlib.h that were already unconditionally included about ten lines above.

I agree.

---

You could submit a PR. Or I submit a PR for you.

**Comment by irwir** [comment]
@fredgan
> This may change user's usage compatibility.

This is only a small additional header file.  What other changes in compatibility you are expecting?

> You could submit a PR. Or I submit a PR for you.

I could but the necessity of making a PR is unclear so far and your services are not required.

**Comment by Neustradamus** [comment]
@fredgan: Have you seen the last @irwir comment?

**Comment by madler** [comment]
Resolved.

**Comment by Neustradamus** [comment]
Linked to:
- https://github.com/madler/zlib/pull/836
