### ISSUE TITLE
zran.c doesn't support big chunks?

### ISSUE THREAD

**Issue by eggitta** [madler/zlib#807]
Hi,

I'm using deflate_index_build() and deflate_index_extract() to extract data from compressed files, and it works very well :)
But I encounter some problem when extracting big chunks from .gz file.
I take a look at the source code, maybe it's caused by the type of both 'len' and return value are 'int', so the max supported chunk size is 2GB, right?
_**int** deflate_index_extract(FILE *in, struct deflate_index *index, off_t offset,
                          unsigned char *buf, **int** len)_

How can I extract big chunks (> 2GB) from .gz file? Would you help to give me some suggestions? Thanks!

Regards,
Fan

**Comment by madler** [comment]
Try the version on the develop branch. It uses `size_t`.

**Comment by eggitta** [comment]
Hi Mark,

Sure, I'll give it a try.
Thanks for the great help!

Regards,
Fan
