### ISSUE TITLE
test/infcover.c does not compile on linux

### ISSUE THREAD

**Issue by Dead2** [madler/zlib#81]
The following definition in infcover.c fixes the compile-error, but I am unsure whether this is enough?

+/* reallocf is BSD-specific */
+#ifndef reallocf
+#  define reallocf realloc
+#endif

**Comment by mtl1979** [comment]
#include <bsd/stdlib.h>

should make it find reallocf() on Linux as long as <bsd/stdlib.h> exists... requires -lbsd when linking

**Comment by madler** [comment]
I have pushed a commit that avoids the use of `reallocf()`.
