### ISSUE TITLE
Regression in compression speed from v 1.2.11 to 1.2.13

### ISSUE THREAD

**Issue by amd-rajangra** [madler/zlib#820]
Hi,
I see there is noticeable regression in compression speed on lower compression levels. This observation is noticed with below config :
Benchmarking Utility : https://github.com/inikep/lzbench
Dataset : Silesia
Compiler : GCC 13
Machine : AMD EPYC 9654
LZBench Config :
./lzbench -v -p1 -i10,10 -t16,16 -ezlib,1 -r <dataset>

1.2.11
Compression Speed | Decompression Speed | Compression Ratio
122.09 MB/s             | 399.67 MB/s                 | 41.55

1.2.13
Compression Speed | Decompression Speed | Compression Ratio
120.31 MB/s             | 402.25 MB/s                 | 41.55

%change
Compression Speed | Decompression Speed | Compression Ratio
-1.458 %                   | 0.645%                 | 0 %

**Comment by rajangra25** [comment]
@madler Is this due to change in deflate data structure ?

**Comment by AraHaan** [comment]
I think so.

**Comment by amd-rajangra** [comment]
@madler Same regression still observed in 1.3 release. Do you have any plan to fix this in future ?

**Comment by madler** [comment]
This is due to a bug fix (https://github.com/madler/zlib/commit/5c44459c3b28a9bd3283aaceab7c615f8020c531) that now writes two bytes into a table, instead of one 16-bit write previously, for each distance. I will take a look, but I am finding it difficult to get excited over 1.5%.

**Comment by madler** [comment]
I added a commit (https://github.com/madler/zlib/commit/ac8f12c97d1afd9bafa9c710f827d40a407d3266) that provides the option to use more memory, in order to recover most of the compression speed loss of the bug fix in 1.2.12.

I say "most", since testing on my machine and compiler (an Apple M1 and clang) shows that on the order of 2/3 of the increase in execution cycles is remedied. It is going back to exactly what was done in 1.2.11, but with an 80K instead of a 64K pending/symbols buffer. My guess is that the 64K fit more nicely in a cache.

Please give it a try.

**Comment by amd-rajangra** [comment]
Thanks @madler for the reply and patch. I will benchmark this patch over 1.13 and share results here

**Comment by amd-rajangra** [comment]
I have confirmed this patch recovers almost all of the regression

**Comment by madler** [comment]
Numbers?

**Comment by amd-rajangra** [comment]
@madler Below are the numbers from same machine and config:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rajangra/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rajangra/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Version | Level | Compression Speed   (MB/s) | Decompression   Speed (MB/s) | Compression Ratio |   | %diff wrt 1.2.11 |   |  
-- | -- | -- | -- | -- | -- | -- | -- | --
1.2.11 | 1 | 123.225 | 401.25 | 41.55 |   | CS | DS | CR
1.3_without_LIT_MEM | 1 | 119.95 | 403.25 | 41.55 |   | -2.66% | 0.50% | 0.00%
1.3_with LIT_MEM | 1 | 123.525 | 404.9167 | 41.55 |   | 0.24% | 0.91% | 0.00%



</body>

</html>

**Comment by madler** [comment]
Thank you.

**Comment by AraHaan** [comment]
> @madler Below are the numbers from same machine and config:
> Version 	Level 	Compression Speed (MB/s) 	Decompression Speed (MB/s) 	Compression Ratio 	  	%diff wrt 1.2.11 	  	 
> 1.2.11 	1 	123.225 	401.25 	41.55 	  	CS 	DS 	CR
> 1.3_without_LIT_MEM 	1 	119.95 	403.25 	41.55 	  	-2.66% 	0.50% 	0.00%
> 1.3_with LIT_MEM 	1 	123.525 	404.9167 	41.55 	  	0.24% 	0.91% 	0.00%

And at lv 9?

**Comment by madler** [comment]
The difference would be _much_ less pronounced at level 9. Then the execution time would be completely dominated by string searching.

**Comment by AraHaan** [comment]
> The difference would be _much_ less pronounced at level 9. Then the execution time would be completely dominated by string searching.

Interesting, is there a way to help reduce string search time then when at lv 9? Might help improve performance even for people doing lv 9 compressions.
