### ISSUE TITLE
Should deflateBound return the tight bound for default w_bits and memLevel 9? 

### ISSUE THREAD

**Issue by michalc** [madler/zlib#822]
At the moment in [deflateBound](https://github.com/madler/zlib/blob/04f42ceca40f73e2978b50e93806c2a18c1281fc/deflate.c#L753) if memLevel is 9 with default w_bits, then it looks like one of the conservative bounds is returned. This strikes me as odd since sizes should(?) be smaller than for memLevel 8 when the lower/tighter bound is returned.

Can the tight bound be returned instead in this case? So specifically
```c
if (s->w_bits != 15 || s->hash_bits != 8 + 7)
```
changed to
```
if (s->w_bits != 15 || s->hash_bits < 8 + 7)
```
(If so - am happy to raise a PR)

**Comment by madler** [comment]
No. In fact it can be larger.

**Comment by michalc** [comment]
Oh good to know!
