### ISSUE TITLE
Error in using gzungetc immediately after gzopen or gzdopen

### ISSUE THREAD

**Issue by hopper-vul** [madler/zlib#837]
I found that if we call gzungetc after gzopen immediately with read mode, the program will crash in the function calling because it tries to access ` state->x.next` and the memory is an unknown address (state->out is uninitialized).

I read the comments in `zlib.h`, it said that "If gzungetc is used immediately after gzopen or gzdopen, at least the
   output buffer size of pushed characters is allowed. (See gzbuffer above.)". However, I can not figure out it well.

Is it better to add an error `gz_error` for users that if they call this API function immediately before push any chars to the buffer?

Here is an example for reproduction.

```
#include "zlib.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <math.h>
typedef uint8_t   u8;   
typedef uint16_t  u16;  
typedef uint32_t  u32;  
typedef uint64_t  u64;
typedef unsigned int usize;
typedef int8_t  i8;
typedef int16_t i16;
typedef int32_t i32;
typedef int64_t i64;
typedef int isize;

int main() {
    i32 v0 = 101; // c
    u8 v1_tmp[] = {1, 0, }; // file_buf
    u8 *v1 = malloc(sizeof v1_tmp);
    memcpy(v1, v1_tmp, sizeof v1_tmp);
    char* path_v2 = "file_fd_1";
    FILE *f_v2 = fopen(path_v2, "wb");
    fwrite(v1, sizeof v1_tmp, 1, f_v2);
    fclose(f_v2);
    char* v2 = path_v2; // fd
    i8 v3_tmp[] = {114, 0, }; // mode
    i8 *v3 = malloc(sizeof v3_tmp);
    memcpy(v3, v3_tmp, sizeof v3_tmp);
    i8 *v4 = v3; // mode
    struct gzFile_s *v5 = gzopen(v2, v4); // file
    if (v5 == NULL) return 0;
    struct gzFile_s *v7 = v5; // file
    i32 v8 = gzungetc(v0, v7); // $target
}
```

**Comment by madler** [comment]
Thanks! That is a big fat bug. It can be instantiated with just:

```
#include "zlib.h"

int main() {
    gzFile gz = gzopen("foo.gz", "r");
    return gzungetc(0, gz);
}
```

Fixed with https://github.com/madler/zlib/commit/7dd6aa72455ef1f2aacdc28a00d1eaf632d59593
