### ISSUE TITLE
Release v1.2.14

### ISSUE THREAD

**Issue by MaskRay** [madler/zlib#842]
Thank you for fixing #633. As we can see in various issues linking #633, having v1.2.14 will help many projects get rid of `-Wno-deprecated-non-prototype` CFLAGS workaround.

**Comment by Neustradamus** [comment]
@MaskRay: @madler has done a 1.3 few hours ago.

**Comment by MaskRay** [comment]
Thanks for releasing v1.3! https://github.com/madler/zlib/commit/09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851
