### ISSUE TITLE
inflateSync() looks wrong to me

### ISSUE THREAD

**Issue by sh1boot** [madler/zlib#848]
This pair of lines shifts `state->hold` right and decreases `state->bits` by the same value:
https://github.com/madler/zlib/blob/79a0e447a0dfa32979420cb21cfb96d684b2c9d5/inflate.c#L502-L505

But this pair of lines shifts `state->hold` _left_ and decreases `state->bits` by the same value:
https://github.com/madler/zlib/blob/79a0e447a0dfa32979420cb21cfb96d684b2c9d5/inflate.c#L1388-L1391

That's a bug, right?

**Comment by madler** [comment]
Yep. Thanks. It's fixed on my local branch.
