### ISSUE TITLE
Unused code part in inftrees.c?

### ISSUE THREAD

**Issue by bastie** [madler/zlib#850]
Hello,
can someone explained, in wich case the while loop is executed? 

<pre>
            /* determine length of next table */
            curr = len - drop;
            left = (int)(1 << curr);
            while (curr + drop < max) {
                left -= count[curr + drop];
                if (left <= 0) break;
                curr++;
                left <<= 1;
            }
</pre>

In result of transpiled to Swift, swiftc means curr+drop < max is never ever true, because curr = len-drop before. But it was a test translation from KI and so I asked.

If I starts make test with printf in the while loop no output is displayed.

thanks
Sebastian

**Comment by madler** [comment]
Happens all the time. You must not have tested it with your printf very much. It happens when `len < max`, which is when the next sub-table is shorter than the last sub-table.
