### ISSUE TITLE
contrib\minizip\unzip.c forces definition of NOUNCRYPT preprocessor symbol

### ISSUE THREAD

**Issue by NotMeGuv** [madler/zlib#862]
By forcing NOUNCRYPT to be defined, the code will not work with encrypted files within a zip.
See unzip.c line 71

**Comment by Neustradamus** [comment]
@madler: Can you look this ticket?

**Comment by Neustradamus** [comment]
@madler: Can you look this ticket?

**Comment by madler** [comment]
https://github.com/madler/zlib/commit/da5937705d1656148b18348e57186aa0592a907d
