### ISSUE TITLE
zlib1.3 link error on linux ndk 

### ISSUE THREAD

**Issue by xengine-qyt** [madler/zlib#882]
linux ndk 25c
does not work --static of  the configure option

when i link app:
error: relocation R_AARCH64_ADR_PREL_PG_HI21 cannot be used against symbol 'z_errmsg'; recompile with -fPIC

**Comment by ctxqlxs** [comment]
how to resolve it ?

**Comment by ctxqlxs** [comment]
@xengine-qyt

**Comment by xengine-qyt** [comment]
> @xengine-qyt


https://github.com/madler/zlib/pull/883
