### ISSUE TITLE
please look at inflate.c file for typo

### ISSUE THREAD

**Issue by akis-chatz** [madler/zlib#906]
file inflate.c has some typo? line 640 ive open with text editor and two brackets are shown error, not sure if there was some error in the code, please confirm that the file is correct.. perhaps some condition deleted by mistake.. thanks..

**Comment by madler** [comment]
It's correct. The expression continues on line 644.

**Comment by akis-chatz** [comment]
thanks for the fast response! the closed brackets that show missing are on line 1234 and 1264..
it is a big function, so i thought it started at line 640.. sorry about the assumption, im not expert and didnt realize it was correct..
i will try to see if there is some false warning in the sublime text editor.. thanks again for your time..
