### ISSUE TITLE
Issues recompressing legacy ZLIB files

### ISSUE THREAD

**Issue by MontyMole98** [madler/zlib#929]
There are some ZLIB-compressed files from games made in, like, 2015, which I wish to edit. While these files seem to be accurately decompress, I can't get them recompressed in remotely the same way. Games just crash using the latest versions of ZLIB. How should I compress using the older method used around that timeframe?

Thank you for helping in advance!

**Comment by madler** [comment]
What exactly do you mean by "remotely the same way"?

zlib compressed data has been forward and backward compatible for the almost thirty years of its existence. Perhaps your app is doing some other check to guard against modifications.

**Comment by MontyMole98** [comment]
Figured out that there was a header in the game files that doesn't exist in
the most recent version of ZLIB. Didn't notice in the first place, but now
I did.

**Comment by madler** [comment]
I will assume then that you have resolved your issue.
