### ISSUE TITLE
Files bigger than 4 gb?

### ISSUE THREAD

**Issue by UltraEngine** [madler/zlib#954]
Before I move my code over to this library, can you confirm that this library and the included version of minizip will support zip files that contain archives bigger than 4 gb in size?

**Comment by madler** [comment]
zlib doesn't know anything about zip files, and has always supported the compression and decompression of any size input.

It is my understanding that minizip is designed to support the Zip64 format, which would include zip files larger than 4GB, uncompressed zip file entries larger than 4GB, and zip files with more than 65,535 entries. As far as I know it works. However I cannot vouch for that code, as it is not mine. The code in contrib is not part of zlib, and is provided as a courtesy. You can contact the author, Gilles Vollant @gvollant, for more information.

I would say though that no degree of promises or affirmations from the authors of any code should take the place of your own testing of said code in your application.
