### ISSUE TITLE
Code improvement for iowin32.c

### ISSUE THREAD

**Issue by Lwisce** [madler/zlib#956]
I found that in the iowin32.c, there are some function parameters and declared variables that are not used. This will generate warnings in the MSVC compiler. Can we consider using (void) for unused function parameters and directly deleting unused variables to avoid warnings?
Here is example:

> voidpf ZCALLBACK win32_open64_file_func(voidpf opaque, const void* filename, int mode) {
> \-    const char* mode_fopen = NULL;
> \+    (void)opaque;
>      DWORD dwDesiredAccess,dwCreationDisposition,dwShareMode,dwFlagsAndAttributes ;
>      HANDLE hFile = NULL;

**Comment by madler** [comment]
Ok. Warnings averted.
