### ISSUE TITLE
Visual Studio .def file error

### ISSUE THREAD

**Issue by topwizprogramming** [madler/zlib#957]
I downloaded version 1.3.1 and found two issues.

There isn't a vc16 folder (VS 2019). I created one by copying vc17 (VS 2022) and changing the Platform Toolset from v143 to v142 in all the project files.

The .def file has version 1.3.1 but Visual Studio only supports one dot in the version. This caused a compile error. I changed it to 1.31 and it compiled without issue.

**Comment by madler** [comment]
Thanks. Yes, the version number is fixed on the develop branch. (https://github.com/madler/zlib/commit/b14484997a50c01b8d78f9db32516423573fc083)

I am considering deleting all of the vc folders, since cmake can be used to automatically generate the build files.
