### ISSUE TITLE
Can we clean clang compiler warning ”reserve-id-macro"?

### ISSUE THREAD

**Issue by Lwisce** [madler/zlib#961]
When compile with clang, some macro like "_ZLIBIOAPI64_H" will cause  ”reserve-id-macro" warning. Can we consider remove the under scar before the macro to avoid it? For example:

>  \- #ifndef _ZLIBIOAPI64_H
>  \- #define _ZLIBIOAPI64_H
>  \+ #ifndef ZLIBIOAPI64_H
>  \+ #define ZLIBIOAPI64_H

**Comment by madler** [comment]
Sure. Fixed in local branch.
