### ISSUE TITLE
zlib-1.3.1, deflate.c, line 497

### ISSUE THREAD

**Issue by xuyun018** [madler/zlib#962]
s->pending_buf = (uchf *) ZALLOC(strm, s->lit_bufsize, LIT_BUFS);
    s->pending_buf_size = (ulg)s->lit_bufsize * 4;
应该为
    s->pending_buf_size = (ulg)s->lit_bufsize * LIT_BUFS;

**Comment by nmoinvaz** [comment]
https://github.com/madler/zlib/commit/ac8f12c97d1afd9bafa9c710f827d40a407d3266#r137966340

**Comment by madler** [comment]
The code is correct as is. The suggested change would break the code.
