### ISSUE TITLE
zlib.error: Error -3 while decompressing data: invalid code -- missing end-of-block

### ISSUE THREAD

**Issue by zoumath19** [madler/zlib#971]
Issue:

Cannot extract specific file, due to corruption, read more @ Reproduce Issue

Error Dump:

 zip_obj.testzip()
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 1475, in testzip
    while f.read(chunk_size):     # Check CRC-32
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 957, in read
    data = self._read1(n)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/zipfile.py", line 1033, in _read1
    data = self._decompressor.decompress(data, n)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           
Reproduce Issue:

Python 3.11.8 Docker 
Attempting to decompress a corrupt file, libre office says it's corrupt and attempts to restore

**Comment by madler** [comment]
You have a corrupt zip file, and zlib is correctly reporting it as corrupt. So what's the issue?

**Comment by madler** [comment]
No response to my query, so I am closing this issue.
