### ISSUE TITLE
Inconsistency with new LIT_MEM (likely bug)

### ISSUE THREAD

**Issue by bsdphk** [madler/zlib#973]
In deflate.c:

    s->pending_buf = (uchf *) ZALLOC(strm, s->lit_bufsize, LIT_BUFS);
    s->pending_buf_size = (ulg)s->lit_bufsize * 4;

I think that '4' should also be LIT_BUFS ?

**Comment by madler** [comment]
No, it should be 4. If it were LIT_BUFS, then _that_ would be a bug.
