### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by MarkJonas** [madler/zlib#98]
I want to use [Sourcegraph](https://sourcegraph.com) for zlib code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/madler/zlib. (It should only take 30 seconds.)

Thank you!

**Comment by mtl1979** [comment]
That doesn't make sense as Sourcegraph doesn't support C files.
