### ISSUE TITLE
CRC32C support

### ISSUE THREAD

**Issue by mullermp** [madler/zlib#981]
Hello. Is there planned support for CRC32C?

**Comment by madler** [comment]
In zlib? No. the zlib, gzip, and zip formats all use [CRC-32/ISO-HDLC](https://reveng.sourceforge.io/crc-catalogue/17plus.htm#crc.cat.crc-32-iso-hdlc). There is no application for [CRC-32/ISCSI](https://reveng.sourceforge.io/crc-catalogue/17plus.htm#crc.cat.crc-32-iscsi) in zlib.

You can look to [crcany](https://github.com/madler/crcany) for the generation of C code to compute any CRC. Also [this answer on stackoverflow](https://stackoverflow.com/a/17646775/1180620) has my fast code to use the Intel hardware instruction for CRC-32C.

**Comment by mullermp** [comment]
Thanks for your prompt response. I am trying to find the best place to put a CRC32C implementation in the Ruby ecosystem. There is a gem called `zlib` that interfaces with this library that has CRC32 checksum code and it felt natural to put CRC32C there. I'm not sure how much you've used Ruby, but do you have any opinions on where that would live?

**Comment by madler** [comment]
I don't know where it would best live in the standard gems. A quick google search turned up this: https://github.com/postmodern/digest-crc

**Comment by mullermp** [comment]
Yep, I've seen that one. I try to avoid dependencies for our library (AWS SDK for Ruby), which is why my motivation was for it to exist in a bundled/standard gem such as zlib.
