### ISSUE TITLE
Undefined symbol error for Bcrypt

### ISSUE THREAD

**Issue by bhavyajn7599** [madler/zlib#986]
I am trying to compile Minizip for Windows platform and after compilation I am using libminizip.lib in my project unresolved external symbol error for all bcrypt APIs

![image](https://github.com/madler/zlib/assets/171550500/420ed971-6a59-4a1b-ae97-7e27ed583580)

Bcrypt
Then i ran dumpbin /SYMBOLS libminizip.lib this command for checking all the symbols and i saw that these symbols are all undefined.
![image](https://github.com/madler/zlib/assets/171550500/30569ed8-56bf-43f5-95eb-618c84e291e0)

This is the command I am using for compiling Minizip project I am using version 4.0.4

cmake -S . -B build -D MZ_BUILD_TESTS=ON -DZSTD_TAG=dev -D MZ_DECOMPRESS_ONLY=ON -D MZ_FORCE_FETCH_LIBS=ON -D MZ_FILE32_API=ON -D MZ_COMPRESS_ONLY=ON -D MZ_SIGNING=ON -D MZ_LIBBSD=ON -D MZ_BUILD_UNIT_TESTS=ON -D MZ_CODE_COVERAGE=ON -D MZ_ICONV=ON -DZLIB_TAG=develop -D MZ_LIBCOMP=ON -D MZ_OPENSSL=ON -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON

[Build_log.txt](https://github.com/user-attachments/files/15530843/Build_log.txt)
This the log of build. Can you check why these API's are not getting defined.
I tried compiling with minizip 3.0.10 and in that I am not facing any errors as I can see that mz_crypt_winvista.c file was added after 3.0.10 . Can you check if that file has some issue. Or am i missing something?

**Comment by madler** [comment]
This appears to be coming from [minizip-ng](https://github.com/zlib-ng/minizip-ng). Perhaps submit an issue there.
