### ISSUE TITLE
Size of file before compression in the archive shows as the Original size - Int 32 max size(4294967295)

### ISSUE THREAD

**Issue by Neena1414** [madler/zlib#998]
Hello.. In my project I am using minizip from Zlib (version 1.2.3). I am not sure if this has large file support(greater than 4 GB).
I can see zipOpenNewFileInZip4 functions but no functions like zipOpenNewFileInZip64 (or any function with 64 appended). It may be very basic question, not sure  from which version do we have the large file support. What I noticed in the .zip produced using this mizip library, the size of the file is the remaining bytes after reducing the max int32 value(4294967295) Could anyone please guide me

![image](https://github.com/user-attachments/assets/9c29d8a6-9efb-40af-8fe7-ebbd013f7743)

**Comment by madler** [comment]
Your question is unclear, but yes, minizip provides full support for the Zip64 format, permitting larger than 4GB zip files, larger than 4GB entries, and more than 65536 entries. If you have further questions, they should be asked on stackoverflow.com.
